package dslspec

// The proof that the PUBLISHED grammar accepts the language (memql#5388, D24).
//
// Every other test beside this one is a NAME-level agreement check: that each
// construct has a production, that the operator ladder names the table's
// levels, that a clause's grammar opens on its own word. All of them pass over
// a production whose right-hand side is structurally wrong -- a missing
// optional, a repetition in the wrong place, two clauses nested the wrong way
// round -- because none of them ever opens a `.memql` file.
//
// That gap matters because of what the grammar is FOR. It is published so a
// model can be given the language in a prompt and so a decoder can be
// constrained by it. A grammar wrong in a way no test can see does not fail
// loudly: it produces confidently wrong MemQL, and the failure reads as "the
// model is bad at MemQL".
//
// So: a recognizer over the language's own token stream, reading the grammar
// as data (internal/bnfmatch), and the real corpus run through it --
//
//   - every `.memql` file of the embedded dsl/ tree, and
//   - every conformance case the engine LOADS, plus every fixture those cases
//     are loaded beside, plus every expression a lower/evaluate case holds.
//
// A file the engine loads and the published grammar rejects is a defect in the
// grammar, and the failure names the file, where the recognizer stopped and
// the production it stopped in.
//
// The grammar is a deliberate SUPERSET of what the engine accepts -- it is
// syntax only, and says nothing about what an annotation means or whether a
// name resolves -- so nothing here asks it to reject what the engine refuses
// for semantic reasons. What it must reject is nonsense, and
// TestPublishedGrammarRefusesNonsense is that half.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/znasllc-io/memql/component/language/dslspec/internal/bnfmatch"
	"github.com/znasllc-io/memql/component/language/functions"
	"github.com/znasllc-io/memql/component/language/parser"
)

// repoRoot is this package's path to the repository root. component/language
// is its own module, so the trees the grammar is proved against -- dsl/ and
// test/conformance/ -- are read from disk rather than imported.
const repoRoot = "../../.."

// docCommentTerminal is the one terminal the MemQL lexer reads as no token at
// all. TestDocCommentIsTheOnlyTerminalTheLexerHides pins that.
const docCommentTerminal = "///"

// publishedGrammar reads the grammar from the COMMITTED PAGE rather than from
// BNF(), because the page is the artifact: it is what a reader is handed, what
// the docs publish and what the memqlGrammar() builtin serves. Proving the
// renderer's output would leave the published bytes unproven whenever the two
// differ, which is exactly the state `make docs-grammar-check` exists to
// catch and exactly when a reader is most likely to be holding the stale one.
func publishedGrammar(t *testing.T) (*bnfmatch.Grammar, string) {
	t.Helper()
	page := filepath.Join(repoRoot, GrammarPath)
	raw, err := os.ReadFile(page)
	if err != nil {
		t.Fatalf("%s is missing (%v); it is generated by `make docs-grammar` and is the artifact this test proves", page, err)
	}
	block := fencedEBNF(t, string(raw))
	// The committed page and the tables must agree, or the recognizer would
	// prove a grammar nobody generates. That agreement is also
	// TestGrammarPageIsGenerated's whole subject; asserting it here as well is
	// what lets the rest of this file read the page with no doubt about which
	// grammar it holds.
	if block != BNF() {
		t.Fatalf("the ebnf block committed in %s is not what BNF() renders; run `make docs-grammar` and "+
			"commit the result. Until they agree this test would be proving a grammar nobody publishes.", GrammarPath)
	}
	g, err := bnfmatch.ParseGrammar(block)
	if err != nil {
		t.Fatalf("the published grammar does not read as the notation its own header describes: %v", err)
	}
	if undefined := g.Undefined(); len(undefined) > 0 {
		t.Errorf("the published grammar references productions it does not define: %s.\n"+
			"A reference with no production is a dead end wherever it is reached, so the grammar cannot "+
			"derive anything that needs it.", strings.Join(undefined, ", "))
	}
	return g, block
}

// fencedEBNF pulls the one ```ebnf block out of the committed page.
func fencedEBNF(t *testing.T, page string) string {
	t.Helper()
	const open = "```ebnf\n"
	i := strings.Index(page, open)
	if i < 0 {
		t.Fatalf("%s holds no ```ebnf block; the grammar is published as one", GrammarPath)
	}
	rest := page[i+len(open):]
	j := strings.Index(rest, "```")
	if j < 0 {
		t.Fatalf("%s opens an ```ebnf block and never closes it", GrammarPath)
	}
	return rest[:j]
}

// source is one thing the grammar must derive: a file or an expression, and
// where it came from.
type source struct {
	// what names the file, and for a corpus case the verdict that put it here.
	what string
	// start is the production the recognition begins at.
	start string
	text  string
}

// TestPublishedGrammarDerivesTheEmbeddedTree runs every .memql file of the
// shipped DSL tree through the published grammar. These are the files the
// engine loads on every boot: if the grammar cannot derive one, the grammar is
// describing a language this cluster does not write.
func TestPublishedGrammarDerivesTheEmbeddedTree(t *testing.T) {
	g, _ := publishedGrammar(t)
	files := embeddedTreeFiles(t)
	// A walk that finds nothing must FAIL rather than pass over an unchecked
	// tree: a corpus gate is exactly the shape that rots that way.
	if len(files) < 250 {
		t.Fatalf("found only %d .memql files under dsl/; the walk is broken, not the tree", len(files))
	}
	sources := make([]source, 0, len(files))
	for _, f := range files {
		raw, err := os.ReadFile(f)
		if err != nil {
			t.Fatalf("read %s: %v", f, err)
		}
		rel, _ := filepath.Rel(repoRoot, f)
		sources = append(sources, source{what: rel, start: "file", text: string(raw)})
	}
	derived := deriveAll(t, g, sources)
	t.Logf("the published grammar derives %d/%d files of the embedded dsl/ tree", derived, len(sources))
}

// TestPublishedGrammarDerivesTheConformanceCorpus runs every conformance case
// the engine LOADS through the published grammar, plus the fixtures those
// cases are loaded beside. A case the corpus says loads and the grammar
// refuses is the same defect as a tree file it refuses; the corpus is where
// the language's own rules are written down one at a time, so it reaches forms
// the shipped tree happens not to use.
func TestPublishedGrammarDerivesTheConformanceCorpus(t *testing.T) {
	g, _ := publishedGrammar(t)
	sources := corpusSources(t)
	if len(sources) < 200 {
		t.Fatalf("found only %d accepting conformance cases; the corpus walk is broken, not the corpus", len(sources))
	}
	derived := deriveAll(t, g, sources)
	t.Logf("the published grammar derives %d/%d accepting conformance sources", derived, len(sources))
}

// deriveAll recognizes every source, in parallel, and reports each failure
// with the file, where the recognizer stopped and the production it was in.
// Parallel rather than sampled: a sampled gate is a gate with a hole, and the
// hole is wherever the sample did not look.
func deriveAll(t *testing.T, g *bnfmatch.Grammar, sources []source) int {
	t.Helper()
	type outcome struct {
		src  source
		msg  string
		defs []string
	}
	results := make([]outcome, len(sources))
	workers := runtime.GOMAXPROCS(0)
	var (
		wg   sync.WaitGroup
		next = make(chan int)
	)
	go func() {
		for i := range sources {
			next <- i
		}
		close(next)
	}()
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range next {
				results[i] = outcome{src: sources[i]}
				msg, defs := derive(g, sources[i])
				results[i].msg, results[i].defs = msg, defs
			}
		}()
	}
	wg.Wait()

	derived := 0
	defects := map[string]string{}
	for _, r := range results {
		if r.msg == "" {
			derived++
		} else {
			t.Errorf("%s", r.msg)
		}
		for _, d := range r.defs {
			if _, seen := defects[d]; !seen {
				defects[d] = r.src.what
			}
		}
	}
	for _, d := range sortedDefects(defects) {
		t.Errorf("the published grammar is not readable as a grammar: %s (first reached from %s)", d, defects[d])
	}
	return derived
}

// derive recognizes one source, returning the failure message when the
// grammar does not derive it and the grammar defects the recognition ran into.
func derive(g *bnfmatch.Grammar, s source) (string, []string) {
	tokens, err := bnfmatch.Tokens(s.text)
	if err != nil {
		// A file the lexer refuses is not this test's subject: the parser
		// would refuse it too, and the corpus guard in parser/ owns that.
		return fmt.Sprintf("%s: does not lex (%v); the grammar cannot be held to a file the lexer refuses", s.what, err), nil
	}
	res := bnfmatch.Match(g, s.start, tokens)
	var defects []string
	for _, n := range res.Undefined {
		defects = append(defects, "<"+n+"> is referenced but never defined")
	}
	for _, n := range res.Prose {
		defects = append(defects, "<"+n+"> is written as prose, so nothing can derive from it")
	}
	for _, n := range res.CharOnly {
		defects = append(defects, "<"+n+"> is a character-level production reached at token level")
	}
	for _, n := range res.InvisibleTerminals {
		// `///` is the one terminal the lexer reads as no token at all: a doc
		// comment leaves the stream on a side channel before the parser sees
		// it, which is why <doc-comment> is always written under a `*`. Any
		// OTHER such terminal is a production nothing can match.
		if n == docCommentTerminal {
			continue
		}
		defects = append(defects, fmt.Sprintf("the terminal %q is read as no token at all, so nothing can match it", n))
	}
	for _, n := range res.CharacterTerminals {
		defects = append(defects, fmt.Sprintf("the character terminal %q is reached at token level", n))
	}
	for _, n := range res.LeftRecursive {
		defects = append(defects, "<"+n+"> is left-recursive")
	}
	if res.OK {
		return "", defects
	}
	return fmt.Sprintf("%s: the published grammar does not derive this %s.\n"+
		"    stopped at %s\n"+
		"    in %s\n"+
		"    The grammar is generated (component/language/dslspec/grammar.go) and is handed to models as "+
		"%s: a production it cannot derive this file from is a form the model will be taught not to write.",
		s.what, startNoun(s.start), res.Where(tokens), res.In(), GrammarPath), defects
}

func startNoun(start string) string {
	if start == "file" {
		return "file"
	}
	return start
}

func sortedDefects(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// embeddedTreeFiles lists every .memql file the engine's embedded tree holds.
// dsl/_reference/ is excluded deliberately: those are the don't-do-this
// skeletons, the one place a retired form is written on purpose, and the
// loader skips them for the same reason (a `_`-prefixed directory is
// soft-disabled).
func embeddedTreeFiles(t *testing.T) []string {
	t.Helper()
	root := filepath.Join(repoRoot, "dsl")
	if _, err := os.Stat(root); err != nil {
		t.Skipf("dsl tree not present: %v", err)
	}
	var files []string
	err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if strings.HasPrefix(d.Name(), "_") || strings.HasPrefix(d.Name(), ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(p, ".memql") {
			files = append(files, p)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk dsl/: %v", err)
	}
	sort.Strings(files)
	return files
}

// corpusCase is the part of one conformance case this test reads. The full
// format, and the one decoder that owns it, are in test/conformance (the
// runner's corpusCase); the two fields below are the only ones that decide
// whether a case is something the engine LOADS.
type corpusCase struct {
	File    string `json:"file"`
	Verdict string `json:"verdict"`
	// Call names a logic an evaluate case runs, and is what tells the two
	// shapes of expression case apart: with it the file is a .memql file, and
	// without it the file holds the expression alone.
	Call string `json:"call"`
}

// corpusSources collects every conformance source the engine accepts: each
// case whose verdict loads (load_ok, lower, evaluate -- the corpus's own
// phrase, and what its completeness gates read), and each directory's
// fixture.memql, which is loaded beside every case in it.
func corpusSources(t *testing.T) []source {
	t.Helper()
	root := filepath.Join(repoRoot, "test", "conformance")
	if _, err := os.Stat(root); err != nil {
		t.Skipf("conformance corpus not present: %v", err)
	}
	var out []source
	err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || d.Name() != "expect.json" {
			return err
		}
		dir := filepath.Dir(p)
		rel, _ := filepath.Rel(repoRoot, dir)
		raw, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		var ef struct {
			Cases []corpusCase `json:"cases"`
		}
		if err := json.Unmarshal(raw, &ef); err != nil {
			return fmt.Errorf("%s: %w", p, err)
		}
		if fixture, err := os.ReadFile(filepath.Join(dir, "fixture.memql")); err == nil {
			out = append(out, source{what: rel + "/fixture.memql", start: "file", text: string(fixture)})
		}
		for _, c := range ef.Cases {
			start := ""
			switch {
			case c.Verdict == "load_ok":
				start = "file"
			case c.Verdict != "lower" && c.Verdict != "evaluate":
				continue // a refusal: the engine does not accept it either.
			case c.Call != "":
				start = "file" // an evaluate case with `call` declares logic.
			default:
				start = "expression"
			}
			text, err := os.ReadFile(filepath.Join(dir, c.File))
			if err != nil {
				return fmt.Errorf("%s names %s: %w", p, c.File, err)
			}
			out = append(out, source{
				what:  fmt.Sprintf("%s/%s [%s]", rel, c.File, c.Verdict),
				start: start,
				text:  string(text),
			})
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk the conformance corpus: %v", err)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].what < out[j].what })
	return out
}

// TestPublishedGrammarRefusesNonsense is the other half. The grammar is a
// deliberate superset of what the engine accepts, so it is not asked to refuse
// what the engine refuses for SEMANTIC reasons -- an annotation on the wrong
// receiver, a name that does not resolve, a retired call the parser names by
// its replacement. It must refuse nonsense, or a recognizer that accepts
// everything would have proved nothing above.
//
// Every case is a PAIR that differs only in the fault: the good twin must
// derive and the bad one must not. Without the twin a case can pass for the
// wrong reason -- the whole shape being underivable rather than the fault --
// and it would go on passing after the fault stopped being one.
func TestPublishedGrammarRefusesNonsense(t *testing.T) {
	g, _ := publishedGrammar(t)
	for _, tc := range []struct {
		name  string
		start string
		good  string
		bad   string
	}{
		{"a body never closed", "file",
			"concept ticket {\n  title string\n}\n",
			"concept ticket {\n  title string\n"},
		{"a body closed twice", "file",
			"concept ticket {\n  title string\n}\n",
			"concept ticket {\n  title string\n}\n}\n"},
		{"a keyword where a construct belongs", "file",
			"concept ticket {\n  title string\n}\n",
			"if ticket {\n  title string\n}\n"},
		{"a quoted name where a name belongs", "file",
			"concept ticket {\n  title string\n}\n",
			"concept \"ticket\" {\n  title string\n}\n"},
		{"a construct with no name", "file",
			"concept ticket {\n  title string\n}\n",
			"concept {\n  title string\n}\n"},
		{"a word that opens no construct", "file",
			"concept ticket {\n  title string\n}\n",
			"widget ticket {\n  title string\n}\n"},
		{"a field with no type", "file",
			"concept ticket {\n  title string\n}\n",
			"concept ticket {\n  title\n}\n"},
		{"a field whose type is a word the table does not carry", "file",
			"concept ticket {\n  title string\n}\n",
			"concept ticket {\n  title return\n}\n"},
		{"a clause no construct takes", "file",
			"query ticket openTickets {\n  filter row => row.status == \"open\"\n}\n",
			"query ticket openTickets {\n  sieve row => row.status == \"open\"\n}\n"},
		{"a clause with nothing after it", "file",
			"query ticket openTickets {\n  filter row => row.status == \"open\"\n}\n",
			"query ticket openTickets {\n  filter\n}\n"},
		{"the retired filter with no lambda header", "file",
			"query ticket openTickets {\n  filter row => row.status == \"open\"\n}\n",
			"query ticket openTickets {\n  filter row.status == \"open\"\n}\n"},
		{"the retired spec body in braces", "file",
			"spec ticket isOpen = row => row.status == \"open\"\n",
			"spec ticket isOpen = { return row.status == \"open\" }\n"},
		{"the retired `when` guard", "file",
			"query ticket openTickets {\n  filter row => args.status == nil || row.status == args.status\n}\n",
			"query ticket openTickets {\n  filter row => when(args.status) { row.status == args.status }\n}\n"},
		{"the retired seed value form", "file",
			"seed ticket firstTicket {\n  title: \"first\"\n}\n",
			"seed ticket firstTicket {\n  title = \"first\"\n}\n"},
		{"a provider param written as a map entry", "file",
			"provider chat {\n  params {\n    contextWindow 128000\n  }\n}\n",
			"provider chat {\n  params {\n    contextWindow: 128000\n  }\n}\n"},
		{"the retired `;` connective", "expression",
			"row => row.a == 1 && row.b == 2",
			"row => row.a == 1; row.b == 2"},
		{"the retired `has` operator", "expression",
			"row => \"x\" in row.tags",
			"row => row.tags has \"x\""},
		{"the retired cond()", "expression",
			"row => row.a == 1 ? \"y\" : \"n\"",
			"row => cond(row.a == 1, \"y\", \"n\")"},
		{"the retired coalesce()", "expression",
			"row => row.a ?? \"\"",
			"row => coalesce(row.a, \"\")"},
		{"the retired concat()", "expression",
			"row => row.a + row.b",
			"row => concat(row.a, row.b)"},
		{"the retired now()", "expression",
			"row => row.createdAt < now",
			"row => row.createdAt < now()"},
		{"an operator with nothing on its right", "expression",
			"row => row.a && row.b",
			"row => row.a &&"},
		{"an unbalanced parenthesis", "expression",
			"row => (row.a == 1)",
			"row => (row.a == 1"},
		{"two operators in a row", "expression",
			"row => row.a == 1",
			"row => row.a == == 1"},
		{"a method call with no receiver", "expression",
			"row => row.tags.count() > 0",
			"row => count() > 0"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if !derives(t, g, tc.start, tc.good) {
				t.Fatalf("the GOOD twin does not derive from <%s>, so this case proves nothing about the fault:\n%s",
					tc.start, tc.good)
			}
			if derives(t, g, tc.start, tc.bad) {
				t.Errorf("the published grammar DERIVES this from <%s>, though it differs from the good twin "+
					"only in the fault. A grammar that accepts nonsense constrains a decoder to nothing:\n%s",
					tc.start, tc.bad)
			}
		})
	}
}

// derives recognizes one source, failing the test when the input does not even
// lex -- a refusal by the lexer is a refusal, but not one the grammar made,
// and counting it would hide a case that had stopped testing anything.
func derives(t *testing.T, g *bnfmatch.Grammar, start, src string) bool {
	t.Helper()
	tokens, err := bnfmatch.Tokens(src)
	if err != nil {
		t.Fatalf("this input does not lex (%v), so it says nothing about the grammar:\n%s", err, src)
	}
	return bnfmatch.Match(g, start, tokens).OK
}

// unexercisedProductions are the productions no source the gate reads can
// exercise, each with the reason it cannot. The test below fails on any OTHER
// unexercised production -- that is a form the grammar publishes and the
// corpus never checks, which is exactly how `<precondition-block>` shipped
// describing statements for a body of `key: value` entries: its only example
// in the tree was a `dsl/_reference/` skeleton, which no loader and no gate
// reads.
//
// Two shapes, and the difference matters when one is added:
//
//   - LEXICAL: reached only from a production matched by the token's KIND, or
//     not reachable at token level at all. Nothing can exercise these and
//     nothing should try.
//   - SHADOWED: a sibling alternative derives the same tokens, so blanking
//     this one changes no answer. That is an ambiguity in the grammar rather
//     than a gap in the corpus -- worth knowing about, never a defect on its
//     own.
var unexercisedProductions = map[string]string{
	"string":                   "lexical: matched by the token's kind, because a string token carries its decoded value rather than its spelling",
	"character":                "lexical: reached only from <string> and <text>, over characters",
	"text":                     "lexical: reached only from <doc-comment>",
	"doc-comment":              "lexical: `///` leaves the token stream on the lexer's side channel, so no token can match it",
	"reserved-root":            "shadowed: <primary> also offers <name>, which derives `actor`, `args` and `now` as well",
	"args-field-annotation":    "shadowed: <field-annotation> unions five receivers, and <concept-field-annotation> derives the same names",
	"builtin-field-annotation": "shadowed: as args-field-annotation",
	"prompt-field-annotation":  "shadowed: as args-field-annotation",
}

// TestEveryPublishedProductionIsExercisedByTheCorpus blanks one production at
// a time and asks whether anything the gate reads stops deriving. A production
// nothing stops deriving without is a production the gate cannot check: it may
// say whatever it likes about the language and the 306 tree files and 627
// conformance sources will still pass.
//
// This is the durable form of "is any form's only example a `_reference/`
// skeleton". The walk deliberately does NOT read those skeletons -- the
// engine's own loader skips `_`-prefixed directories (core/dslfs), so holding
// the grammar to text the engine never loads would be holding it to the wrong
// thing -- and a corpus case is how every other form here is covered.
func TestEveryPublishedProductionIsExercisedByTheCorpus(t *testing.T) {
	_, block := publishedGrammar(t)
	sources := allGatedSources(t)
	base, err := bnfmatch.ParseGrammar(block)
	if err != nil {
		t.Fatalf("read the published grammar: %v", err)
	}

	names := append([]string(nil), base.Order...)
	exercised := make([]bool, len(names))
	var wg sync.WaitGroup
	next := make(chan int)
	go func() {
		for i := range names {
			next <- i
		}
		close(next)
	}()
	for w := 0; w < runtime.GOMAXPROCS(0); w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range next {
				exercised[i] = blankingBreaksSomething(t, block, names[i], sources)
			}
		}()
	}
	wg.Wait()

	for i, name := range names {
		reason, listed := unexercisedProductions[name]
		switch {
		case exercised[i] && listed:
			t.Errorf("<%s> IS exercised now, but this file still lists it as unexercisable (%q). "+
				"Delete the entry: a list of exceptions that is no longer true is worse than none.", name, reason)
		case !exercised[i] && !listed:
			t.Errorf("<%s> is published and NOTHING the gate reads exercises it: blanking it changes no "+
				"answer, so it may describe the language wrongly and both corpora still pass. Give it a "+
				"conformance case, or -- if no source can reach it -- add it to unexercisedProductions with "+
				"the reason.", name)
		}
	}
}

// blankingBreaksSomething replaces one production with a right-hand side
// nothing matches and reports whether any source stops deriving.
func blankingBreaksSomething(t *testing.T, block, name string, sources []source) bool {
	t.Helper()
	g, err := bnfmatch.ParseGrammar(blankProduction(block, name))
	if err != nil {
		t.Errorf("blanking <%s> left a grammar that does not read: %v", name, err)
		return true
	}
	for _, s := range sources {
		tokens, lexErr := bnfmatch.Tokens(s.text)
		if lexErr != nil {
			continue
		}
		if !bnfmatch.Match(g, s.start, tokens).OK {
			return true
		}
	}
	return false
}

// blankProduction rewrites one production's right-hand side, continuation
// lines included, to a reference the grammar does not define -- which derives
// nothing, wherever it is reached.
func blankProduction(block, name string) string {
	head := "<" + name + ">"
	var out []string
	inProduction := false
	for _, line := range strings.Split(block, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, head+" ") && strings.Contains(trimmed, "::="):
			inProduction = true
			out = append(out, head+" ::= <no-production-is-this>")
		case inProduction && strings.HasPrefix(trimmed, "|"):
			// a continuation of the production just blanked: drop it
		default:
			inProduction = false
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}

// allGatedSources is everything the two derivation tests read, in one slice.
func allGatedSources(t *testing.T) []source {
	t.Helper()
	var out []source
	for _, f := range embeddedTreeFiles(t) {
		raw, err := os.ReadFile(f)
		if err != nil {
			t.Fatalf("read %s: %v", f, err)
		}
		rel, _ := filepath.Rel(repoRoot, f)
		out = append(out, source{what: rel, start: "file", text: string(raw)})
	}
	return append(out, corpusSources(t)...)
}

// TestPublishedGrammarAdmitsTheOneArgumentRetiredCalls RECORDS a known,
// bounded looseness rather than leaving it to be discovered.
//
// `<predicate-name> "(" <expression> ")"` is how a spec or a trait is applied
// to its receiver -- `isActiveRecord(row)`, which nearly every shipped query
// filter writes -- and a spec's name is declared by a `.memql` file, so no
// table can list it and BNF cannot say "any name except these". The price is
// that the retired calls taking exactly ONE argument have the same tokens and
// derive too; the parser refuses each by name with its replacement.
//
// This exists because the negative pairs that pin the retired calls are all
// MULTI-argument, so the suite would otherwise read as covering a boundary it
// does not. Both halves are generated from the parser's own retired-form
// table, and the second assertion holds the grammar's published note to the
// same set -- so the page, this test and the table cannot drift apart.
func TestPublishedGrammarAdmitsTheOneArgumentRetiredCalls(t *testing.T) {
	g, block := publishedGrammar(t)
	admitted := OneArgumentRetiredCalls()
	if len(admitted) == 0 {
		t.Fatal("the parser's retired-form table names no one-argument call; either it changed shape or " +
			"splitCallSpelling stopped reading it, and this test is now vacuous")
	}
	for _, c := range admitted {
		t.Run(c.Name, func(t *testing.T) {
			src := "row => " + c.Name + "(row.a)"
			if !derives(t, g, "expression", src) {
				t.Errorf("%q no longer derives. That is a TIGHTER grammar than this test records, which is "+
					"good news -- update the note beside <call> and this test rather than reverting it.", src)
			}
			if !strings.Contains(block, c.Spelling) {
				t.Errorf("the published grammar does not name %q in its note beside <call>; a looseness "+
					"nobody is told about is the same as one nobody noticed", c.Spelling)
			}
		})
	}
	// The containment: every retired call that is NOT one argument stays
	// underivable, which is what keeps <function-name> worth closing.
	for _, f := range parser.V1RetiredForms() {
		name, args, ok := splitCallSpelling(f.Spelling)
		if !ok || (args != "" && !strings.Contains(args, ",")) {
			continue
		}
		if catalogFunctionNames()[name] {
			// `contains` is retired only as the two-argument substring test;
			// the catalog keeps the name for the graph traversal, so it
			// derives as a catalog function and is judged after its arguments.
			continue
		}
		t.Run(f.Spelling, func(t *testing.T) {
			if derives(t, g, "expression", "row => "+f.Spelling) {
				t.Errorf("`%s` derives, though it takes a number of arguments a predicate application cannot. "+
					"The one-argument form is the whole of the intended looseness.", f.Spelling)
			}
		})
	}
}

// catalogFunctionNames is the set of bare function names the catalog carries,
// which <function-name> enumerates.
func catalogFunctionNames() map[string]bool {
	out := map[string]bool{}
	for _, f := range functions.Catalog() {
		if f.Receiver == "" {
			out[f.Name] = true
		}
	}
	return out
}

// TestDocCommentIsTheOnlyTerminalTheLexerHides pins the one place where the
// published grammar describes text the parser never sees. A `///` doc comment
// leaves the stream on the lexer's side channel, so <doc-comment> matches no
// token and every use of it in the grammar is under a `*`. That is a fact
// about the language, not a defect -- but a SECOND such terminal would be a
// production nothing can ever match, and the recognizer above would report a
// file as underivable with no way for a reader to tell why.
func TestDocCommentIsTheOnlyTerminalTheLexerHides(t *testing.T) {
	g, _ := publishedGrammar(t)
	if hidden := g.InvisibleTerminals(); len(hidden) != 1 || hidden[0] != docCommentTerminal {
		t.Errorf("the terminals the lexer reads as no token at all are %q; only %q may be one.\n"+
			"Any other terminal here is written in the grammar and cannot be matched, so a production "+
			"that needs it derives nothing.", hidden, docCommentTerminal)
	}
	// The lexer REFUSES a bare quote, which is a different thing: it is a
	// character of a string, and <string> is matched against a token's kind.
	// A terminal like that outside a lexical production could never match
	// either.
	if chars := g.CharacterTerminals(); len(chars) != 1 || chars[0] != `"` {
		t.Errorf("the terminals the lexer refuses are %q; only a bare quote, in <string>, may be one", chars)
	}
}

// TestPublishedGrammarMatchesTheParsersEdition keeps this file honest about
// WHICH grammar it proved: the page names the edition and the grammar version,
// and a recognizer run against a page for another edition would pass or fail
// for reasons that have nothing to do with this tree.
func TestPublishedGrammarMatchesTheParsersEdition(t *testing.T) {
	_, block := publishedGrammar(t)
	if !strings.Contains(block, parser.Edition) {
		t.Errorf("the published grammar does not name edition %q, so nothing says which language it describes", parser.Edition)
	}
	if !strings.Contains(block, parser.GrammarVersion) {
		t.Errorf("the published grammar does not name grammar version %q", parser.GrammarVersion)
	}
}
