package main

import (
	"fmt"
	"os"

	"github.com/znasllc-io/memql/cmd/memql-lsp/internal/grammar"
)

// runGenGrammar implements `memql-lsp gen-grammar <out.json>`: generate the
// TextMate grammar from dslspec and write it to the given path. It is the
// mechanical regeneration step; the checked-in grammar is refreshed with it and
// a drift test guards that they agree.
func runGenGrammar(args []string) int {
	return writeGenerated("gen-grammar", "grammar", args, grammar.Generate)
}

// runGenLanguageConfig implements `memql-lsp gen-language-config <out.json>`:
// generate the VS Code language configuration from dslspec's punctuation table
// and write it to the given path (memql#5362). The checked-in file is
// refreshed with it, and TestLanguageConfigurationIsUpToDate guards that they
// agree.
func runGenLanguageConfig(args []string) int {
	return writeGenerated("gen-language-config", "language configuration", args, grammar.GenerateLanguageConfiguration)
}

// writeGenerated is the shared body of the generator subcommands: one output
// path, the generated bytes, and a one-line report on stderr.
func writeGenerated(subcommand, what string, args []string, generate func() ([]byte, error)) int {
	if len(args) != 1 || args[0] == "" {
		fmt.Fprintf(os.Stderr, "usage: memql-lsp %s <out.json>\n", subcommand)
		return 2
	}
	data, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: generating %s: %v\n", what, err)
		return 1
	}
	if err := os.WriteFile(args[0], data, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: writing %s: %v\n", args[0], err)
		return 1
	}
	fmt.Fprintf(os.Stderr, "SUCCESS: wrote %s (%d bytes)\n", args[0], len(data))
	return 0
}
