# Cloud Run service configuration for the Planner node.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memql-planner
  labels:
    memql-node-type: planner
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 900
      containers:
        - image: us-central1-docker.pkg.dev/fast-fire-486523-f3/memql/memql-planner:latest
          ports:
            - containerPort: 50056
              name: h2c
          env:
            - name: MEMQL_NODE_TYPE
              value: planner
            - name: MEMQL_NODE_SERVICE_ADDRESS
              value: ":50056"
            - name: MEMQL_GRPC_ADDRESS
              value: ":50051"
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
