package scorecard

import (
	"fmt"
	"sort"
	"strings"

	"github.com/znasllc-io/memql/component/proving/figure"
)

// PageHeader is the generated page's front matter. `docs/public/**` is gated
// on it (docs_front_matter_test.go), and the keys' values are from that gate's
// closed sets.
const PageHeader = `---
title: memQL Proving Scorecard
audience: public
status: stable
area: overview
sinceVersion: 0.15.0
owner: znas
---
`

// generatedMarker opens the body. A reader who lands here from a search needs
// to know within one line that editing this file is pointless.
const generatedMarker = "<!-- GENERATED by `memql-bench scorecard`. Edit the dated JSON under proving/scorecard/, not this file. -->"

// GeneratedMarker is the marker, exported so the writer's `--check` can look
// for it before overwriting a file somebody hand-authored.
const GeneratedMarker = generatedMarker

// RenderPage produces the whole page. It is a PURE function of the scorecard,
// which is what makes `--check` a diff rather than a judgement call.
//
// Everything it prints about a number goes through figure.Figure.Render, so
// there is no path by which the page shows a median without its spread.
func RenderPage(s Scorecard) string {
	var b strings.Builder
	b.WriteString(PageHeader)
	b.WriteString("\n")
	b.WriteString(generatedMarker)
	b.WriteString("\n\n# memQL Proving Scorecard\n\n")

	b.WriteString("What the platform measures about itself, and what it does not.\n" +
		"Each number is a **median with its spread and its N**, stamped with the\n" +
		"commit and date it came from. A figure that was not measured says so, in\n" +
		"its own words, rather than reporting a zero -- an absent figure and a zero\n" +
		"are different answers.\n\n")

	b.WriteString(fmt.Sprintf("- **Scorecard** `%s` at commit `%s`\n", s.Date, s.Commit))
	b.WriteString(fmt.Sprintf("- **Corpus** `%s` -- two scorecards with different corpus fingerprints measured different things and are not a trend\n", s.CorpusFingerprint))
	b.WriteString("\n")

	writeTiers(&b, s)
	writeHonestyTable(&b)
	writeFamilies(&b, s)
	writeGovernance(&b, s)
	writeMethod(&b)
	return b.String()
}

func writeTiers(b *strings.Builder, s Scorecard) {
	b.WriteString("## The two tiers\n\n")
	b.WriteString("| Tier | Armed | Last run | |\n|---|---|---|---|\n")
	for _, t := range []figure.Tier{figure.TierCI, figure.TierLive} {
		st := s.Tiers[t]
		last := st.LastRun
		if last == "" {
			last = "never"
		}
		armed := "no"
		if st.Armed {
			armed = "yes"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", t, armed, last, st.Note))
	}
	b.WriteString("\n")
}

// writeHonestyTable prints which tier can honestly answer what. It is
// GENERATED from the metric registry rather than written down, so a metric
// added to a family cannot quietly acquire a claim the table does not make.
func writeHonestyTable(b *strings.Builder) {
	b.WriteString("## What each tier can honestly measure\n\n")
	b.WriteString("A CI run replays from recorded model responses, so it is deterministic by\n" +
		"construction: pass-rate variance is trivially perfect and wall-clock belongs\n" +
		"to the runner rather than to the product. Those figures are `unmeasured` in\n" +
		"CI and stay that way until the live tier fills them.\n\n")
	b.WriteString("| Family | Metric | Blocks a merge | What it counts |\n|---|---|---|---|\n")
	for _, fam := range figure.AllFamilies() {
		for _, m := range figure.RegisteredMetrics() {
			spec, _ := figure.MetricSpec(m)
			if spec.Family != fam {
				continue
			}
			blocks := "no"
			if spec.Blocking {
				blocks = "**yes**"
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s |\n", fam, m, blocks, spec.Means))
		}
	}
	b.WriteString("\n")
}

func writeFamilies(b *strings.Builder, s Scorecard) {
	b.WriteString("## The numbers\n\n")
	byFamily := map[figure.Family][]Entry{}
	for _, e := range s.Entries {
		byFamily[e.Family] = append(byFamily[e.Family], e)
	}
	for _, fam := range figure.AllFamilies() {
		entries := byFamily[fam]
		if len(entries) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("### %s\n\n", familyTitle(fam)))
		b.WriteString("| Scenario | Metric | Arm | Figure |\n|---|---|---|---|\n")
		for _, e := range entries {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s |\n",
				e.Scenario, e.Figure.Metric, e.Arm, escapePipes(e.Figure.Render())))
		}
		b.WriteString("\n")

		// The comparison the epic asks for, printed once per family: platform
		// against baseline, and undecidable where the two are not comparable.
		writeComparisons(b, entries)
	}
}

// writeComparisons prints the platform-versus-baseline delta for every metric
// both arms measured. A metric only one arm produced is LISTED as such rather
// than omitted: a missing row reads as "no difference", which is the one thing
// it does not mean.
func writeComparisons(b *strings.Builder, entries []Entry) {
	type key struct {
		scenario string
		metric   figure.Metric
	}
	platform := map[key]figure.Figure{}
	baseline := map[key]figure.Figure{}
	var order []key
	seen := map[key]bool{}
	for _, e := range entries {
		k := key{e.Scenario, e.Figure.Metric}
		if !seen[k] {
			seen[k] = true
			order = append(order, k)
		}
		switch e.Arm {
		case figure.ArmPlatform:
			platform[k] = e.Figure
		case figure.ArmBaseline:
			baseline[k] = e.Figure
		}
	}
	var rows []string
	for _, k := range order {
		p, hasP := platform[k]
		bl, hasBL := baseline[k]
		switch {
		case hasP && hasBL:
			d := figure.Compare(bl, p)
			rows = append(rows, fmt.Sprintf("| `%s` | `%s` | %s |", k.scenario, k.metric, escapePipes(d.Render())))
		case hasP:
			rows = append(rows, fmt.Sprintf("| `%s` | `%s` | not comparable: the baseline arm produced no figure |", k.scenario, k.metric))
		case hasBL:
			rows = append(rows, fmt.Sprintf("| `%s` | `%s` | not comparable: the platform arm produced no figure |", k.scenario, k.metric))
		}
	}
	if len(rows) == 0 {
		return
	}
	b.WriteString("Platform against the bare-loop baseline:\n\n")
	b.WriteString("| Scenario | Metric | Platform vs baseline |\n|---|---|---|\n")
	b.WriteString(strings.Join(rows, "\n"))
	b.WriteString("\n\n")
}

func writeGovernance(b *strings.Builder, s Scorecard) {
	b.WriteString("## Governance\n\n")
	b.WriteString("Pass or fail, with no score. A failure here blocks a merge.\n\n")
	if len(s.Governance) == 0 {
		b.WriteString("No governance properties were asked in this run.\n\n")
		return
	}
	b.WriteString("| Property | Scenario | Result |\n|---|---|---|\n")
	for _, p := range s.Governance {
		result := "pass"
		if !p.Passed {
			result = "**FAIL** -- " + escapePipes(p.Detail)
		}
		b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n", p.Name, p.Scenario, result))
	}
	b.WriteString("\n")
}

func writeMethod(b *strings.Builder) {
	b.WriteString("## Method\n\n")
	b.WriteString("The **baseline** is the same model, the same tools and the same scenarios in\n" +
		"a plain bounded tool loop, with the platform's machinery switched off: no\n" +
		"catalog, no journal, no replay, no symptom classifier, no healing. It gets\n" +
		"the same retry allowance and the same wall-clock ceiling. What it does not\n" +
		"get is a memory of having done this before, which is the whole thesis.\n\n")
	b.WriteString("No other framework is named or measured. The comparison is the platform\n" +
		"against a model on its own, which is the only comparison this suite is\n" +
		"equipped to make fairly.\n\n")
	b.WriteString("**What a `synthetic` model id in the CI row means.** A CI run has no\n" +
		"provider, so both arms replay from a recorded tape. Where that tape holds\n" +
		"PLACEHOLDER responses, every figure above is still a fact about the plan and\n" +
		"the platform -- how many model exchanges a plan needs, how many steps a\n" +
		"resume re-executes, whether an effect duplicated -- because none of those\n" +
		"depends on the words a model said. Nothing model-dependent is published from\n" +
		"it: tokens, dollars and answer quality all read `unmeasured`, and they stay\n" +
		"that way until the live tier runs.\n\n")
	b.WriteString("Design record:\n" +
		"[the proving suite](../../superpowers/specs/2026-09-06-proving-suite-design.md).\n" +
		"The day-by-day walkthrough log is [the proving log](proving.md), which is a\n" +
		"different artifact: it records what a person exercised by hand.\n")
}

func familyTitle(f figure.Family) string {
	switch f {
	case figure.FamilyAmortizedCost:
		return "Amortized cost"
	case figure.FamilyReliability:
		return "Reliability"
	case figure.FamilyRecovery:
		return "Recovery"
	case figure.FamilyDurability:
		return "Durability"
	case figure.FamilyLearningCurve:
		return "Learning curve"
	case figure.FamilySpeed:
		return "Speed"
	case figure.FamilyGovernance:
		return "Governance"
	}
	return string(f)
}

// escapePipes keeps a rendered figure from breaking the markdown table it sits
// in. A dollar figure or an error message can carry one, and a broken table is
// how a scorecard stops being read.
func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// FamilySummary folds a scorecard into one line per family, for the CI comment
// and the OS surface. Both need "how did each family do" without the whole
// table, and two implementations of that fold would disagree.
func FamilySummary(s Scorecard) []string {
	measured := map[figure.Family]int{}
	absent := map[figure.Family]int{}
	for _, e := range s.Entries {
		if e.Figure.IsMeasured() {
			measured[e.Family]++
		} else {
			absent[e.Family]++
		}
	}
	var out []string
	for _, f := range figure.AllFamilies() {
		if measured[f]+absent[f] == 0 {
			continue
		}
		out = append(out, fmt.Sprintf("%s: %d measured, %d unmeasured", familyTitle(f), measured[f], absent[f]))
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}
