import { useEffect, useId, useRef, useState } from "react";
import { ArrowRight } from "lucide-react";

import { Button, Caption, CopyField, Fact, Facts, FormRow, Head, Notice, Panel, Subhead, type ButtonTone } from "../../kit";
import { useSession } from "../../chrome/access";
import {
  editionCaption,
  usesSummary,
  windowSentence,
  type LanguageDocsTopic,
  type LanguageFacts,
  type LanguageForm,
} from "./language";
import { useLanguage, useLanguageDocs } from "./useLanguage";

/**
 * Settings -> Language (memql#5390).
 *
 * The MemQL line this cluster speaks, the forms the language deprecates and
 * where this cluster's own DSL still spells one, and the two documents a model
 * needs to write MemQL the cluster accepts.
 *
 * THE ORDER IS THE QUESTION ORDER: what this cluster speaks, what that means
 * HERE, which forms are on their way out and by when, whether this cluster
 * still writes any and where, and finally the two copies.
 *
 * WHAT A PERSON OPENS IT TO DO decides the Head's one action (rule 1). An
 * operator checking the cluster reads the panels; somebody about to have a
 * model write a construct wants the grammar on the clipboard, and that is the
 * primary act. The vocabulary is its companion and sits in the panel that
 * explains both, so the Head never carries two primaries.
 *
 * THE COPIES READ ON CLICK. Both documents are large and most visits copy
 * neither, so nothing is fetched until somebody asks, and the answer to a click
 * is on the button itself -- its label reads Copied for two seconds -- rather
 * than a toast somewhere else on the screen.
 */
export function LanguageSection() {
  const { access } = useSession();
  const language = useLanguage();
  const readDocs = useLanguageDocs();
  const grammar = useCopy(readDocs, "grammar");
  const vocabulary = useCopy(readDocs, "vocabulary");
  const facts = language.facts;
  // An answer is on screen: the facts, or the sentence saying why there are none.
  const answered = facts !== null || language.state === "failed" || language.unreadable;

  return (
    <div className="os-settings os-app-stack">
      {/* NO META ON THE HEAD (rule 7). "MemQL 1.0, edition 2026" beside the
          title would repeat the first two facts one panel below it, and those
          facts are the one place the line is stated -- with the edition's
          status, the grammar and the editor that go with it. */}
      <Head title="Language">
        {readDocs === null ? null : <CopyButton copy={grammar} idle="Copy grammar" tone="primary" />}
      </Head>
      <CopyOutcome copy={grammar} />

      {language.state === "failed" ? (
        // The engine's sentence, verbatim: it names the capability the read
        // needs and the role that lacked it, and a paraphrase would lose both.
        <Notice
          tone="warn"
          sentence={`The cluster declined this read for ${access?.role || "your role"}.`}
          detail={language.error}
        />
      ) : language.unreadable ? (
        <Notice
          tone="warn"
          sentence="The cluster answered in a form this window does not read."
          next="Reload the window. If this is still here, the shell and the engine are from different releases."
        />
      ) : facts === null ? (
        <Caption>Loading from the cluster</Caption>
      ) : (
        <>
          <SpeaksPanel facts={facts} />
          <DeprecatedFormsPanel facts={facts} />
        </>
      )}

      {/* NOT WHILE LOADING. Drawn under the loading line, "Copy vocabulary"
          jumps the height of both fact panels when they land, out from under
          the pointer reaching for it. Held back until an answer is on screen
          above it, nothing arrives ABOVE a control once it is drawn: the Head's
          copy is the one control present from the first paint, and everything
          the read brings lands below it. A refused read still offers both
          copies, because the documents are a different read. */}
      {answered ? (
        <Panel label="For models">
          <Subhead>For models</Subhead>
          <Caption>
            Give a model the grammar and the vocabulary, and it writes MemQL this cluster accepts. Both are
            generated by this cluster at the moment you ask, so neither can disagree with what it loads. The
            engine still refuses anything that fails a load rule, and its refusal names the fix.
          </Caption>
          {readDocs === null ? null : (
            <FormRow>
              <CopyButton copy={vocabulary} idle="Copy vocabulary" tone="quiet" />
            </FormRow>
          )}
          <CopyOutcome copy={vocabulary} />
        </Panel>
      ) : null}
    </div>
  );
}

function SpeaksPanel({ facts }: { facts: LanguageFacts }) {
  return (
    <Panel label="This cluster speaks">
      <Subhead>This cluster speaks</Subhead>
      <Facts>
        <Fact label="Language" value={`MemQL ${facts.language}`} />
        <Fact label="Edition" value={`${facts.edition}, ${facts.status}`} />
        <Fact label="Grammar" value={facts.grammarVersion} mono />
        <Fact label="Editor" value={`MemQL for VS Code ${facts.editorRelease} or later`} />
      </Facts>
      {/* What the edition promises depends on its STATUS, which is read rather
          than assumed: a draft is not held to the frozen guarantee, so the page
          does not print it under one. */}
      <Caption>{editionCaption(facts)}</Caption>
    </Panel>
  );
}

/**
 * The forms, and whether this cluster's DSL still uses them.
 *
 * THE ANSWER TO "DOES MY CLUSTER USE ONE" SITS ON THE SUBHEAD LINE OR DIRECTLY
 * UNDER IT, never at the foot of the list: a count in the meta slot when there
 * are uses, and the sentence in its place when there are none. Only one of the
 * two is drawn -- usesSummary's own zero answer and the empty-state sentence
 * say the same thing, and saying it twice a line apart is the rule-7 tell.
 */
function DeprecatedFormsPanel({ facts }: { facts: LanguageFacts }) {
  const used = facts.forms.some((form) => form.uses.length > 0);
  return (
    <Panel label="Deprecated forms">
      <div className="os-head">
        <Subhead>Deprecated forms</Subhead>
        {used ? <span className="os-head-meta">{usesSummary(facts.forms)}</span> : null}
      </div>
      {facts.forms.length === 0 ? (
        <Caption>Edition {facts.edition} deprecates nothing.</Caption>
      ) : (
        <>
          {used ? null : <Caption>Nothing this cluster loads uses a deprecated form.</Caption>}
          <ul className="os-language-forms">
            {facts.forms.map((form) => (
              <DeprecatedForm key={form.rule} form={form} />
            ))}
          </ul>
        </>
      )}
    </Panel>
  );
}

/**
 * How many uses a form shows before the rest wait behind one control. A bundle
 * half way through a migration can spell a deprecated form hundreds of times,
 * and the list is the evidence, not the fix -- the migrator below it is.
 */
const USES_SHOWN = 8;

/**
 * One form, read top to bottom as the problem, its deadline, where this cluster
 * has it, and the fix. The migrator comes LAST: set directly under the window
 * sentence, the `file:line` list beneath it read as the command's output rather
 * than as the places the command would change.
 */
function DeprecatedForm({ form }: { form: LanguageForm }) {
  const [expanded, setExpanded] = useState(false);
  const extra = form.uses.length - USES_SHOWN;
  const shown = expanded ? form.uses : form.uses.slice(0, USES_SHOWN);
  return (
    <li className="os-language-form">
      {/* The spaces are text nodes, not layout: a flex container renders no
          whitespace-only run, and without them the text alternative reads as
          one word, "array(T)is now written[]T". */}
      <p className="os-language-pair">
        <code className="os-mono">{form.spelling}</code>{" "}
        <ArrowRight size={14} aria-hidden />
        <span className="os-sr-only">is now written</span>{" "}
        <code className="os-mono">{form.replacement}</code>
      </p>
      <p className="os-language-window">{windowSentence(form)}</p>
      {form.uses.length === 0 ? null : (
        <>
          <ul className="os-language-uses" aria-label={`Uses of ${form.spelling}`}>
            {shown.map((use) => (
              <li key={`${use.file}:${use.line}:${use.column}`}>
                <span className="os-mono">
                  {use.file}:{use.line}
                </span>
                {/* The concrete spelling, which the generic one cannot show. */}
                <span className="os-language-use-text os-mono">{use.text}</span>
              </li>
            ))}
          </ul>
          {/* A TOGGLE THAT STAYS. A control that removed itself when pressed
              would drop keyboard focus to the document body. Drawn in both
              states it is the same DOM node, so focus stays on the control that
              acted and aria-expanded reports what it did. */}
          {extra > 0 ? (
            <FormRow>
              <Button ariaExpanded={expanded} onClick={() => setExpanded((open) => !open)}>
                {expanded ? "Show fewer" : `Show ${extra} more`}
              </Button>
            </FormRow>
          ) : null}
        </>
      )}
      <CopyField value={form.migrator} label="command" />
    </li>
  );
}

// ---------------------------------------------------------------------------
// Copying a document the cluster serves
// ---------------------------------------------------------------------------

type CopyState =
  | { readonly phase: "idle" }
  | { readonly phase: "copying" }
  | { readonly phase: "copied" }
  /** The cluster did not send the document; its own sentence. */
  | { readonly phase: "refused"; readonly sentence: string }
  /** The document arrived and the clipboard did not take it. */
  | { readonly phase: "unreached"; readonly text: string };

interface Copy {
  readonly topic: LanguageDocsTopic;
  readonly state: CopyState;
  readonly copy: () => void;
}

/** How long a copy says Copied before the button offers the copy again. */
const COPIED_FOR_MS = 2000;

function sentenceOf(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/**
 * One copy of one document: read it, put it on the clipboard, say what
 * happened.
 *
 * THE WRITE STARTS INSIDE THE CLICK WHERE THE BROWSER ALLOWS IT. Safari keeps
 * the clipboard only for a write the gesture itself started, and the document
 * is still on its way from the cluster at that moment -- so where the platform
 * takes a promised ClipboardItem the write begins at once and the text arrives
 * when the read does. Everywhere else the write follows the read, inside the
 * activation window those browsers give a click.
 *
 * EVERY PATH SETTLES. A copy leaves Copying through `settle` and nowhere else,
 * including when the platform throws synchronously: a phase left at Copying
 * holds `inFlight` forever, and the button then ignores every later press.
 *
 * A REFUSAL IS A STANDING FACT, A CONFIRMATION IS NOT: Copied decays after two
 * seconds, while a document the clipboard would not take stays on screen,
 * selectable, until the next attempt says otherwise.
 */
function useCopy(
  read: ((topic: LanguageDocsTopic, signal: AbortSignal) => Promise<string>) | null,
  topic: LanguageDocsTopic,
): Copy {
  const [state, setState] = useState<CopyState>({ phase: "idle" });
  const decay = useRef<number | null>(null);
  const inFlight = useRef<AbortController | null>(null);

  useEffect(
    () => () => {
      if (decay.current !== null) window.clearTimeout(decay.current);
      inFlight.current?.abort();
    },
    [],
  );

  function copy(): void {
    // A second press while a read is out is the same request; it is not sent
    // twice. The button stays enabled so keyboard focus is never dropped.
    if (read === null || inFlight.current !== null) return;
    if (decay.current !== null) window.clearTimeout(decay.current);
    const controller = new AbortController();
    inFlight.current = controller;
    setState({ phase: "copying" });

    const settle = (next: CopyState): void => {
      inFlight.current = null;
      // Unmounted: there is nobody to tell, and nothing to set state on.
      if (controller.signal.aborted) return;
      setState(next);
      if (next.phase === "copied") {
        decay.current = window.setTimeout(() => setState({ phase: "idle" }), COPIED_FOR_MS);
      }
    };

    let body: Promise<string>;
    try {
      body = read(topic, controller.signal);
    } catch (err) {
      settle({ phase: "refused", sentence: sentenceOf(err) });
      return;
    }
    const started = startPromisedWrite(body);

    void (async () => {
      let text: string;
      try {
        text = await body;
      } catch (err) {
        settle({ phase: "refused", sentence: sentenceOf(err) });
        return;
      }
      settle((await putOnClipboard(text, started)) ? { phase: "copied" } : { phase: "unreached", text });
    })();
  }

  return { topic, state, copy };
}

/**
 * Start a clipboard write inside the click, with the text still on its way.
 *
 * Null when the platform takes no promised item, AND when it throws trying -- a
 * synchronous throw from `new ClipboardItem` or `clipboard.write` is a platform
 * saying no, and the copy then writes the text once it is here.
 */
function startPromisedWrite(body: Promise<string>): Promise<void> | null {
  const clipboard = globalThis.navigator?.clipboard;
  if (clipboard === undefined || typeof clipboard.write !== "function" || typeof ClipboardItem === "undefined") {
    return null;
  }
  try {
    const blob = body.then((text) => new Blob([text], { type: "text/plain" }));
    // Observed later through `body` and the returned promise; these only keep
    // an early rejection from being reported as unhandled.
    blob.catch(() => {});
    const started = clipboard.write([new ClipboardItem({ "text/plain": blob })]);
    started.catch(() => {});
    return started;
  } catch {
    return null;
  }
}

/**
 * Whether the text reached the clipboard: the write the click started, and when
 * there was none or it was refused, `writeText` with the text in hand. Never
 * throws; a false is the answer the fallback text area is for.
 */
async function putOnClipboard(text: string, started: Promise<void> | null): Promise<boolean> {
  if (started !== null) {
    try {
      await started;
      return true;
    } catch {
      // A refused promised write is not the last word: writeText may still take
      // the text, now that it has arrived.
    }
  }
  const clipboard = globalThis.navigator?.clipboard;
  if (clipboard === undefined || typeof clipboard.writeText !== "function") return false;
  try {
    await clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

const COPY_WORDS = { copying: "Copying", copied: "Copied" } as const;

/**
 * A copy button whose label answers the click.
 *
 * THE LABEL NEVER MOVES THE LINE. Every word the button can say is laid in the
 * same grid cell and only the current one is visible, so the button is always
 * as wide as its longest word: "Copy vocabulary" becoming "Copied" does not
 * pull the edge of the control out from under the pointer that pressed it. The
 * words not shown are hidden from assistive tech too, so the accessible name is
 * exactly the word on screen.
 */
function CopyButton({ copy, idle, tone }: { copy: Copy; idle: string; tone: ButtonTone }) {
  const phase = copy.state.phase;
  const shown = phase === "copying" || phase === "copied" ? COPY_WORDS[phase] : idle;
  return (
    <Button tone={tone} onClick={copy.copy}>
      <span className="os-copy-label">
        {[idle, COPY_WORDS.copying, COPY_WORDS.copied].map((word) =>
          word === shown ? (
            <span key={word}>{word}</span>
          ) : (
            <span key={word} className="os-copy-label-sizer" aria-hidden>
              {word}
            </span>
          ),
        )}
      </span>
    </Button>
  );
}

/**
 * What a copy that did not end in Copied has to say, in place, under the
 * control that produced it.
 */
function CopyOutcome({ copy }: { copy: Copy }) {
  const area = useRef<HTMLTextAreaElement | null>(null);
  const noteId = useId();
  const { state } = copy;

  // The text arrives selected and focused, so the next keystroke copies it.
  useEffect(() => {
    if (state.phase !== "unreached") return;
    area.current?.focus();
    area.current?.select();
  }, [state]);

  if (state.phase === "refused") {
    return <Notice tone="warn" sentence={`The cluster did not send the ${copy.topic}.`} detail={state.sentence} />;
  }
  if (state.phase !== "unreached") return null;
  return (
    <div className="os-language-fallback">
      <p id={noteId} className="os-caption">
        Copy did not reach the clipboard. Select the text and copy it.
      </p>
      <textarea
        ref={area}
        className="os-report"
        aria-label={copy.topic === "grammar" ? "Grammar" : "Vocabulary"}
        aria-describedby={noteId}
        readOnly
        rows={10}
        spellCheck={false}
        value={state.text}
        onFocus={(event) => event.currentTarget.select()}
      />
    </div>
  );
}
