// Code generated by cmd/frontdoorpaths. DO NOT EDIT.
// Regenerate with: make frontdoor

package frontdoor

// BFFHTTPPaths is every HTTP path the front door routes to the bff's HTTP
// edge (bff-http:8085) rather than to its gRPC h2c edge, longest-first.
//
// Generated from the same collect() that writes the Ingress path blocks in
// deploy/k8s/overlays, so the cluster's own `api.` host and every account's
// reserved `api.` host route the same set by construction. Read by the
// account front-door provisioner, which hands it to
// scripts/deploy/bind-account-front-door.sh.
//
// The catch-all "/" is deliberately ABSENT: it is the rule that reaches the
// gRPC backend, and emitting it here would shadow that backend with the
// HTTP one.
var BFFHTTPPaths = []string{
	"/.well-known/oauth-authorization-server",
	"/.well-known/memql-config.json",
	"/.well-known/jwks.json",
	"/automations/resume",
	"/auth/callback",
	"/auth/exchange",
	"/auth/landing",
	"/automations/",
	"/auth/logout",
	"/memql/query",
	"/unsubscribe",
	"/auth/login",
	"/artifacts",
	"/inbound/",
	"/memql/ws",
	"/healthz",
	"/readyz",
	"/sites/",
	"/livez",
	"/t/c/",
	"/t/o/",
}
