import { RecordList, RecordRow, Caption, Notice, Panel, Subhead } from "../../../kit";
import { trigger, type Automation, type Edge } from "./layout";
export function AutomationDetail({row, rows, select}: {row?: Automation;rows:Automation[];select:(name:string)=>void}) {
  if(!row)return <Panel label="How to read the map"><Subhead>Read the reactions</Subhead><Caption>Columns show the order automations can start each other.</Caption><Caption>Dashed edges are undecided: the load could not resolve a filter against a write.</Caption><Caption>Enclosures mark cycles. Select an automation to inspect its trigger and bounds.</Caption></Panel>;
  const incoming=rows.flatMap(a=>a.edgesOut.filter(e=>e.to===row.name).map(edge=>({name:a.name,edge})));
  const links=(items:{name:string;edge:Edge}[])=>items.length?<RecordList as="ul">{items.map(({name,edge},i)=><RecordRow key={`${name}:${i}`} name={name} secondary={`Through ${edge.concept || edge.topic || "a write"}.`} state={edge.decided ? undefined : "Undecided"} onOpen={()=>select(name)}>{edge.reason}</RecordRow>)}</RecordList>:<Caption>None.</Caption>;
  return <Panel label={`Automation ${row.name}`}><Subhead><span className="os-automation-name">{row.name}</span></Subhead>{row.origin?<Caption><code>{row.origin}</code></Caption>:null}{row.problem?<Notice tone="error" sentence="This cycle is not protected." detail={row.problem}/>:null}
    <dl className="os-automation-facts"><dt>Runs when</dt><dd>{trigger(row)}{row.triggerFilter?<pre>{row.triggerFilter}</pre>:null}</dd><dt>Stratum</dt><dd>{row.stratum}{incoming.length?`, after ${[...new Set(incoming.map(x=>x.name))].join(", ")}`:""}</dd><dt>Writes</dt><dd>{row.writes.length?row.writes.map(x=><code key={x}>{x} </code>):"None."}</dd>{row.publishes.length?<><dt>Publishes</dt><dd>{row.publishes.map(x=><code key={x}>{x} </code>)}</dd></>:null}<dt>Starts</dt><dd>{links(row.edgesOut.map(edge=>({name:edge.to,edge})))}</dd><dt>Started by</dt><dd>{links(incoming)}</dd>
    {row.opaque.length?<><dt>Calls the map cannot see</dt><dd>{row.opaque.map(x=><code key={x}>{x} </code>)}<Caption>The load cannot see what a builtin or an action writes; the run-time depth cap still stops a loop that runs through one.</Caption></dd></>:null}
    <dt>Loop</dt><dd>{row.loop?`Stops when ${row.loop.until}. At most ${row.loop.maxDepth} runs of this automation in one chain.`:"No @loop declared."}{row.cycle?<p>{row.cycle.permitted?"Permitted":"Unprotected"} cycle with {row.cycle.members.join(", ")}. Protected by {row.cycle.permittedBy.join(", ") || "no automation"}.</p>:null}</dd><dt>Mode</dt><dd>{row.mode?.kind==="single"?"Single: a fire while one runs is refused.":row.mode?.kind==="restart"?"Restart: a new fire cancels the one in flight.":row.mode?.kind==="queued"?`Queued${row.mode.max?`, up to ${row.mode.max} waiting`:" with the default queue bound"}.`:row.mode?.kind==="parallel" && row.mode.max?`Parallel: up to ${row.mode.max} runs at once. A fire at the limit is refused.`:"Parallel: every fire runs."}</dd></dl></Panel>;
}
