// Package web hosts the public-facing identity web app: login form,
// check-email page, magic-link landing page, error page, first-run
// wizard, legal markdown, and the per-user /me/* dashboard.
//
// HTML pages are produced by templ-generated components in the
// sibling component/identity/web/templ package — typed Go functions
// that emit HTML at request time. CSS, JS, SVG sprites, and the
// legal markdown are embedded via the FS variable below so the
// binary ships self-contained. There are NO external CDN references;
// the CSP enforced by csp.go is `default-src 'self'` (with a
// narrowly-scoped img-src 'self' data: for the optional brand logo).
//
// The embedded static asset pipeline:
//
//   - app.css — GENERATED by scripts/identity/build-css.sh (Tailwind v4 over
//     component/identity/web/tailwind/input.css, which imports the shared
//     brand/ layer). Gitignored; every build regenerates it.
//   - fonts/*.woff2 — the brand faces, copied next to app.css by the same
//     script so brand/fonts.css's relative ./fonts/ URLs resolve when served.
//   - favicon.svg — copied from brand/favicon.svg by the same script.
//   - app.js — small (no-framework) progressive-enhancement JS for the /me/*
//     dashboard's bearer-token bootstrap.
//   - htmx.min.js / stimulus.umd.min.js — vendored CSP-friendly builds loaded
//     globally by the layout component.
//   - heroicons.svg — small inline SVG sprite hand-built from the
//     MIT-licensed Heroicons set. Only the icons we use.
//
// # WHY app.css IS EMBEDDED BY NAME AND NOT ONLY BY THE GLOB
//
// `//go:embed static/*` is a glob, and a glob that matches nothing still
// compiles. So a build that skipped the CSS step used to SUCCEED, embed one
// file fewer, and serve /static/app.css as a 404 — every identity page
// rendering as unstyled HTML, with nothing in the build output hinting at it.
// The root Dockerfile shipped exactly that image once already; the comment
// above its build step says so.
//
// The explicit pattern below turns that into a build failure. If you see
//
//	pattern static/app.css: no matching files found
//
// the stylesheet has not been generated: run `make identity-tailwind` (or
// `make identity`, which runs it first). That is the whole fix — and it is
// deliberately a compile error, because the alternative is a silently broken
// deployment.
package web

import "embed"

// FS is the embedded asset bundle. The `static/` and `legal/`
// subtrees are readable through this FS at the relative paths they
// appear in the source tree. HTML templates are produced by the
// templ compiler at build time and live in component/identity/web/templ
// as Go source — they are NOT part of this embed.
//
//go:embed static/app.css
//go:embed static/* legal/*.md
var FS embed.FS
