// The language reference page's markup, its stylesheet and its one script.
//
// THE PAGE ANSWERS TWO QUESTIONS AND NEVER MIXES THEM UP. "What may I write?"
// is the grammar; "what does this name mean?" is the vocabulary. Both are
// GENERATED BY THE CLUSTER, so the page's first job is to say which language
// it is showing -- the edition, that edition's status, and the grammar version
// -- because a grammar with no version on it is a grammar a reader cannot tell
// from yesterday's.
//
// SEARCH RUNS IN THE PAGE, NOT IN THE HOST. A repaint assigns `webview.html`,
// which replaces the whole document and takes the focused element, the caret
// and any selection with it -- so a filter that round-tripped to the extension
// host would move the search box out from under the cursor on every keystroke.
// The renderer therefore emits EVERY item with the text it is searchable by
// (`data-search`, built by state/languageReference.ts's searchIndex) and the
// script does nothing but `includes`. The term travels to the host anyway, but
// only so a repaint for another reason can seed the box again.
//
// COPY TAKES THE WHOLE ARTIFACT, never the filtered view. Both artifacts exist
// to be handed to a model, and a model given three productions out of a
// hundred and fifty does not emit less MemQL -- it emits MemQL shaped like the
// fragment it was shown, which is worse than being given nothing.
//
// Same three constraints as every other view-kit consumer here: no DOM, no
// inline event handlers (the CSP forbids them, so interactivity is `data-act`
// attributes plus one delegated listener), and every value through
// `escapeHtml` -- which matters more here than anywhere else in the tree,
// since half the words on this page are `<production>`, `@annotation` and
// `&&`.
//
// Deliberately free of `vscode` imports (cmd/memql-lsp/vscodeimportrule_test.go).

import { escapeHtml } from "@znasllc-io/memql-view-kit";

import {
  grammarSections,
  productionCount,
  searchIndex,
  vocabularyByKind,
  type GrammarArtifact,
  type GrammarBlock,
  type LanguageIdentity,
  type VocabularyArtifact,
  type VocabularyEntry,
} from "../state/languageReference.js";

/** What the page needs to draw itself. */
export interface LanguageReferenceInput {
  /** Which language this is, and on whose authority. */
  identity: LanguageIdentity;
  /** The cluster's grammar, when one has been read. */
  grammar?: GrammarArtifact | undefined;
  /** The cluster's vocabulary, when one has been read. */
  vocabulary?: VocabularyArtifact | undefined;
  /** A read is in flight. Never left true with nothing else said -- see bodyHtml. */
  loading: boolean;
  /** A failure to report, or "". */
  error: string;
  /** The term to seed the search box with, so a repaint does not lose it. */
  search: string;
  /**
   * Whether this window can offer to pick a cluster.
   *
   * False in an untrusted workspace, where the runtime surface is never
   * registered and `memql.clusters.select` would fail with "command not
   * found". A button that cannot work is worse than no button, so the page
   * says what is missing instead.
   */
  offerSelectCluster: boolean;
}

/** The message the page posts when a copy button is pressed. */
export const COPY_GRAMMAR = "copyGrammar";
/** The message the page posts when the vocabulary copy button is pressed. */
export const COPY_VOCABULARY = "copyVocabulary";
/** The message the page posts as the search term changes. */
export const SEARCH_MESSAGE = "search";
/** The message the page posts from its "Select Cluster" button. */
export const SELECT_CLUSTER = "selectCluster";

export function renderLanguageReferencePage(input: LanguageReferenceInput): string {
  return `<h1>MemQL language reference</h1>
<p class="lede">What a MemQL cluster accepts, generated by the cluster from its own parser: the grammar says what may be written, the vocabulary says what each written thing means.</p>
${identityHtml(input.identity)}
${errorHtml(input.error)}
${retryHtml(input)}
${bodyHtml(input)}`;
}

/**
 * The header fact block: which language, and where the facts came from.
 *
 * THE STATUS IS PRINTED ONLY WHEN THERE IS ONE, and its note is printed
 * either way. An edition whose status this extension cannot state gets the
 * sentence saying so rather than a blank row, because a missing status and a
 * draft edition look identical as an absence.
 */
function identityHtml(identity: LanguageIdentity): string {
  const status =
    identity.status === ""
      ? `<span class="lr-unstated">not stated</span>`
      : `<span class="badge ok">${escapeHtml(identity.status)}</span>`;
  const rows: string[] = [
    fact("edition", identity.edition === "" ? "not stated" : identity.edition, ""),
    fact("status", "", `${status} <span class="lr-note">${escapeHtml(identity.statusNote)}</span>`),
    fact(
      "grammar version",
      identity.grammarVersion === "" ? "not stated" : identity.grammarVersion,
      "",
    ),
    fact("source", "", `<span class="lr-note">${escapeHtml(identity.origin)}</span>`),
  ];
  return `<div class="panel-box lr-identity">${rows.join("")}</div>`;
}

/** One `key  value` row. `html` wins over `value` when it is not empty. */
function fact(key: string, value: string, html: string): string {
  const body = html === "" ? `<span class="fact-value data">${escapeHtml(value)}</span>` : html;
  return `<div class="fact"><span class="fact-key">${escapeHtml(key)}</span>${body}</div>`;
}

function errorHtml(error: string): string {
  if (error === "") return "";
  return `<p class="lr-error">${escapeHtml(error)}</p>`;
}

/**
 * The way back from a read that did not work.
 *
 * Offered ONLY when there is a cluster and something is missing: a dropped
 * socket and a mid-upgrade node both produce a failure the next attempt
 * succeeds at, and without this the only retry is closing the tab and running
 * the command again. Drawn once, however many of the two calls failed -- two
 * buttons for one action is a choice a reader has to make and cannot.
 */
function retryHtml(input: LanguageReferenceInput): string {
  if (input.identity.source !== "cluster" || input.loading) return "";
  if (input.error === "" && (input.grammar !== undefined || input.vocabulary !== undefined)) {
    return "";
  }
  return `<div class="actions"><button class="secondary" type="button" data-act="reload">Try again</button></div>`;
}

/**
 * The two artifacts, or the honest account of why they are not here.
 *
 * FOUR STATES, and every one of them says something. Nothing on this page is
 * allowed to be an empty pane or a spinner that never ends: the reader came
 * here to find out what their cluster accepts, and "I could not ask" is an
 * answer to that while a blank rectangle is not.
 */
function bodyHtml(input: LanguageReferenceInput): string {
  const { grammar, vocabulary } = input;
  if (grammar !== undefined || vocabulary !== undefined) {
    return `${controlsHtml(input.search)}
${grammarHtml(grammar)}
${vocabularyHtml(vocabulary)}`;
  }
  if (input.identity.source === "extension") return notConnectedHtml(input);
  if (input.loading) {
    return `<p class="lr-pending">Reading the grammar and the vocabulary from ${escapeHtml(
      input.identity.cluster,
    )}...</p>`;
  }
  return `<h2>Grammar and vocabulary</h2>
<p class="lr-pending">${escapeHtml(
    `${input.identity.cluster} answered with neither artifact. Both are served by the memqlGrammar() and memqlVocabulary() builtins; a cluster that has them will answer, and one too old to have them refuses the call by name.`,
  )}</p>`;
}

/**
 * The state with no cluster: say so plainly, and show what the extension does
 * know.
 *
 * WHAT IT KNOWS IS NOT NOTHING. The extension ships its own language server,
 * so the completion, the diagnostics and the highlighting in the editor behind
 * this panel ARE a language -- the one named in the block above. Saying which
 * one, and that the two artifacts live on a cluster, is the whole answer; an
 * empty panel would leave a reader to guess that the feature is broken.
 */
function notConnectedHtml(input: LanguageReferenceInput): string {
  const select = input.offerSelectCluster
    ? `<div class="actions"><button class="primary" type="button" data-act="${SELECT_CLUSTER}">Select Cluster</button></div>`
    : `<p class="lr-note">${escapeHtml(
        "This window is not trusted, so there is no cluster connection to use. Trust the workspace to connect to one.",
      )}</p>`;
  return `<h2>Grammar and vocabulary</h2>
<p>${escapeHtml(
    "No cluster is connected, so there is no grammar and no vocabulary to show: a cluster generates both from its own parser at the moment it is asked, which is what makes them describe the language it actually reads rather than the language a committed page described when it was last written.",
  )}</p>
<p>${escapeHtml(
    "What this extension knows on its own is above. Its language server ships with the extension, so the completion, diagnostics and highlighting you are getting in the editor are that edition and that grammar version -- whatever a cluster you later connect to turns out to speak.",
  )}</p>
${select}`;
}

/** The search box and the two copy buttons, kept together above both artifacts. */
function controlsHtml(search: string): string {
  return `<div class="lr-controls">
  <label class="lr-search-label" for="lr-search">Search</label>
  <input id="lr-search" class="lr-search" type="search" autocomplete="off" spellcheck="false"
         placeholder="a name, a production, a word in a description"
         value="${escapeHtml(search)}">
  <div class="lr-actions">
    <button class="secondary" type="button" data-act="${COPY_GRAMMAR}">Copy grammar</button>
    <button class="secondary" type="button" data-act="${COPY_VOCABULARY}">Copy vocabulary</button>
  </div>
  <p class="lr-note lr-controls-note">${escapeHtml(
    "Search filters both artifacts below. Copy takes the whole artifact, not what the search leaves showing -- both exist to be handed to a model, and a model given part of a grammar writes MemQL shaped like the part it was shown.",
  )}</p>
</div>`;
}

/** The grammar pane: the cluster's own sections, its own productions. */
function grammarHtml(grammar: GrammarArtifact | undefined): string {
  if (grammar === undefined) {
    return `<h2>Grammar</h2>
<p class="lr-pending">${escapeHtml(
      "This cluster did not answer with a grammar. The vocabulary below is what it did answer.",
    )}</p>`;
  }
  const sections = grammarSections(grammar.content);
  const total = productionCount(sections);
  const format = grammar.format === "" ? "" : ` <span class="badge">${escapeHtml(grammar.format)}</span>`;
  const groups = sections
    .map(
      (section) => `<section class="lr-group" data-group>
${section.title === "" ? "" : `<h3 class="lr-group-head">${escapeHtml(section.title)}</h3>\n`}${section.blocks
        .map(blockHtml)
        .join("\n")}
</section>`,
    )
    .join("\n");
  // The heading lives INSIDE the scope, with its counter: the script rewrites
  // the counter for whatever its own scope is showing, and a counter outside
  // would be a number about a list it cannot see.
  return `<div class="lr-scope" data-scope="grammar">
<h2>Grammar${format} ${count(total, "productions")}</h2>
${groups}
${empty(
  "Nothing in the grammar matches",
  "A term is matched against a production's name and every line of its right-hand side.",
)}
</div>`;
}

/** One production (or one of the cluster's own comments) as searchable text. */
function blockHtml(block: GrammarBlock): string {
  const text = block.lines.join("\n");
  const index = searchIndex([block.name, text]);
  return `<pre class="lr-production" data-search="${escapeHtml(index)}">${escapeHtml(text)}</pre>`;
}

/** The vocabulary pane, grouped by the kinds the cluster named. */
function vocabularyHtml(vocabulary: VocabularyArtifact | undefined): string {
  if (vocabulary === undefined) {
    return `<h2>Vocabulary</h2>
<p class="lr-pending">${escapeHtml(
      "This cluster did not answer with a vocabulary. The grammar above is what it did answer.",
    )}</p>`;
  }
  const groups = vocabularyByKind(vocabulary)
    .map(
      (group) => `<section class="lr-group" data-group>
<h3 class="lr-group-head">${escapeHtml(group.kind)} <span class="lr-group-count" data-group-count data-total="${
        group.entries.length
      }">${group.entries.length}</span></h3>
${group.entries.map(entryHtml).join("\n")}
</section>`,
    )
    .join("\n");
  return `<div class="lr-scope" data-scope="vocabulary">
<h2>Vocabulary ${count(vocabulary.entries.length, "entries")}</h2>
${groups}
${empty(
  "Nothing in the vocabulary matches",
  "A term is matched against an entry's name, how it is written, what it means, and its kind.",
)}
</div>`;
}

/** One vocabulary entry: the name, how it is written, what it means. */
function entryHtml(entry: VocabularyEntry): string {
  const index = searchIndex([entry.name, entry.signature, entry.description, entry.kind]);
  const tier = entry.tier === "" ? "" : `<span class="badge lr-tier">${escapeHtml(tierLabel(entry.tier))}</span>`;
  const signature =
    entry.signature === ""
      ? ""
      : `<code class="lr-signature data">${escapeHtml(entry.signature)}</code>`;
  const description =
    entry.description === ""
      ? `<p class="lr-desc lr-unstated">This cluster carries no description for it.</p>`
      : `<p class="lr-desc">${escapeHtml(entry.description)}</p>`;
  return `<div class="lr-entry" data-search="${escapeHtml(index)}">
<div class="lr-entry-head"><code class="lr-name data">${escapeHtml(
    entry.name,
  )}</code>${signature}${tier}</div>
${description}
</div>`;
}

/**
 * A catalog function's tier, with the letter kept.
 *
 * The letter is what the cluster sent and what the docs elsewhere use, so it
 * stays; the words after it are the meaning the vocabulary's own field
 * documents ("P" when the call lowers to SQL, "M" when it runs in process). An
 * unrecognised letter is shown bare rather than guessed at.
 */
function tierLabel(tier: string): string {
  if (tier === "P") return "P -- lowers to SQL";
  if (tier === "M") return "M -- runs in process";
  return tier;
}

/** The "n items" counter the script rewrites to "n of m items" while filtering. */
function count(total: number, noun: string): string {
  return `<span class="lr-count" data-count data-total="${total}" data-noun="${escapeHtml(
    noun,
  )}">${total} ${escapeHtml(noun)}</span>`;
}

/**
 * The no-match line, pre-rendered hidden.
 *
 * The TERM is filled in by the script through `textContent`, never by building
 * markup in the page: the one string on this surface that this module cannot
 * escape is the one a reader typed, and textContent cannot carry markup at
 * all.
 *
 * It says what a term IS matched against, which is the thing a reader who got
 * no hits actually needs -- "no results" alone leaves them unable to tell a
 * misspelling from a search that was never going to look where they meant.
 */
function empty(lead: string, searchable: string): string {
  return `<p class="lr-empty" data-empty hidden>${escapeHtml(lead)} <span class="data" data-term></span>. ${escapeHtml(
    searchable,
  )}</p>`;
}

/**
 * The page's stylesheet.
 *
 * ONE COLUMN, and narrow-first: this panel opens beside a file, so the common
 * width is a side pane rather than a full editor. Every colour is a
 * `--memql-*` token, so the page follows the appearance setting and defers
 * wholesale to VS Code under either high-contrast theme (see brandTokens.ts).
 */
export function languageReferenceStyles(): string {
  return `
  body { max-width: 860px; }
  h2 { display: flex; align-items: baseline; flex-wrap: wrap; gap: 8px;
       border-top: 1px solid var(--memql-border); padding-top: 14px; margin-top: 22px; }
  /* Not uppercased: a section title is the cluster's own banner text, and one
     of them is two full sentences ("The precedence ladder, loosest binding
     first. Level numbers are the operator table's..."). Weight and colour
     carry the level instead. */
  h3 { font-size: 0.94em; font-weight: 600; margin: 16px 0 6px;
       color: var(--memql-muted); }

  .lr-identity { margin-bottom: 14px; }
  .fact { display: flex; gap: 8px; align-items: baseline; padding: 2px 0; flex-wrap: wrap; }
  .fact-key { flex: 0 0 8.5em; color: var(--memql-muted); }
  .fact-value { min-width: 0; overflow-wrap: anywhere; }
  .lr-note { color: var(--memql-muted); min-width: 0; overflow-wrap: anywhere; }
  /* A note in a fact row SHRINKS beside its key rather than dropping to a line
     of its own, which would leave the key looking like a value that is
     missing. At a narrow width it still wraps, which is what a sentence
     should do. */
  .fact .lr-note { flex: 1 1 14em; }
  .lr-unstated { color: var(--memql-subtle); }
  .lr-error { color: var(--memql-danger); overflow-wrap: anywhere; }
  .lr-pending { color: var(--memql-muted); }

  /* The controls STAY PUT while the lists underneath them change: filtering
     must never move the box out from under the cursor that is typing in it. */
  /* The negative margins take the bar out to the body's own 16px/20px padding
     so the sticky background covers the full width; without them, content
     scrolling past shows through the gutters. */
  .lr-controls { position: sticky; top: 0; z-index: 1; background: var(--memql-bg);
                 border-bottom: 1px solid var(--memql-border);
                 padding: 10px 20px 8px; margin: 14px -20px 0;
                 display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }
  .lr-search-label { color: var(--memql-muted); }
  .lr-search { flex: 1 1 14em; min-width: 0; font: inherit; border-radius: 3px;
               padding: 4px 8px; color: var(--memql-fg);
               background: var(--memql-surface);
               border: 1px solid var(--memql-border-strong); }
  .lr-search:focus-visible { outline: 2px solid var(--memql-accent); outline-offset: 1px; }
  .lr-actions { display: flex; gap: 8px; flex-wrap: wrap; }
  .lr-controls-note { flex: 1 1 100%; margin: 0; font-size: 0.92em; }

  .lr-count { color: var(--memql-muted); font-size: 0.86em; font-weight: 400; }
  .lr-group-count { color: var(--memql-subtle); }
  .lr-group[hidden] { display: none; }

  /* A tinted block per production, with no border: at 126 of them an outline
     each is a page made of boxes. The tint is still what separates one
     production from the WRAPPED continuation lines of the one above it, which
     is the thing a reader actually needs kept apart. */
  .lr-production { font-family: var(--vscode-editor-font-family, ui-monospace, monospace);
                   font-size: 0.92em; margin: 0 0 4px; padding: 5px 8px;
                   background: var(--memql-raised); border-radius: 4px;
                   white-space: pre-wrap; overflow-wrap: anywhere; }

  .lr-entry { padding: 6px 0; border-bottom: 1px solid var(--memql-border); }
  .lr-entry:last-child { border-bottom: none; }
  .lr-entry-head { display: flex; flex-wrap: wrap; align-items: baseline; gap: 8px; }
  .lr-name { font-weight: 700; color: var(--memql-fg); }
  .lr-signature { color: var(--memql-data-string); min-width: 0; overflow-wrap: anywhere; }
  .lr-tier { font-size: 0.8em; }
  .lr-desc { margin: 3px 0 0; color: var(--memql-muted); overflow-wrap: anywhere; }
  .lr-empty { color: var(--memql-muted); }
`;
}

/**
 * The page's script body, without its `<script>` tag -- the panel owns the
 * document and the nonce.
 *
 * The ONLY decision in here is `index.includes(term)`. Which text an item is
 * searchable by is decided in state/languageReference.ts and arrives as
 * `data-search`; what a no-match says is decided above and arrives as markup.
 * That split is what makes the search testable at all, since nothing in this
 * package runs a DOM.
 */
export function languageReferenceScript(): string {
  return `
  const vscode = acquireVsCodeApi();
  const search = document.getElementById('lr-search');

  document.addEventListener('click', (e) => {
    const act = e.target.closest('[data-act]');
    if (act) vscode.postMessage({ type: act.dataset.act });
  });

  function applyFilter() {
    const term = search === null ? '' : search.value.trim().toLowerCase();
    for (const scope of document.querySelectorAll('[data-scope]')) {
      let shown = 0;
      for (const item of scope.querySelectorAll('[data-search]')) {
        const hit = term === '' || item.dataset.search.includes(term);
        item.hidden = !hit;
        if (hit) shown += 1;
      }
      for (const group of scope.querySelectorAll('[data-group]')) {
        const visible = group.querySelectorAll('[data-search]:not([hidden])').length;
        group.hidden = visible === 0;
        // A group's own count follows the filter too. Left at its total it
        // would sit beside one visible entry reading "22", which a reader
        // takes for the number of matches.
        const groupCount = group.querySelector('[data-group-count]');
        if (groupCount) {
          const groupTotal = groupCount.dataset.total;
          groupCount.textContent = term === '' ? groupTotal : visible + ' of ' + groupTotal;
        }
      }
      const counter = scope.querySelector('[data-count]');
      if (counter) {
        const total = counter.dataset.total;
        const noun = counter.dataset.noun;
        counter.textContent = term === '' ? total + ' ' + noun : shown + ' of ' + total + ' ' + noun;
      }
      const none = scope.querySelector('[data-empty]');
      if (none) {
        none.hidden = shown !== 0;
        const termEl = none.querySelector('[data-term]');
        if (termEl) termEl.textContent = search === null ? '' : search.value.trim();
      }
    }
  }

  if (search !== null) {
    search.addEventListener('input', () => {
      applyFilter();
      // The host keeps the term only so a repaint -- a theme flip, a
      // reconnect -- can put it back. It never re-renders because of it.
      vscode.postMessage({ type: '${SEARCH_MESSAGE}', term: search.value });
    });
    applyFilter();
  }
`;
}
