// Package abuse implements the anti-abuse middleware stack for the
// identity service. It hosts the per-IP rate limiter, Cloudflare
// Turnstile verifier, disposable-email blocklist, MX-record validator,
// weighted risk scorer, and the HTTP middleware that wires them in
// front of POST /auth/magic-link.
//
// The package is import-light by design — it depends on the parent
// component/identity package (for Config + AuditLogger) and the
// standard library, nothing else. Phase 6 may extend it with admin-UI
// hooks that read the rate-limiter state, but the core defenses stay
// in here.
package abuse

import "strings"

// disposableDomains is an embedded snapshot of well-known
// disposable / throwaway email-domain providers. Source: a curated
// subset of the popular `disposable-email-domains` GitHub project's
// blocklist:
//
//	https://github.com/disposable-email-domains/disposable-email-domains/blob/master/disposable_email_blocklist.conf
//
// This list is a starter set (~200 entries) covering the providers we
// see most often in dev / staging. Future work refreshes it from the
// upstream feed via a code-generator that fetches the latest .conf
// file and regenerates this map. Until that lands, the list is
// hand-maintained — extend it cautiously and prefer false-negatives
// over false-positives so legitimate users on niche-but-real domains
// aren't bounced.
var disposableDomains = map[string]struct{}{
	// Mailinator family.
	"mailinator.com":     {},
	"mailinator.net":     {},
	"mailinator2.com":    {},
	"binkmail.com":       {},
	"bobmail.info":       {},
	"chammy.info":        {},
	"devnullmail.com":    {},
	"letthemeatspam.com": {},
	"mailinater.com":     {},
	"mailinator.org":     {},
	"notmailinator.com":  {},
	"reallymymail.com":   {},
	"reconmail.com":      {},
	"safetymail.info":    {},
	"safetypost.de":      {},
	"sogetthis.com":      {},
	"spambooger.com":     {},
	"spamherelots.com":   {},
	"streetwisemail.com": {},
	"suremail.info":      {},
	"thisisnotmyrealemail.com": {},
	"tradermail.info":    {},
	"veryrealemail.com":  {},
	"zippymail.info":     {},

	// 10minutemail / temp-window family.
	"10minutemail.com":   {},
	"10minutemail.net":   {},
	"10minutemail.us":    {},
	"10minutemail.de":    {},
	"10minutemail.co.uk": {},
	"20minutemail.com":   {},
	"30minutemail.com":   {},
	"60minutemail.com":   {},
	"33mail.com":         {},
	"5minutemail.com":    {},
	"15minutemail.com":   {},

	// Guerrilla mail family.
	"guerrillamail.com":  {},
	"guerrillamail.net":  {},
	"guerrillamail.org":  {},
	"guerrillamail.biz":  {},
	"guerrillamail.de":   {},
	"guerrillamailblock.com": {},
	"sharklasers.com":    {},
	"grr.la":             {},
	"spam4.me":           {},
	"pokemail.net":       {},

	// Generic temp-mail providers.
	"tempmail.com":       {},
	"temp-mail.org":      {},
	"temp-mail.io":       {},
	"temp-mail.ru":       {},
	"tempmailaddress.com": {},
	"tempmail.net":       {},
	"tempmailo.com":      {},
	"tempmail.us.com":    {},
	"tempmail.email":     {},
	"tempmailbox.com":    {},
	"temp-mailbox.com":   {},
	"tempinbox.com":      {},
	"throwawaymail.com":  {},
	"throwam.com":        {},
	"throwaway.email":    {},
	"discard.email":      {},
	"discardmail.com":    {},
	"discardmail.de":     {},
	"dispostable.com":    {},
	"disposemail.com":    {},
	"trashmail.com":      {},
	"trashmail.de":       {},
	"trashmail.net":      {},
	"trashmail.org":      {},
	"trashmail.ws":       {},
	"trash-mail.com":     {},
	"trash-mail.de":      {},
	"trashymail.com":     {},
	"mytrashmail.com":    {},
	"wegwerfemail.de":    {},
	"wegwerfmail.de":     {},
	"wegwerfmail.net":    {},
	"wegwerfmail.org":    {},

	// Yopmail family.
	"yopmail.com":        {},
	"yopmail.net":        {},
	"yopmail.fr":         {},
	"cool.fr.nf":         {},
	"jetable.fr.nf":      {},
	"nospam.ze.tc":       {},
	"speed.1s.fr":        {},
	"courriel.fr.nf":     {},
	"moncourrier.fr.nf":  {},
	"monemail.fr.nf":     {},
	"monmail.fr.nf":      {},

	// Maildrop family.
	"maildrop.cc":        {},
	"maildrop.cf":        {},
	"maildrop.ga":        {},
	"maildrop.gq":        {},
	"maildrop.ml":        {},
	"maildrop.tk":        {},

	// FakeMail / FakeInbox.
	"fakeinbox.com":      {},
	"fakemail.fr":        {},
	"fakemailgenerator.com": {},
	"fake-mail.ml":       {},
	"fake-email.com":     {},

	// Generic disposable / privacy.
	"anonbox.net":        {},
	"anonmails.de":       {},
	"anonymail.dk":       {},
	"anonymbox.com":      {},
	"armyspy.com":        {},
	"blackmarket.to":     {},
	"buyusedlibrarybooks.org": {},
	"byom.de":            {},
	"cek.pm":             {},
	"chacuo.net":         {},
	"clrmail.com":        {},
	"correo.blogos.net":  {},
	"crapmail.org":       {},
	"cuvox.de":           {},
	"dacoolest.com":      {},
	"dandikmail.com":     {},
	"dayrep.com":         {},
	"deadaddress.com":    {},
	"deadspam.com":       {},
	"despam.it":          {},
	"despammed.com":      {},
	"dfgh.net":           {},
	"digitalsanctuary.com": {},
	"disposableaddress.com": {},
	"disposableemailaddresses.com": {},
	"disposableinbox.com": {},
	"dodgeit.com":        {},
	"dodgit.com":         {},
	"donemail.ru":        {},
	"dontreg.com":        {},
	"dontsendmespam.de":  {},
	"drdrb.net":          {},
	"dump-email.info":    {},
	"dumpyemail.com":     {},
	"e4ward.com":         {},
	"easytrashmail.com":  {},
	"einrot.com":         {},
	"einmalmail.de":      {},
	"emailgo.de":         {},
	"emailias.com":       {},
	"emailinfive.com":    {},
	"emailmiser.com":     {},
	"emailsensei.com":    {},
	"emailtemporanea.com": {},
	"emailtemporanea.net": {},
	"emailtemporario.com.br": {},
	"emailthe.net":       {},
	"emailtmp.com":       {},
	"emailwarden.com":    {},
	"emailx.at.hm":       {},
	"emailxfer.com":      {},
	"emkei.cz":           {},
	"explodemail.com":    {},
	"fastacura.com":      {},
	"fastchevy.com":      {},
	"fastchrysler.com":   {},
	"fastkawasaki.com":   {},
	"fastmazda.com":      {},
	"fastmitsubishi.com": {},
	"fastnissan.com":     {},
	"fastsubaru.com":     {},
	"fastsuzuki.com":     {},
	"fasttoyota.com":     {},
	"fastyamaha.com":     {},
	"filzmail.com":       {},
	"fizmail.com":        {},
	"fleckens.hu":        {},
	"frapmail.com":       {},
	"front14.org":        {},
	"fux0ringduh.com":    {},
	"garliclife.com":     {},
	"get1mail.com":       {},
	"getairmail.com":     {},
	"getonemail.com":     {},
	"getonemail.net":     {},
	"giantmail.de":       {},
	"girlsundertheinfluence.com": {},
	"gishpuppy.com":      {},
	"goemailgo.com":      {},
	"gotmail.com":        {},
	"gotmail.net":        {},
	"gotmail.org":        {},
	"gotti.otherinbox.com": {},
	"great-host.in":      {},
	"greensloth.com":     {},
	"gsrv.co.uk":         {},
	"guerillamail.biz":   {},
	"guerillamail.com":   {},
	"guerillamail.net":   {},
	"guerillamail.org":   {},
	"h.mintemail.com":    {},
	"haltospam.com":      {},
	"hidemail.de":        {},
	"hidzz.com":          {},
	"hmamail.com":        {},
	"hochsitze.com":      {},
	"hopemail.biz":       {},
	"hulapla.de":         {},
	"icx.in":             {},
	"icx.li":             {},
	"ieatspam.eu":        {},
	"ieatspam.info":      {},
	"ieh-mail.de":        {},
	"ikbenspamvrij.nl":   {},
	"imails.info":        {},
	"inbax.tk":           {},
	"inbox.si":           {},
	"inboxalias.com":     {},
	"inboxclean.com":     {},
	"inboxclean.org":     {},
	"infocom.zp.ua":      {},
	"instant-mail.de":    {},
	"ip6.li":             {},
	"irish2me.com":       {},
	"iwi.net":            {},
	"jetable.com":        {},
	"jetable.net":        {},
	"jetable.org":        {},
	"jnxjn.com":          {},
	"junk1e.com":         {},
	"kasmail.com":        {},
	"kaspop.com":         {},
	"keepmymail.com":     {},
	"killmail.com":       {},
	"killmail.net":       {},
	"klassmaster.com":    {},
	"klzlk.com":          {},
	"kook.ml":            {},
	"koszmail.pl":        {},
	"kurzepost.de":       {},
	"lawlita.com":        {},
	"lhsdv.com":          {},
	"lifebyfood.com":     {},
	"link2mail.net":      {},
	"litedrop.com":       {},
	"loadby.us":          {},
	"login-email.ga":     {},
	"lol.ovpn.to":        {},
	"lookugly.com":       {},
	"lortemail.dk":       {},
	"lr78.com":           {},
	"lroid.com":          {},
	"lukop.dk":           {},
	"m21.cc":             {},
	"mail-filter.com":    {},
	"mail-temporaire.fr": {},
	"mail.by":            {},
	"mail.mezimages.net": {},
	"mail.zp.ua":         {},
	"mail1a.de":          {},
	"mail21.cc":          {},
	"mail2rss.org":       {},
	"mail333.com":        {},
	"mail4trash.com":     {},
	"mailbidon.com":      {},
	"mailbiz.biz":        {},
	"mailblocks.com":     {},
	"mailbucket.org":     {},
	"mailcatch.com":      {},
	"mailde.de":          {},
	"mailde.info":        {},
	"maildx.com":         {},
	"maileater.com":      {},
	"mailed.in":          {},
	"mailexpire.com":     {},
	"mailfa.tk":          {},
	"mailforspam.com":    {},
	"mailfreeonline.com": {},
	"mailguard.me":       {},
	"mailhazard.com":     {},
	"mailhz.me":          {},
	"mailimate.com":      {},
	"mailin8r.com":       {},
	"mailinblack.com":    {},
	"mailincubator.com":  {},
	"mailismagic.com":    {},
	"mailme.lv":          {},
	"mailme24.com":       {},
	"mailmetrash.com":    {},
	"mailmoat.com":       {},
	"mailnator.com":      {},
	"mailnesia.com":      {},
	"mailnull.com":       {},
	"mailorg.org":        {},
	"mailpick.biz":       {},
	"mailrock.biz":       {},
	"mailscrap.com":      {},
	"mailshell.com":      {},
	"mailsiphon.com":     {},
	"mailtemp.info":      {},
	"mailtome.de":        {},
	"mailtothis.com":     {},
	"mailtrash.net":      {},
	"mailtv.net":         {},
	"mailtv.tv":          {},
	"mailzilla.com":      {},
	"mailzilla.org":      {},
	"makemetheking.com":  {},
	"manybrain.com":      {},
	"mbx.cc":             {},
	"mega.zik.dj":        {},
	"meinspamschutz.de":  {},
	"meltmail.com":       {},
	"messagebeamer.de":   {},
	"mezimages.net":      {},
	"mintemail.com":      {},
	"misterpinball.de":   {},
	"msa.minsmail.com":   {},
	"mt2009.com":         {},
	"mt2014.com":         {},
	"mycard.net.ua":      {},
	"mycleaninbox.net":   {},
	"mymail-in.net":      {},
	"mymailoasis.com":    {},
	"mynetstore.de":      {},
	"mypartyclip.de":     {},
	"myphantomemail.com": {},
	"mysamp.de":          {},
	"mytempemail.com":    {},
	"mytempmail.com":     {},
	"nepwk.com":          {},
	"nervmich.net":       {},
	"nervtmich.net":      {},
	"netmails.com":       {},
	"netmails.net":       {},
	"netzidiot.de":       {},
	"neverbox.com":       {},
	"nice-4u.com":        {},
	"nincsmail.com":      {},
	"nincsmail.hu":       {},
	"nnh.com":            {},
	"no-spam.ws":         {},
	"noblepioneer.com":   {},
	"nomail.pw":          {},
	"nomail.xl.cx":       {},
	"nomail2me.com":      {},
	"nospam4.us":         {},
	"nospamfor.us":       {},
	"nospammail.net":     {},
	"notsharingmy.info":  {},
	"nowmymail.com":      {},
	"objectmail.com":     {},
	"obobbo.com":         {},
	"odnorazovoe.ru":     {},
	"oneoffemail.com":    {},
	"onewaymail.com":     {},
	"online.ms":          {},
	"oopi.org":           {},
	"ordinaryamerican.net": {},
	"otherinbox.com":     {},
	"ovpn.to":            {},
	"owlpic.com":         {},
	"pancakemail.com":    {},
	"pimpedupmyspace.com": {},
	"pjjkp.com":          {},
	"plexolan.de":        {},
	"poofy.org":          {},
	"pookmail.com":       {},
	"privacy.net":        {},
	"privatdemail.net":   {},
	"proxymail.eu":       {},
	"prtnx.com":          {},
	"putthisinyourspamdatabase.com": {},
	"putzmich.com":       {},
	"quickinbox.com":     {},
	"rcpt.at":            {},
	"recode.me":          {},
	"recursor.net":       {},
	"regbypass.com":      {},
	"regbypass.comsafe-mail.net": {},
	"rejectmail.com":     {},
	"rmqkr.net":          {},
	"rppkn.com":          {},
	"rtrtr.com":          {},
	"s0ny.net":           {},
	"safe-mail.net":      {},
	"safersignup.de":     {},
	"sandelf.de":         {},
	"saynotospams.com":   {},
	"schafmail.de":       {},
	"selfdestructingmail.com": {},
	"sendspamhere.com":   {},
	"shieldedmail.com":   {},
	"shiftmail.com":      {},
	"shitmail.me":        {},
	"shitware.nl":        {},
	"shortmail.net":      {},
	"sibmail.com":        {},
	"sinnlos-mail.de":    {},
	"slapsfromlastnight.com": {},
	"slaskpost.se":       {},
	"smashmail.de":       {},
	"smellfear.com":      {},
	"snakemail.com":      {},
	"sneakemail.com":     {},
	"sofort-mail.de":     {},
	"soodonims.com":      {},
	"spam.la":            {},
	"spamavert.com":      {},
	"spambob.com":        {},
	"spambob.net":        {},
	"spambob.org":        {},
	"spambog.com":        {},
	"spambog.de":         {},
	"spambog.ru":         {},
	"spambox.us":         {},
	"spamcannon.com":     {},
	"spamcannon.net":     {},
	"spamcero.com":       {},
	"spamcon.org":        {},
	"spamcorptastic.com": {},
	"spamcowboy.com":     {},
	"spamcowboy.net":     {},
	"spamcowboy.org":     {},
	"spamday.com":        {},
	"spamex.com":         {},
	"spamfree.eu":        {},
	"spamfree24.com":     {},
	"spamfree24.de":      {},
	"spamfree24.eu":      {},
	"spamfree24.info":    {},
	"spamfree24.net":     {},
	"spamfree24.org":     {},
	"spamgoes.com":       {},
	"spamgourmet.com":    {},
	"spamgourmet.net":    {},
	"spamgourmet.org":    {},
	"spamhole.com":       {},
	"spamify.com":        {},
	"spaminator.de":      {},
	"spamkill.info":      {},
	"spaml.com":          {},
	"spaml.de":           {},
	"spammotel.com":      {},
	"spamobox.com":       {},
	"spamoff.de":         {},
	"spamslicer.com":     {},
	"spamspot.com":       {},
	"spamthis.co.uk":     {},
	"spamthisplease.com": {},
	"spamtroll.net":      {},
	"squizzy.de":         {},
	"ssoia.com":          {},
	"stinkefinger.net":   {},
	"stop-my-spam.com":   {},
	"stuffmail.de":       {},
	"super-auswahl.de":   {},
	"supergreatmail.com": {},
	"supermailer.jp":     {},
	"superrito.com":      {},
	"superstachel.de":    {},
	"talkinator.com":     {},
	"teewars.org":        {},
	"teleworm.com":       {},
	"teleworm.us":        {},
	"thanksnospam.info":  {},
	"thankyou2010.com":   {},
	"thecloudindex.com":  {},
	"thelimestones.com":  {},
	"thismail.net":       {},
	"throwawayemailaddress.com": {},
	"tilien.com":         {},
	"tmail.ws":           {},
	"tmailinator.com":    {},
	"toomail.biz":        {},
	"topranklist.de":     {},
	"trash2009.com":      {},
	"trashdevil.com":     {},
	"trashemail.de":      {},
	"trashinbox.com":     {},
	"trbvm.com":          {},
	"trialmail.de":       {},
	"trillianpro.com":    {},
	"twinmail.de":        {},
	"tyldd.com":          {},
	"uggsrock.com":       {},
	"umail.net":          {},
	"upliftnow.com":      {},
	"uplipht.com":        {},
	"uroid.com":          {},
	"us.af":              {},
	"venompen.com":       {},
	"viditag.com":        {},
	"viralplays.com":     {},
	"vpn.st":             {},
	"vsimcard.com":       {},
	"vubby.com":          {},
	"wasteland.rfc822.org": {},
	"webemail.me":        {},
	"weg-werf-email.de":  {},
	"wegwerf-emails.de":  {},
	"wegwerfadresse.de":  {},
	"wegwerfemail.com":   {},
	"wegwerfemailadresse.com": {},
	"wegwerfmail.info":   {},
	"wegwerpmailadres.nl": {},
	"wetrainbayarea.com": {},
	"wetrainbayarea.org": {},
	"wh4f.org":           {},
	"whatpaas.com":       {},
	"whyspam.me":         {},
	"willhackforfood.biz": {},
	"willselfdestruct.com": {},
	"winemaven.info":     {},
	"wronghead.com":      {},
	"wuzup.net":          {},
	"wuzupmail.net":      {},
	"www.e4ward.com":     {},
	"www.mailinator.com": {},
	"wwwnew.eu":          {},
	"x.ip6.li":           {},
	"xagloo.com":         {},
	"xemaps.com":         {},
	"xents.com":          {},
	"xmaily.com":         {},
	"xoxy.net":           {},
	"yapped.net":         {},
	"yep.it":             {},
	"yogamaven.com":      {},
	"yougotgoated.com":   {},
	"youmail.ga":         {},
	"yuurok.com":         {},
	"z1p.biz":            {},
	"za.com":             {},
	"zehnminuten.de":     {},
	"zehnminutenmail.de": {},
	"zetmail.com":        {},
	"zoaxe.com":          {},
	"zoemail.com":        {},
	"zoemail.net":        {},
	"zoemail.org":        {},
	"zomg.info":          {},
}

// IsDisposable returns true if the email's domain is in the embedded
// disposable-email blocklist. The check is case-insensitive on the
// domain. Local-part is ignored.
//
// Returns false for malformed input (no @, empty domain) — the
// caller's email-format validator is responsible for rejecting those
// shapes earlier in the pipeline.
func IsDisposable(email string) bool {
	at := strings.LastIndex(email, "@")
	if at < 0 || at == len(email)-1 {
		return false
	}
	domain := strings.ToLower(strings.TrimSpace(email[at+1:]))
	if domain == "" {
		return false
	}
	_, ok := disposableDomains[domain]
	return ok
}
