package memql

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/znasllc-io/memql/core/common"
)

// suggest_knowledge.go -- the `knowledge` suggest domain (memql#1959).
//
// knowledge is CORE (epic 3.1): it powers the workspace knowledge-domain
// picker, a platform-level surface every frontend shares, so its handler is
// registered from core (this file) rather than the pack. The schema + prompt
// builder + post-process were moved verbatim out of
// component/server/sihttp/knowledge_suggest.go so the structured-output output
// is byte-equivalent to the pre-extraction switch.
//
// The 9 product suggest domains live in the pack (the carrier repo)
// and register under the pack's build tag.

func init() {
	RegisterSuggestDomain("knowledge", buildKnowledgeSuggest)
}

// buildKnowledgeSuggest is the SuggestDomainHandler for the `knowledge`
// domain. Mirrors the old switch's `case "knowledge"` branch: the user types
// (or speaks) a free-text description of what content the domain should cover;
// we turn that into {name, description, category}. The model is shown the
// existing-domain list so its proposed name doesn't collide and so the category
// lines up with how related domains have been categorised. Scope (workspace /
// private) is collected by the modal itself -- it's an authorization decision,
// not a generative one.
func buildKnowledgeSuggest(ctx SuggestContext) (SuggestPlan, error) {
	description := ctx.String("description")
	if strings.TrimSpace(description) == "" {
		return SuggestPlan{}, SuggestValidationErrorf("description is required in payload")
	}
	existingDomains := extractKnowledgeExistingDomains(ctx.Payload)
	return SuggestPlan{
		Messages:    buildKnowledgeSuggestMessages(description, existingDomains),
		Schema:      knowledgeSuggestSchemaJSON,
		SchemaName:  "knowledgeConfigSuggest",
		PostProcess: postProcessKnowledgeSuggestion,
	}, nil
}

// extractKnowledgeExistingDomains extracts existing knowledge domain
// descriptors from a suggest payload map. The frontend's knowledge modal passes
// the workspace's existing domains under "existingDomains" so the model can
// avoid name collisions and pick a category consistent with how related domains
// are categorised.
func extractKnowledgeExistingDomains(payload map[string]any) []knowledgeExistingDomain {
	domainsRaw, ok := payload["existingDomains"].([]any)
	if !ok {
		return nil
	}
	str := func(m map[string]any, key string) string {
		if v, ok := m[key].(string); ok {
			return v
		}
		return ""
	}
	var domains []knowledgeExistingDomain
	for _, d := range domainsRaw {
		m, ok := d.(map[string]any)
		if !ok {
			continue
		}
		domains = append(domains, knowledgeExistingDomain{
			Name:        str(m, "name"),
			Description: str(m, "description"),
			Category:    str(m, "category"),
		})
	}
	return domains
}

// knowledgeSuggestSchemaJSON is the JSON Schema enforced on knowledge domain
// suggestion output. Mirrors the fields buildKnowledgeSuggestMessages asks the
// model for. Drives the describe-phase + AI-suggest flow on the frontend's
// knowledge modal.
//
// Fields:
//   - name        : short title for the domain (1-4 words). Becomes the row
//     label in the Knowledge panel.
//   - description : 1-2 sentences explaining what content the domain covers.
//     Surfaced on the row + on each agent's knowledge picker.
//   - category    : one of core / business / technical / product / internal --
//     drives the grouping header on the Knowledge panel list.
//
// Scope (workspace vs private) is intentionally NOT generated by the AI; it's
// an authorization decision the user makes themselves and the modal collects it
// via a chip toggle.
var knowledgeSuggestSchemaJSON = json.RawMessage(`{
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "description", "category"],
  "properties": {
    "name": {
      "type": "string",
      "description": "Short title for the knowledge domain, 1-4 words. Should read as a topic label, not a sentence. Examples: \"HR Records\", \"API Reference\", \"Sales Playbook\". No suffixes like \"Knowledge\" or \"Domain\"."
    },
    "description": {
      "type": "string",
      "description": "1-2 sentences explaining what content this domain covers and when an agent should draw on it."
    },
    "category": {
      "type": "string",
      "enum": ["core", "business", "technical", "product", "internal"],
      "description": "Domain category. core = always-attached baseline knowledge. business = company / industry / domain knowledge. technical = APIs, runbooks, code conventions. product = product surface area, features, UX. internal = HR, ops, finance, internal-only."
    }
  }
}`)

// knowledgeExistingDomain is a thin descriptor of a domain that already exists
// in the workspace. The model is shown the existing list so its proposed name
// doesn't collide and so it can pick the category consistently with how the
// user has been categorising related domains.
type knowledgeExistingDomain struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Category    string `json:"category"`
}

// buildKnowledgeSuggestMessages builds the system + user prompts for a
// knowledge-domain suggestion. The user description is the free-text the
// operator typed into the modal's describe phase (optionally produced by voice
// transcription); the existing-domain list helps the model avoid name
// collisions and pick a consistent category.
func buildKnowledgeSuggestMessages(description string, existing []knowledgeExistingDomain) []common.ChatMessage {
	var existingLines []string
	for _, d := range existing {
		cat := d.Category
		if cat == "" {
			cat = "business"
		}
		existingLines = append(existingLines, fmt.Sprintf("- %s [%s]: %s", d.Name, cat, d.Description))
	}
	existingList := "(none)"
	if len(existingLines) > 0 {
		existingList = strings.Join(existingLines, "\n")
	}

	systemPrompt := fmt.Sprintf(`Configure a knowledge domain from a free-text description. Return ONLY flat JSON (no nesting, no markdown).

Fields:
- name: short topic-style label, 1-4 words. Examples: "HR Records", "API Reference", "Sales Playbook". Do NOT append "Knowledge", "Domain", "Library", "Hub".
- description: 1-2 sentences describing what content lives in this domain and when an agent should draw on it.
- category: pick exactly one of:
    * core      -- always-attached baseline knowledge.
    * business  -- company, industry, or domain knowledge.
    * technical -- APIs, runbooks, code conventions, infra.
    * product   -- product surface area, features, UX, onboarding.
    * internal  -- HR, ops, finance, legal, internal-only.

Existing domains (avoid colliding with these names; pick a category that's consistent with how related domains have been categorised):
%s

Rules: keep name under 4 words, no suffixes. Return flat JSON only.`, existingList)

	userPrompt := fmt.Sprintf(`User wants to create a knowledge domain for: "%s"`, strings.TrimSpace(description))

	return []common.ChatMessage{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: userPrompt},
	}
}

// postProcessKnowledgeSuggestion clamps + sanitises the suggestion the model
// returned. We trust the structured-output schema to enforce the field set +
// the category enum, but we still:
//   - trim whitespace
//   - normalise category casing
//   - default category to 'business' if the model produced something wild
//     (defensive; shouldn't fire when structured output is on)
func postProcessKnowledgeSuggestion(suggestion map[string]any) {
	if name, ok := suggestion["name"].(string); ok {
		suggestion["name"] = strings.TrimSpace(name)
	}
	if desc, ok := suggestion["description"].(string); ok {
		suggestion["description"] = strings.TrimSpace(desc)
	}
	if cat, ok := suggestion["category"].(string); ok {
		normalized := strings.ToLower(strings.TrimSpace(cat))
		switch normalized {
		case "core", "business", "technical", "product", "internal":
			suggestion["category"] = normalized
		default:
			suggestion["category"] = "business"
		}
	} else {
		suggestion["category"] = "business"
	}
}
