#!/usr/bin/env bash
# Lint the on-disk policies tree by running the policy loader
# (component/memql/policy_function_loader.go) as a one-shot CLI.
#
# Checks the same things the engine checks at startup:
#   - @tier annotation matches the directory placement
#   - @frontend_visible is only valid on bff-tier policies
#   - filename matches the function name (no prefix)
#   - downward-only delegation (core may NOT call bff)
#
# Exits 0 on success, non-zero with a structured error list on
# failure. The lint binary is generated by `go run` so there's
# nothing to install.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

function main() {
  cd "$ROOT"
  if [[ ! -d "dsl/v1/policies" ]]; then
    echo "policies-lint: missing dsl/v1/policies"
    exit 1
  fi
  go run ./scripts/policies/cli "$@"
}

main "$@"
