// Code generated by scripts/sdk-gen. DO NOT EDIT.
// Source of truth: dsl/**/*.memql.

import { QueryClient, type QueryCallOptions } from "./query.js";
import type { Result } from "./types.js";
import { renderMemQLValue } from "./memqlValue.js";

/** Generate an event-email rule's automation construct and arm it (memql#4829). The generator is a DETERMINISTIC template over the rule's form -- the LLM authoring path stays off, because a rule that mails strangers is not a place for a model to improvise and a deterministic generator is one a person can read the output of. The generated .memql goes through the ordinary authoring pipeline: bundle, validate, activate. Activation takes effect IMMEDIATELY rather than at next boot. The rule row records the bundle and construct it produced; on refusal it records the engine's own sentence on lastError and the rule goes to 'failed' rather than silently staying draft. */
export interface CampaignActivateEmailRuleArgs {
  /** The rule to generate and arm. The caller must own it: the generated construct runs under the AUTHOR's envelope, so who armed it decides what it can read. */
  emailRuleId: string;
}

export function buildCampaignActivateEmailRule(args: CampaignActivateEmailRuleArgs): string {
  const parts: string[] = [];
  parts.push("emailRuleId: " + renderMemQLValue(args.emailRuleId));
  return "builtin campaignActivateEmailRule(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignActivateEmailRule(args: CampaignActivateEmailRuleArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignActivateEmailRule = function (this: QueryClient, args: CampaignActivateEmailRuleArgs = {} as CampaignActivateEmailRuleArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignActivateEmailRule", buildCampaignActivateEmailRule(args), opts);
};

/** Import recipients into an audience from a CSV file already uploaded to the Library (memql#4822). The file is read SERVER-SIDE under the caller's own actor, so a file the caller cannot read is a file this cannot import -- the artifact id is not a capability. The header row must carry an `email` column (case-insensitive; `displayName` and `name` are also recognized) and EVERY OTHER COLUMN lands verbatim in the recipient's `fields` map, reachable from a template as {{fields.<key>}}. Per row: the address is normalized and shape-validated, deduplicated against the audience's existing recipients AND against earlier rows of the same file (first occurrence wins). The import refuses WHOLE when the resulting roster would exceed MEMQL_CAMPAIGNS_MAX_AUDIENCE -- it never silently truncates, because a partially-imported list is one nobody knows is partial. Returns {added, duplicates, invalid, total} plus up to 20 sample invalid lines with their line numbers, so the operator's next action is fixing the file rather than guessing at it. Each added recipient also gets a consent grant event with source 'import'. */
export interface CampaignImportRecipientsArgs {
  /** The audience to import into. The caller must be able to read it. */
  audienceId: string;
  /** v1:library:artifact.id of the uploaded CSV. Read under the caller's actor -- an artifact the caller cannot read is not found. */
  artifactId: string;
  /** Whether the first row is a header. Defaults true. A file with no header cannot be imported: the column mapping IS the header, and guessing which column holds addresses is how an import mails the wrong list. */
  hasHeader?: boolean;
}

export function buildCampaignImportRecipients(args: CampaignImportRecipientsArgs): string {
  const parts: string[] = [];
  parts.push("audienceId: " + renderMemQLValue(args.audienceId));
  parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  if (args.hasHeader !== undefined) parts.push("hasHeader: " + renderMemQLValue(args.hasHeader));
  return "builtin campaignImportRecipients(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignImportRecipients(args: CampaignImportRecipientsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignImportRecipients = function (this: QueryClient, args: CampaignImportRecipientsArgs = {} as CampaignImportRecipientsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignImportRecipients", buildCampaignImportRecipients(args), opts);
};

/** Pause a running campaign send. The delivery ledger is untouched, so resuming continues exactly where it stopped -- 'where it stopped' is the set of recipients with no delivery row, not a cursor that could go stale. */
export interface CampaignPauseSendArgs {
  /** The campaign to pause. The caller must own it. */
  campaignId: string;
}

export function buildCampaignPauseSend(args: CampaignPauseSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignPauseSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignPauseSend(args: CampaignPauseSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignPauseSend = function (this: QueryClient, args: CampaignPauseSendArgs = {} as CampaignPauseSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignPauseSend", buildCampaignPauseSend(args), opts);
};

/** Resume a paused campaign send. Does not re-stamp startedAt: the gap between startedAt and completedAt is how long the run took, and resetting it on resume would erase the pause it exists to reveal. */
export interface CampaignResumeSendArgs {
  /** The campaign to resume. The caller must own it. */
  campaignId: string;
}

export function buildCampaignResumeSend(args: CampaignResumeSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignResumeSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignResumeSend(args: CampaignResumeSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignResumeSend = function (this: QueryClient, args: CampaignResumeSendArgs = {} as CampaignResumeSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignResumeSend", buildCampaignResumeSend(args), opts);
};

/** Retire an event-email rule's generated construct (memql#4829). The automation stops firing and the bundle is retired; the RULE row survives with its history, because a rule somebody turned off is a different thing from one that never existed. Used by delete and by edit-and-regenerate, which retires the old bundle before arming the new one -- so a rule is never armed twice. */
export interface CampaignRetireEmailRuleArgs {
  /** The rule whose construct should be retired. */
  emailRuleId: string;
}

export function buildCampaignRetireEmailRule(args: CampaignRetireEmailRuleArgs): string {
  const parts: string[] = [];
  parts.push("emailRuleId: " + renderMemQLValue(args.emailRuleId));
  return "builtin campaignRetireEmailRule(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignRetireEmailRule(args: CampaignRetireEmailRuleArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignRetireEmailRule = function (this: QueryClient, args: CampaignRetireEmailRuleArgs = {} as CampaignRetireEmailRuleArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignRetireEmailRule", buildCampaignRetireEmailRule(args), opts);
};

/** Commit a campaign to a time and enqueue the send job that will fire at it (memql#3459). Runs the SAME preflight as campaignStartSend -- sender registered, one-click unsubscribe configured, template marked ready, audience non-empty and inside the ceiling -- because the whole value of scheduling is finding out now rather than at 3am. The job it writes is inert: it sits in the 'scheduled' status until the drain worker sees that the campaign's scheduledAt has passed, and the campaign row is the authority on that time, so moving the date with updateCampaign moves the send. A time in the past is refused; use campaignStartSend to send now. Authorization is the owned-tier read of the campaign, exactly as for starting one by hand. */
export interface CampaignScheduleSendArgs {
  /** The campaign to schedule. The caller must own it. */
  campaignId: string;
  /** When the send should begin, RFC 3339 (e.g. 2026-08-14T09:00:00Z). Interpreted as an instant, not a local wall clock -- a value with no offset is read as UTC. */
  scheduledAt: string;
}

export function buildCampaignScheduleSend(args: CampaignScheduleSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  parts.push("scheduledAt: " + renderMemQLValue(args.scheduledAt));
  return "builtin campaignScheduleSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignScheduleSend(args: CampaignScheduleSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignScheduleSend = function (this: QueryClient, args: CampaignScheduleSendArgs = {} as CampaignScheduleSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignScheduleSend", buildCampaignScheduleSend(args), opts);
};

/** Preflight and start a campaign send. Refuses -- rather than partially sending -- when no email sender is registered on the node, when one-click unsubscribe is not configured (MEMQL_CAMPAIGNS_UNSUBSCRIBE_SECRET / _BASE_URL), when the template is not marked ready, or when the audience is empty or at the MEMQL_CAMPAIGNS_MAX_AUDIENCE ceiling. Authorization is the owned-tier read of the campaign: a caller who cannot read it cannot start it. Returns the recipient count the send will work through. */
export interface CampaignStartSendArgs {
  /** The campaign to send. The caller must own it. */
  campaignId: string;
}

export function buildCampaignStartSend(args: CampaignStartSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignStartSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignStartSend(args: CampaignStartSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignStartSend = function (this: QueryClient, args: CampaignStartSendArgs = {} as CampaignStartSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignStartSend", buildCampaignStartSend(args), opts);
};

/** The outcome breakdown for one campaign (memql#4823): recipients, pending, sent, failed, the skipped bucket split into suppressed / unsubscribed / other, hard bounces, complaints, one-click unsubscribes, and opens and clicks as both total and unique. Computed SERVER-SIDE from the delivery ledger, the campaign's consent events and its engagement events -- every bucket that can be an exact COUNT is one, at any audience size. This replaces counting a capped page of rows in the browser, which under-reported every campaign past the page bound and did so silently. Two figures are honest about their limits rather than rounded into a number: a unique open/click count is folded from a bounded read and is reported as UNMEASURED rather than as a wrong number when that bound is reached, and soft bounces are absent entirely because nothing measures them per campaign -- an absent figure and a zero are different answers. */
export interface CampaignStatsArgs {
  /** The campaign to report on. The caller must be able to read it. */
  campaignId: string;
}

export function buildCampaignStats(args: CampaignStatsArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignStats(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignStats(args: CampaignStatsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignStats = function (this: QueryClient, args: CampaignStatsArgs = {} as CampaignStatsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignStats", buildCampaignStats(args), opts);
};

/** Send one test copy of a campaign to a named address (memql#4822). Renders the campaign's template against a synthetic recipient -- display name 'Test Recipient', the address you name, and the `fields` of the audience's first real recipient when one exists, so {{fields.*}} show the shape they will actually have. The subject is prefixed '[Test] ', the message goes through the campaign's resolved sending identity, and the unsubscribe footer carries an obviously-inert token. It writes NO delivery row and touches NO counter, so a test send can never make a campaign look partly sent; it does consume the ordinary send-rate token bucket, because a test is a real message to a real mailbox. Returns the list of merge tags it could not resolve -- the check that catches a typo'd {{fields.compnay}} before the whole audience gets it. `to` is REQUIRED and never defaults to the caller's own address: a builtin that mails somewhere you did not name is one you have to remember the default of. */
export interface CampaignTestSendArgs {
  /** The campaign to render. The caller must be able to read it. */
  campaignId: string;
  /** Where to send the test. Required and validated -- there is deliberately no default. */
  to: string;
}

export function buildCampaignTestSend(args: CampaignTestSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  parts.push("to: " + renderMemQLValue(args.to));
  return "builtin campaignTestSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignTestSend(args: CampaignTestSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignTestSend = function (this: QueryClient, args: CampaignTestSendArgs = {} as CampaignTestSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignTestSend", buildCampaignTestSend(args), opts);
};

/** One B2B account: its orders in a window, how many still have payment terms outstanding, and its MemQL-owned credit limit. The two halves come from different systems, and the question a rep asks -- can this account order -- needs both. */
export interface CommerceCompanyArgs {
  storeId?: string;
  companyGid?: string;
  from?: string;
  to?: string;
}

export function buildCommerceCompany(args: CommerceCompanyArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  if (args.companyGid !== undefined) parts.push("companyGid: " + renderMemQLValue(args.companyGid));
  if (args.from !== undefined) parts.push("from: " + renderMemQLValue(args.from));
  if (args.to !== undefined) parts.push("to: " + renderMemQLValue(args.to));
  return "builtin commerceCompany(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    commerceCompany(args: CommerceCompanyArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.commerceCompany = function (this: QueryClient, args: CommerceCompanyArgs = {} as CommerceCompanyArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("commerceCompany", buildCommerceCompany(args), opts);
};

/** Repeat-customer and refund rates for a window, from the mirror. Repeat rate is customers with more than one order over customers with any; refund rate is refunds over orders. */
export interface CommerceCustomersArgs {
  storeId?: string;
  from?: string;
  to?: string;
}

export function buildCommerceCustomers(args: CommerceCustomersArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  if (args.from !== undefined) parts.push("from: " + renderMemQLValue(args.from));
  if (args.to !== undefined) parts.push("to: " + renderMemQLValue(args.to));
  return "builtin commerceCustomers(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    commerceCustomers(args: CommerceCustomersArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.commerceCustomers = function (this: QueryClient, args: CommerceCustomersArgs = {} as CommerceCustomersArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("commerceCustomers", buildCommerceCustomers(args), opts);
};

/** What sold in a window, grouped by product or by variant, read entirely from the mirror -- no Admin API call and no cost points. Reports units and orders per line, and reports truncated=true when the walk hit its page cap rather than returning a smaller number and letting the caller believe it. */
export interface CommerceSoldArgs {
  storeId?: string;
  from?: string;
  to?: string;
  groupBy?: string;
}

export function buildCommerceSold(args: CommerceSoldArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  if (args.from !== undefined) parts.push("from: " + renderMemQLValue(args.from));
  if (args.to !== undefined) parts.push("to: " + renderMemQLValue(args.to));
  if (args.groupBy !== undefined) parts.push("groupBy: " + renderMemQLValue(args.groupBy));
  return "builtin commerceSold(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    commerceSold(args: CommerceSoldArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.commerceSold = function (this: QueryClient, args: CommerceSoldArgs = {} as CommerceSoldArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("commerceSold", buildCommerceSold(args), opts);
};

/** Inventory levels below a threshold at one location. Shopify models inventory as NAMED quantities (available, committed, on_hand), so the threshold is applied in Go and a level with no `available` count reads as unknown rather than as a stockout. */
export interface CommerceStockArgs {
  storeId?: string;
  locationGid?: string;
  threshold?: number;
}

export function buildCommerceStock(args: CommerceStockArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  if (args.locationGid !== undefined) parts.push("locationGid: " + renderMemQLValue(args.locationGid));
  if (args.threshold !== undefined) parts.push("threshold: " + renderMemQLValue(args.threshold));
  return "builtin commerceStock(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    commerceStock(args: CommerceStockArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.commerceStock = function (this: QueryClient, args: CommerceStockArgs = {} as CommerceStockArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("commerceStock", buildCommerceStock(args), opts);
};

/** The reachable half of creating a binding: mint the ownership token, prefill the account tie, and write the row. `createCustomDomain` itself is @serverOnly precisely so this is the only way in -- a caller who chooses their own verification token proves nothing by publishing it. */
export interface CustomDomainAddArgs {
  /** The v1:platform:site row this domain should serve. */
  siteId: string;
  /** The client's own fully qualified host, e.g. www.acme.com or acme.com. */
  hostname: string;
}

export function buildCustomDomainAdd(args: CustomDomainAddArgs): string {
  const parts: string[] = [];
  parts.push("siteId: " + renderMemQLValue(args.siteId));
  parts.push("hostname: " + renderMemQLValue(args.hostname));
  return "builtin customDomainAdd(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    customDomainAdd(args: CustomDomainAddArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.customDomainAdd = function (this: QueryClient, args: CustomDomainAddArgs = {} as CustomDomainAddArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("customDomainAdd", buildCustomDomainAdd(args), opts);
};

/** List every registered concept with its data state (mirror | origin | native), the system where its changes are made, and the connectors it depends on. Produced from the live concept registry, never persisted. Feeds the portal's Data origins page. */
export interface DataOriginsArgs {
}

export function buildDataOrigins(args: DataOriginsArgs): string {
  void args;
  return "builtin dataOrigins()";
}

declare module "./query.js" {
  interface QueryClient {
    dataOrigins(args?: DataOriginsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.dataOrigins = function (this: QueryClient, args: DataOriginsArgs = {} as DataOriginsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("dataOrigins", buildDataOrigins(args), opts);
};

/** Discard one DEAD-lettered outbox entry: the operator has decided this change will never be delivered. The row survives as audit history carrying the reason. Refuses an entry that is not dead. */
export interface DatasyncDiscardOutboxEntryArgs {
  entryId: string;
  reason?: string;
}

export function buildDatasyncDiscardOutboxEntry(args: DatasyncDiscardOutboxEntryArgs): string {
  const parts: string[] = [];
  parts.push("entryId: " + renderMemQLValue(args.entryId));
  if (args.reason !== undefined) parts.push("reason: " + renderMemQLValue(args.reason));
  return "builtin datasyncDiscardOutboxEntry(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    datasyncDiscardOutboxEntry(args: DatasyncDiscardOutboxEntryArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.datasyncDiscardOutboxEntry = function (this: QueryClient, args: DatasyncDiscardOutboxEntryArgs = {} as DatasyncDiscardOutboxEntryArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("datasyncDiscardOutboxEntry", buildDatasyncDiscardOutboxEntry(args), opts);
};

/** Return one DEAD-lettered outbox entry to the queue with its attempts reset. Refuses an entry that is not dead: a pending or failed one is still the drain worker's, and acting on it would race a delivery in flight. */
export interface DatasyncRetryOutboxEntryArgs {
  entryId: string;
}

export function buildDatasyncRetryOutboxEntry(args: DatasyncRetryOutboxEntryArgs): string {
  const parts: string[] = [];
  parts.push("entryId: " + renderMemQLValue(args.entryId));
  return "builtin datasyncRetryOutboxEntry(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    datasyncRetryOutboxEntry(args: DatasyncRetryOutboxEntryArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.datasyncRetryOutboxEntry = function (this: QueryClient, args: DatasyncRetryOutboxEntryArgs = {} as DatasyncRetryOutboxEntryArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("datasyncRetryOutboxEntry", buildDatasyncRetryOutboxEntry(args), opts);
};

/** Pause or resume one domain: stops its backfill, its reconciliation and its outbox drain, without unregistering the connector or changing any declaration. */
export interface DatasyncSetSyncPausedArgs {
  connector: string;
  conceptId: string;
  paused: boolean;
}

export function buildDatasyncSetSyncPaused(args: DatasyncSetSyncPausedArgs): string {
  const parts: string[] = [];
  parts.push("connector: " + renderMemQLValue(args.connector));
  parts.push("conceptId: " + renderMemQLValue(args.conceptId));
  parts.push("paused: " + renderMemQLValue(args.paused));
  return "builtin datasyncSetSyncPaused(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    datasyncSetSyncPaused(args: DatasyncSetSyncPausedArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.datasyncSetSyncPaused = function (this: QueryClient, args: DatasyncSetSyncPausedArgs = {} as DatasyncSetSyncPausedArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("datasyncSetSyncPaused", buildDatasyncSetSyncPaused(args), opts);
};

/** Drive one domain's backfill page by page from its stored cursor, persisting progress on v1:platform:syncState after every page so a restart resumes rather than restarts. Operator-driven; nothing schedules it. */
export interface DatasyncStartBackfillArgs {
  connector: string;
  conceptId: string;
}

export function buildDatasyncStartBackfill(args: DatasyncStartBackfillArgs): string {
  const parts: string[] = [];
  parts.push("connector: " + renderMemQLValue(args.connector));
  parts.push("conceptId: " + renderMemQLValue(args.conceptId));
  return "builtin datasyncStartBackfill(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    datasyncStartBackfill(args: DatasyncStartBackfillArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.datasyncStartBackfill = function (this: QueryClient, args: DatasyncStartBackfillArgs = {} as DatasyncStartBackfillArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("datasyncStartBackfill", buildDatasyncStartBackfill(args), opts);
};

/** Append a new version of a Library document with new content. Reads the current latest version, computes the next versionNumber + parentVersionId, appends an immutable v1:library:documentVersion snapshot (authorKind=user|assistant) and re-inserts the backing generatedOutput so the Library viewer reflects the edit. Optimistic concurrency via expectedVersion. ownerUserId is threaded from the document row, never the caller. Backs both the user edit (memql#1229) and the assistant editDocument tool (memql#1231). */
export interface EditDocumentArgs {
  documentId: string;
  content?: string;
  attachmentId?: string;
  note?: string;
  // Enum: user | assistant | system
  authorKind?: string;
  authorId?: string;
  expectedVersion?: number;
  producedByPlanId?: string;
  partitionId?: string;
}

export function buildEditDocument(args: EditDocumentArgs): string {
  const parts: string[] = [];
  parts.push("documentId: " + renderMemQLValue(args.documentId));
  if (args.content !== undefined) parts.push("content: " + renderMemQLValue(args.content));
  if (args.attachmentId !== undefined) parts.push("attachmentId: " + renderMemQLValue(args.attachmentId));
  if (args.note !== undefined) parts.push("note: " + renderMemQLValue(args.note));
  if (args.authorKind !== undefined) parts.push("authorKind: " + renderMemQLValue(args.authorKind));
  if (args.authorId !== undefined) parts.push("authorId: " + renderMemQLValue(args.authorId));
  if (args.expectedVersion !== undefined) parts.push("expectedVersion: " + renderMemQLValue(args.expectedVersion));
  if (args.producedByPlanId !== undefined) parts.push("producedByPlanId: " + renderMemQLValue(args.producedByPlanId));
  if (args.partitionId !== undefined) parts.push("partitionId: " + renderMemQLValue(args.partitionId));
  return "builtin editDocument(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    editDocument(args: EditDocumentArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.editDocument = function (this: QueryClient, args: EditDocumentArgs = {} as EditDocumentArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("editDocument", buildEditDocument(args), opts);
};

/** List every model the caller's fleet can run right now: the model id, its context window and capability flags, and the machines behind it with their online and busy state. Produced from live worker registrations, never persisted -- the answer is which machines are awake, so a stored copy's staleness would be indistinguishable from the condition it describes. Scoped to the caller's own machines plus the shared-inference set; a model call carries the caller's prompts and routes only to their machines. Feeds the portal's Providers page and the fleet machine cards. */
export interface FleetModelsArgs {
}

export function buildFleetModels(args: FleetModelsArgs): string {
  void args;
  return "builtin fleetModels()";
}

declare module "./query.js" {
  interface QueryClient {
    fleetModels(args?: FleetModelsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.fleetModels = function (this: QueryClient, args: FleetModelsArgs = {} as FleetModelsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("fleetModels", buildFleetModels(args), opts);
};

/** Fetch a harness plan's full execution timeline (every plan/step version transition + all observations, ordered by createdAt) reconstructed from the append-only graph event stream. Returns one synthetic node carrying the rendered timeline string, a completion flag, and the step count. Owner-scoped to the caller's own plan. The history-over-gRPC contract for the cockpit `harness trace` CLI (memql-cockpit#142). */
export interface HarnessTraceArgs {
  planId: string;
}

export function buildHarnessTrace(args: HarnessTraceArgs): string {
  const parts: string[] = [];
  parts.push("planId: " + renderMemQLValue(args.planId));
  return "builtin harnessTrace(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    harnessTrace(args: HarnessTraceArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.harnessTrace = function (this: QueryClient, args: HarnessTraceArgs = {} as HarnessTraceArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("harnessTrace", buildHarnessTrace(args), opts);
};

/** Answer, in one row, whether this caller can get inference at all and through which of the three doors: a local model on their fleet, the Anthropic workload-identity federation, or a configured API key. Read from the SAME catalog and provider registry the router reads, so eligibility has exactly one implementation -- a second one drifts, and the drift lets a user through to a console whose features all refuse. Backs the portal's first-run gate. */
export interface InferenceStatusArgs {
}

export function buildInferenceStatus(args: InferenceStatusArgs): string {
  void args;
  return "builtin inferenceStatus()";
}

declare module "./query.js" {
  interface QueryClient {
    inferenceStatus(args?: InferenceStatusArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.inferenceStatus = function (this: QueryClient, args: InferenceStatusArgs = {} as InferenceStatusArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("inferenceStatus", buildInferenceStatus(args), opts);
};

/** Set one of an integration's configuration values from an operator surface (memql#4825). OWNER OR DEVELOPER ONLY, which is stricter than reading the status report: wiring up what this cluster talks to is a developer's job, and administering people -- what an admin is for -- is a different one. Three things this does that a client calling setGlobalVariable itself cannot. The row NAME is derived from the integration's declared manifest rather than taken from the caller, so a mistyped variable cannot become a row the resolver never reads and a save that reports success and changes nothing. The row ID reuses the seeder's derivation, so the write UPDATES the row an installed cluster already has instead of adding a second row carrying the same name. And a credential is sealed server-side under the cluster master key, which exists on nodes and must never exist in a browser -- the plaintext crosses the wire once and is never sent back. Afterwards the node discards its resolved sender, so the change takes effect on its next send with no restart; other replicas pick it up on their own next send, and the reply says so rather than implying the fleet moved at once. */
export interface IntegrationConfigureArgs {
  /** The manifest slot to set, e.g. senderAddress or clientSecret. A slot NAME, never an environment variable: the name is stable across a rename of the variable behind it, which is the whole reason a surface keys on it. */
  slot: string;
  /** The plaintext value. Sealed before storage when the slot is a credential, and never read back by any surface -- what a client can learn afterwards is that the slot is set, from where, and the command that rotates it. */
  value: string;
}

export function buildIntegrationConfigure(args: IntegrationConfigureArgs): string {
  const parts: string[] = [];
  parts.push("slot: " + renderMemQLValue(args.slot));
  parts.push("value: " + renderMemQLValue(args.value));
  return "builtin integrationConfigure(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    integrationConfigure(args: IntegrationConfigureArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.integrationConfigure = function (this: QueryClient, args: IntegrationConfigureArgs = {} as IntegrationConfigureArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("integrationConfigure", buildIntegrationConfigure(args), opts);
};

/** Report this node's integration registry: every plug-in the running binary registered, and for the email integration the resolved sender mode plus a slot-by-slot account of which settings and credentials are configured and where each came from. Credential VALUES are never included -- only presence, source and (for stored secrets) a fingerprint. Pass probe=true to additionally run a live, non-sending reachability check (Microsoft Graph: acquire a client-credentials token; SMTP: connect, EHLO, STARTTLS, AUTH, QUIT) and report its verdict; probe=false (the default) answers the configuration question only. */
export interface IntegrationStatusArgs {
  probe?: boolean;
}

export function buildIntegrationStatus(args: IntegrationStatusArgs): string {
  const parts: string[] = [];
  if (args.probe !== undefined) parts.push("probe: " + renderMemQLValue(args.probe));
  return "builtin integrationStatus(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    integrationStatus(args: IntegrationStatusArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.integrationStatus = function (this: QueryClient, args: IntegrationStatusArgs = {} as IntegrationStatusArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("integrationStatus", buildIntegrationStatus(args), opts);
};

/** Decide whether a chat exchange's topic warrants augmenting one of an agent's knowledge domains. Returns {outcome, domainId, topic, reasoning, confidence}. Drives the chat 'Analyze for training' button preflight. */
export interface KnowledgeAugmentDomainAnalyzeArgs {
  userQuestion: string;
  agentResponse: string;
  domains: Record<string, unknown>[];
  retrieved?: Record<string, unknown>[];
}

export function buildKnowledgeAugmentDomainAnalyze(args: KnowledgeAugmentDomainAnalyzeArgs): string {
  const parts: string[] = [];
  parts.push("userQuestion: " + renderMemQLValue(args.userQuestion));
  parts.push("agentResponse: " + renderMemQLValue(args.agentResponse));
  parts.push("domains: " + renderMemQLValue(args.domains));
  if (args.retrieved !== undefined) parts.push("retrieved: " + renderMemQLValue(args.retrieved));
  return "builtin knowledgeAugmentDomainAnalyze(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    knowledgeAugmentDomainAnalyze(args: KnowledgeAugmentDomainAnalyzeArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.knowledgeAugmentDomainAnalyze = function (this: QueryClient, args: KnowledgeAugmentDomainAnalyzeArgs = {} as KnowledgeAugmentDomainAnalyzeArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("knowledgeAugmentDomainAnalyze", buildKnowledgeAugmentDomainAnalyze(args), opts);
};

/** Generate + embed + persist topic-focused chunks for a knowledge domain. Inserts a Plan row for audit. Returns {planId, chunksAdded, domainId, domainName, topic}. */
export interface KnowledgeAugmentDomainGenerateArgs {
  domainId: string;
  topic: string;
  sourceUtteranceId?: string;
  sourceAgentId?: string;
  partitionId: string;
  requestedBy: string;
}

export function buildKnowledgeAugmentDomainGenerate(args: KnowledgeAugmentDomainGenerateArgs): string {
  const parts: string[] = [];
  parts.push("domainId: " + renderMemQLValue(args.domainId));
  parts.push("topic: " + renderMemQLValue(args.topic));
  if (args.sourceUtteranceId !== undefined) parts.push("sourceUtteranceId: " + renderMemQLValue(args.sourceUtteranceId));
  if (args.sourceAgentId !== undefined) parts.push("sourceAgentId: " + renderMemQLValue(args.sourceAgentId));
  parts.push("partitionId: " + renderMemQLValue(args.partitionId));
  parts.push("requestedBy: " + renderMemQLValue(args.requestedBy));
  return "builtin knowledgeAugmentDomainGenerate(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    knowledgeAugmentDomainGenerate(args: KnowledgeAugmentDomainGenerateArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.knowledgeAugmentDomainGenerate = function (this: QueryClient, args: KnowledgeAugmentDomainGenerateArgs = {} as KnowledgeAugmentDomainGenerateArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("knowledgeAugmentDomainGenerate", buildKnowledgeAugmentDomainGenerate(args), opts);
};

/** Add a label to a Library artifact index row. Idempotent -- a label already present is left alone and nothing is written. artifactId is the v1:library:artifact row id; the load + write-back run under a synthetic actor derived from the row's own ownerUserId, so a caller can only ever label an artifact they own. */
export interface LibraryAddArtifactLabelArgs {
  artifactId: string;
  label: string;
}

export function buildLibraryAddArtifactLabel(args: LibraryAddArtifactLabelArgs): string {
  const parts: string[] = [];
  parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  parts.push("label: " + renderMemQLValue(args.label));
  return "builtin libraryAddArtifactLabel(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    libraryAddArtifactLabel(args: LibraryAddArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.libraryAddArtifactLabel = function (this: QueryClient, args: LibraryAddArtifactLabelArgs = {} as LibraryAddArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("libraryAddArtifactLabel", buildLibraryAddArtifactLabel(args), opts);
};

/** Remove a label from a Library artifact index row. Idempotent -- a label already absent is left alone and nothing is written. Same owner-threaded load/write shape as libraryAddArtifactLabel. */
export interface LibraryRemoveArtifactLabelArgs {
  artifactId: string;
  label: string;
}

export function buildLibraryRemoveArtifactLabel(args: LibraryRemoveArtifactLabelArgs): string {
  const parts: string[] = [];
  parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  parts.push("label: " + renderMemQLValue(args.label));
  return "builtin libraryRemoveArtifactLabel(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    libraryRemoveArtifactLabel(args: LibraryRemoveArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.libraryRemoveArtifactLabel = function (this: QueryClient, args: LibraryRemoveArtifactLabelArgs = {} as LibraryRemoveArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("libraryRemoveArtifactLabel", buildLibraryRemoveArtifactLabel(args), opts);
};

/** Search the caller's Library by meaning and get whole artifacts back, best match first. */
export interface LibrarySimilarArtifactsArgs {
  /** The phrase to search by. Set this OR artifactId. */
  text?: string;
  /** Find artifacts similar to this one. Set this OR text. */
  artifactId?: string;
  /** Maximum artifacts to return. Defaults to 5; capped at 50, because each returned artifact costs one further owner-gated read. */
  limit?: number;
}

export function buildLibrarySimilarArtifacts(args: LibrarySimilarArtifactsArgs): string {
  const parts: string[] = [];
  if (args.text !== undefined) parts.push("text: " + renderMemQLValue(args.text));
  if (args.artifactId !== undefined) parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  if (args.limit !== undefined) parts.push("limit: " + renderMemQLValue(args.limit));
  return "builtin librarySimilarArtifacts(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    librarySimilarArtifacts(args: LibrarySimilarArtifactsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.librarySimilarArtifacts = function (this: QueryClient, args: LibrarySimilarArtifactsArgs = {} as LibrarySimilarArtifactsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("librarySimilarArtifacts", buildLibrarySimilarArtifacts(args), opts);
};

/** Train a Library file into a knowledge domain -- the deliberate second act after upload. */
export interface LibraryTrainFileArgs {
  /** The v1:library:file row id to train. Must belong to the acting user. */
  fileId: string;
  /** Id of the knowledge domain to train the file into. */
  domainId: string;
}

export function buildLibraryTrainFile(args: LibraryTrainFileArgs): string {
  const parts: string[] = [];
  parts.push("fileId: " + renderMemQLValue(args.fileId));
  parts.push("domainId: " + renderMemQLValue(args.domainId));
  return "builtin libraryTrainFile(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    libraryTrainFile(args: LibraryTrainFileArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.libraryTrainFile = function (this: QueryClient, args: LibraryTrainFileArgs = {} as LibraryTrainFileArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("libraryTrainFile", buildLibraryTrainFile(args), opts);
};

/** Analyze a package source offline and return the report, deploying nothing (epic memql#4794, D12). Fetches the tracked source, walks the manifest, discovers the DSL domains and runs the SAME Init-grade gates strict boot runs -- so 'this DSL would refuse boot' is an answer produced here, before a pod is ever asked to run it. Returns {report, ok}: the report names every deployable with its build plan (or 'prebuilt output found -- build skipped'), every DSL domain with construct counts, any Go pack as reported-not-deployable, and every problem found. A refusal carries one of the stable codes in component/packages/refusal.go. */
export interface PackageAnalyzeArgs {
  /** The v1:platform:package row to analyze. */
  packageId: string;
}

export function buildPackageAnalyze(args: PackageAnalyzeArgs): string {
  const parts: string[] = [];
  parts.push("packageId: " + renderMemQLValue(args.packageId));
  return "builtin packageAnalyze(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    packageAnalyze(args: PackageAnalyzeArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.packageAnalyze = function (this: QueryClient, args: PackageAnalyzeArgs = {} as PackageAnalyzeArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("packageAnalyze", buildPackageAnalyze(args), opts);
};

/** Archive one of the caller's packages (epic memql#4794, D10). Refuses with package_has_active_deployables when any site this package deployed is not itself archived -- a package is the source its deployables came from, and filing it away while it is still serving the internet would put the record and the reality in different states. Also refuses unless confirmName matches the package's stored name exactly. Archived packages stay listed behind the Archived filter. Returns {packageId, name, status}. */
export interface PackageArchiveArgs {
  /** The v1:platform:package row to archive. */
  packageId: string;
  /** The package's own name, typed by the person as confirmation. Compared against the stored value; a mismatch refuses and writes nothing. */
  confirmName: string;
}

export function buildPackageArchive(args: PackageArchiveArgs): string {
  const parts: string[] = [];
  parts.push("packageId: " + renderMemQLValue(args.packageId));
  parts.push("confirmName: " + renderMemQLValue(args.confirmName));
  return "builtin packageArchive(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    packageArchive(args: PackageArchiveArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.packageArchive = function (this: QueryClient, args: PackageArchiveArgs = {} as PackageArchiveArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("packageArchive", buildPackageArchive(args), opts);
};

/** Run one deployment attempt for a package (epic memql#4794). WITHOUT confirm the run parks at awaiting_confirm with the analysis report on a new deployment row and nothing else happens -- that gate is always present (D12), and a redeploy passes it in one click. WITH confirm the run builds, stages, rolls and publishes in the D6 order: a failure anywhere before publish leaves every site serving exactly what it was serving, and a package with no DSL (or unchanged DSL) skips stage and roll entirely so nothing restarts. A package carrying DSL requires the cluster-owner actor and is refused with dsl_requires_cluster_owner at the START, before any build. hostnames is required only for a deployable's FIRST deploy; later deploys find the site through (packageId, packageDeployableName). Returns {deploymentId, status, awaitingConfirm, deployables, report}. */
export interface PackageDeployArgs {
  /** The v1:platform:package row to deploy. */
  packageId: string;
  /** Pass true to proceed past the confirm gate. Absent or false parks the run with its report and returns. */
  confirm?: boolean;
  /** Retry an earlier run from the bytes it already fetched (epic memql#4900, task memql#4902), rather than fetching the source again. The run re-analyses the SAME snapshot, so a Retry after a node was lost deploys exactly what the lost run was deploying -- not whatever the branch has moved to since. Refused with snapshot_unavailable when that run kept no snapshot, which is every run from before snapshots were stored; deploy without it to fetch fresh. Ignored for a zip-sourced package, whose Library artifact IS its snapshot. */
  fromDeploymentId?: string;
  /** Deployable name -> hostname, for deployables being deployed for the FIRST time. A hostname is chosen once and remembered on the site row. */
  hostnames?: Record<string, unknown>;
}

export function buildPackageDeploy(args: PackageDeployArgs): string {
  const parts: string[] = [];
  parts.push("packageId: " + renderMemQLValue(args.packageId));
  if (args.confirm !== undefined) parts.push("confirm: " + renderMemQLValue(args.confirm));
  if (args.fromDeploymentId !== undefined) parts.push("fromDeploymentId: " + renderMemQLValue(args.fromDeploymentId));
  if (args.hostnames !== undefined) parts.push("hostnames: " + renderMemQLValue(args.hostnames));
  return "builtin packageDeploy(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    packageDeploy(args: PackageDeployArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.packageDeploy = function (this: QueryClient, args: PackageDeployArgs = {} as PackageDeployArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("packageDeploy", buildPackageDeploy(args), opts);
};

/** Bring one of the caller's archived packages back to active (epic memql#4794, D10). No typed confirmation and no cascade: the package's sites keep whatever status they have, because restoring a source is not a decision to redeploy it. Returns {packageId, name, status}. */
export interface PackageRestoreArgs {
  /** The archived v1:platform:package row to restore. */
  packageId: string;
}

export function buildPackageRestore(args: PackageRestoreArgs): string {
  const parts: string[] = [];
  parts.push("packageId: " + renderMemQLValue(args.packageId));
  return "builtin packageRestore(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    packageRestore(args: PackageRestoreArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.packageRestore = function (this: QueryClient, args: PackageRestoreArgs = {} as PackageRestoreArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("packageRestore", buildPackageRestore(args), opts);
};

/** Restore a package to what an earlier successful deployment left live (epic memql#4794, D7). Executes the D6 order REVERSED -- every site is pointed back at its recorded bundle version FIRST, then the active-set pointer goes back and the cluster rolls -- so the app stops using the old schema before the schema changes, which is the window the forward order closes in the other direction. Restores a tuple recorded on the prior row rather than replaying events, which is why the timeline is append-only. Rolling back to a deployment that carried DSL requires the cluster-owner actor. Returns {restored}. */
export interface PackageRollbackArgs {
  /** The v1:platform:package to roll back. */
  packageId: string;
  /** The earlier v1:platform:packageDeployment whose state to restore. Must have finished as succeeded. */
  deploymentId: string;
}

export function buildPackageRollback(args: PackageRollbackArgs): string {
  const parts: string[] = [];
  parts.push("packageId: " + renderMemQLValue(args.packageId));
  parts.push("deploymentId: " + renderMemQLValue(args.deploymentId));
  return "builtin packageRollback(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    packageRollback(args: PackageRollbackArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.packageRollback = function (this: QueryClient, args: PackageRollbackArgs = {} as PackageRollbackArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("packageRollback", buildPackageRollback(args), opts);
};

/** Turn a source's auto-deploy switch on or off (epic memql#4900, task memql#4903). With it ON, a push the update feeds notice starts a run by itself, requested by the package's owner and marked provenance='auto'; the run CONFIRMS ITSELF only when the new analysis plans exactly what the last confirmed run planned -- the same apps by name, kind and path, the same DSL domains, and every placement already remembered -- and parks at the confirm gate for anything else, which is the same gate a person's deploy passes. Never more than one auto-run is live per package. With it OFF, which is the default and the state of every source that has never been switched, a push lights the update chip and waits for a click, exactly as before. The write is owned: the guard admits the source's owner or a cluster owner. Returns {packageId, autoDeploy}. */
export interface PackageSetAutoDeployArgs {
  /** The v1:platform:package row to switch. */
  packageId: string;
  /** True arms it; false restores the click. */
  autoDeploy: boolean;
}

export function buildPackageSetAutoDeploy(args: PackageSetAutoDeployArgs): string {
  const parts: string[] = [];
  parts.push("packageId: " + renderMemQLValue(args.packageId));
  parts.push("autoDeploy: " + renderMemQLValue(args.autoDeploy));
  return "builtin packageSetAutoDeploy(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    packageSetAutoDeploy(args: PackageSetAutoDeployArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.packageSetAutoDeploy = function (this: QueryClient, args: PackageSetAutoDeployArgs = {} as PackageSetAutoDeployArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("packageSetAutoDeploy", buildPackageSetAutoDeploy(args), opts);
};

/** List every AI provider this NODE has registered: its vendor and model, whether this node can call it, which tier of the resolution chain supplied its credential (federation | globalSecret | globalVariable | env | unresolved), and -- when it cannot be called -- why not. Produced from the live provider registry, never persisted, and carrying no credential or fingerprint of one. Per-node on purpose: two replicas genuinely can disagree, and that disagreement is the most useful thing this read surfaces. Owner-only. */
export interface ProviderAuthStatusArgs {
}

export function buildProviderAuthStatus(args: ProviderAuthStatusArgs): string {
  void args;
  return "builtin providerAuthStatus()";
}

declare module "./query.js" {
  interface QueryClient {
    providerAuthStatus(args?: ProviderAuthStatusArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.providerAuthStatus = function (this: QueryClient, args: ProviderAuthStatusArgs = {} as ProviderAuthStatusArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("providerAuthStatus", buildProviderAuthStatus(args), opts);
};

/** Write Anthropic workload identity federation ids as v1:platform:globalVariable rows -- the recommended path, because no key is at rest anywhere: each pod exchanges its own projected token for a short-lived bearer. Plaintext rows are correct here; none of these five is a credential. All-or-none is enforced BEFORE the write (the workspace id excepted, which Anthropic needs only for a multi-workspace rule): a partial set refuses BOOT, so accepting one here would take the fleet down at its next restart, hours from the save that caused it. Owner-only. */
export interface ProviderFederationSetArgs {
  /** The OIDC federation rule id (fdrl_...) the token exchange names. */
  ruleId?: string;
  /** UUID of the Anthropic organization the rule belongs to. */
  organizationId?: string;
  /** The service account the rule maps this cluster onto. */
  serviceAccountId?: string;
  /** Optional. Anthropic requires it only when a rule spans more than one workspace, so it is outside the all-or-none set. */
  workspaceId?: string;
  /** Path to the pod's projected Kubernetes token, mounted for the Anthropic audience. */
  identityTokenFile?: string;
}

export function buildProviderFederationSet(args: ProviderFederationSetArgs): string {
  const parts: string[] = [];
  if (args.ruleId !== undefined) parts.push("ruleId: " + renderMemQLValue(args.ruleId));
  if (args.organizationId !== undefined) parts.push("organizationId: " + renderMemQLValue(args.organizationId));
  if (args.serviceAccountId !== undefined) parts.push("serviceAccountId: " + renderMemQLValue(args.serviceAccountId));
  if (args.workspaceId !== undefined) parts.push("workspaceId: " + renderMemQLValue(args.workspaceId));
  if (args.identityTokenFile !== undefined) parts.push("identityTokenFile: " + renderMemQLValue(args.identityTokenFile));
  return "builtin providerFederationSet(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    providerFederationSet(args: ProviderFederationSetArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.providerFederationSet = function (this: QueryClient, args: ProviderFederationSetArgs = {} as ProviderFederationSetArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("providerFederationSet", buildProviderFederationSet(args), opts);
};

/** Seal one vendor API key into a v1:platform:globalSecret row, under the exact name the auth resolver tries. WRITE-ONLY: the reply carries the row name and a fingerprint, never the value, and no read-back call exists. The VENDOR is the argument rather than the row name, so an operator cannot mistype a name the resolver never tries and watch a correctly-entered key do nothing. Does NOT reload -- seeding and applying are separate acts, so a mistyped key cannot take the fleet down as it is saved. Owner-only. */
export interface ProviderKeySetArgs {
  /** Which vendor the key belongs to: anthropic or openai. */
  vendor: string;
  /** The key itself. Trimmed, refused when empty, sealed with the cluster master key before it touches a row, and never returned. */
  apiKey: string;
}

export function buildProviderKeySet(args: ProviderKeySetArgs): string {
  const parts: string[] = [];
  parts.push("vendor: " + renderMemQLValue(args.vendor));
  parts.push("apiKey: " + renderMemQLValue(args.apiKey));
  return "builtin providerKeySet(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    providerKeySet(args: ProviderKeySetArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.providerKeySet = function (this: QueryClient, args: ProviderKeySetArgs = {} as ProviderKeySetArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("providerKeySet", buildProviderKeySet(args), opts);
};

/** Make ONE authenticated, token-free call to a provider's vendor and report whether the credential THIS node resolved was accepted. Lists models -- the cheapest authenticated request either vendor serves -- so it can be pressed as often as an operator likes without spending inference. A rejected key is an ANSWER (verified=false with the vendor's reason), not an error. Owner-only. */
export interface ProviderVerifyArgs {
  /** The registered provider entry to verify, by name. */
  provider: string;
}

export function buildProviderVerify(args: ProviderVerifyArgs): string {
  const parts: string[] = [];
  parts.push("provider: " + renderMemQLValue(args.provider));
  return "builtin providerVerify(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    providerVerify(args: ProviderVerifyArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.providerVerify = function (this: QueryClient, args: ProviderVerifyArgs = {} as ProviderVerifyArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("providerVerify", buildProviderVerify(args), opts);
};

/** Re-resolve AI provider credentials from the graph on EVERY node, so a key seeded through the portal takes effect fleet-wide with no restart. Reloads this node synchronously and broadcasts the same request over the mesh; each node builds a replacement registry fully and swaps it in atomically, so in-flight calls are unaffected and a node that cannot build one keeps what it had. Writes a providers_reloaded audit line naming who asked. Owner-only. */
export interface ProvidersReloadArgs {
  /** Ties every node's log line back to one Apply. Generated when omitted. */
  requestId?: string;
}

export function buildProvidersReload(args: ProvidersReloadArgs): string {
  const parts: string[] = [];
  if (args.requestId !== undefined) parts.push("requestId: " + renderMemQLValue(args.requestId));
  return "builtin providersReload(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    providersReload(args: ProvidersReloadArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.providersReload = function (this: QueryClient, args: ProvidersReloadArgs = {} as ProvidersReloadArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("providersReload", buildProvidersReload(args), opts);
};

/** Recall top-k memories of a concept (default v1:harness:observation) by a SINGLE hybrid recency x relevance score: pgvector cosine similarity + exponential time-decay over createdAt, scored and ordered server-side in one SQL statement against the MemoryNodes hypertable (no app-side merge). Owner-scoped (partition isolation); window prunes hypertable chunks; halfLife + wSem/wRec are tunable. Numeric tuning args ride additionalProperties. */
export interface RecallArgs {
  text: string;
  concept?: string;
  k?: number;
  provider?: string;
}

export function buildRecall(args: RecallArgs): string {
  const parts: string[] = [];
  parts.push("text: " + renderMemQLValue(args.text));
  if (args.concept !== undefined) parts.push("concept: " + renderMemQLValue(args.concept));
  if (args.k !== undefined) parts.push("k: " + renderMemQLValue(args.k));
  if (args.provider !== undefined) parts.push("provider: " + renderMemQLValue(args.provider));
  return "builtin recall(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    recall(args: RecallArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.recall = function (this: QueryClient, args: RecallArgs = {} as RecallArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("recall", buildRecall(args), opts);
};

/** Cut a new release of MemQL: compute the next version from the repository's existing vX.Y.Z tags, create the tag at main's head, and publish a GitHub Release -- which is what fires the image-build cascade. Owner role only, enforced in Go before any network call. Returns the version, the Release URL and the base sha. Requires MEMQL_RELEASE_REPO and the MEMQL_GITHUB_RELEASE_TOKEN credential. */
export interface ReleaseCutArgs {
  /** Which part of the newest existing version to increment. major and minor zero the parts below them. */
  // Enum: major | minor | patch
  bump: string;
  /** Optional prose prepended to the Release body. GitHub's generated release notes are appended either way, so leaving this empty still produces a populated Release. */
  notes?: string;
  /** Also open a pull request bumping the VS Code extension's DEFAULT_STACK_TAG to the new tag. A PR that cannot be opened is recorded as a note on the release row and never fails the cut, which has already published by then. */
  bumpExtensionPin?: boolean;
  /** Compute the plan -- next version and base sha -- and write nothing, create nothing, publish nothing. The first validation of a freshly seeded credential should use this. */
  dryRun?: boolean;
}

export function buildReleaseCut(args: ReleaseCutArgs): string {
  const parts: string[] = [];
  parts.push("bump: " + renderMemQLValue(args.bump));
  if (args.notes !== undefined) parts.push("notes: " + renderMemQLValue(args.notes));
  if (args.bumpExtensionPin !== undefined) parts.push("bumpExtensionPin: " + renderMemQLValue(args.bumpExtensionPin));
  if (args.dryRun !== undefined) parts.push("dryRun: " + renderMemQLValue(args.dryRun));
  return "builtin releaseCut(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    releaseCut(args: ReleaseCutArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.releaseCut = function (this: QueryClient, args: ReleaseCutArgs = {} as ReleaseCutArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("releaseCut", buildReleaseCut(args), opts);
};

/** Check whether the container images for a cut version actually exist yet, by asking GHCR for their manifests. Answers about the ARTIFACT rather than the workflow run: a build can fail after the Release publishes, and only the registry knows. All present moves the row to images_available; any absent leaves it dispatched; a check that errored reports the error and changes nothing. On demand only -- there is no poller. */
export interface ReleaseCutStatusArgs {
  /** The version to check, in either tag form (v1.2.3) or bare form (1.2.3). */
  version: string;
}

export function buildReleaseCutStatus(args: ReleaseCutStatusArgs): string {
  const parts: string[] = [];
  parts.push("version: " + renderMemQLValue(args.version));
  return "builtin releaseCutStatus(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    releaseCutStatus(args: ReleaseCutStatusArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.releaseCutStatus = function (this: QueryClient, args: ReleaseCutStatusArgs = {} as ReleaseCutStatusArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("releaseCutStatus", buildReleaseCutStatus(args), opts);
};

/** Restore a Library document to an earlier version by APPENDING a new latest version equal to the chosen one (memql#1230). Forward-only and non-destructive: history is never deleted; the restore lands as a new version (authorKind=system) with note 'restored from vN'. ownerUserId is threaded from the document row. */
export interface RestoreDocumentVersionArgs {
  documentId: string;
  versionId: string;
  authorId?: string;
}

export function buildRestoreDocumentVersion(args: RestoreDocumentVersionArgs): string {
  const parts: string[] = [];
  parts.push("documentId: " + renderMemQLValue(args.documentId));
  parts.push("versionId: " + renderMemQLValue(args.versionId));
  if (args.authorId !== undefined) parts.push("authorId: " + renderMemQLValue(args.authorId));
  return "builtin restoreDocumentVersion(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    restoreDocumentVersion(args: RestoreDocumentVersionArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.restoreDocumentVersion = function (this: QueryClient, args: RestoreDocumentVersionArgs = {} as RestoreDocumentVersionArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("restoreDocumentVersion", buildRestoreDocumentVersion(args), opts);
};

/** searchActions wraps the builtin named "searchActions". */
export interface SearchActionsArgs {
  text: string;
  k?: number;
  provider?: string;
}

export function buildSearchActions(args: SearchActionsArgs): string {
  const parts: string[] = [];
  parts.push("text: " + renderMemQLValue(args.text));
  if (args.k !== undefined) parts.push("k: " + renderMemQLValue(args.k));
  if (args.provider !== undefined) parts.push("provider: " + renderMemQLValue(args.provider));
  return "builtin searchActions(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    searchActions(args: SearchActionsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.searchActions = function (this: QueryClient, args: SearchActionsArgs = {} as SearchActionsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("searchActions", buildSearchActions(args), opts);
};

/** Register every mirrored webhook topic for every ingesting store at the pinned API version, update the ones whose URL, version or includeFields have drifted, and remove ours the allowlist no longer wants. Shopify deletes a subscription after eight consecutive delivery failures, so this is what brings a store back after an outage. Records the outcome on each store's health. */
export interface ShopifyEnsureSubscriptionsArgs {
}

export function buildShopifyEnsureSubscriptions(args: ShopifyEnsureSubscriptionsArgs): string {
  void args;
  return "builtin shopifyEnsureSubscriptions()";
}

declare module "./query.js" {
  interface QueryClient {
    shopifyEnsureSubscriptions(args?: ShopifyEnsureSubscriptionsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.shopifyEnsureSubscriptions = function (this: QueryClient, args: ShopifyEnsureSubscriptionsArgs = {} as ShopifyEnsureSubscriptionsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("shopifyEnsureSubscriptions", buildShopifyEnsureSubscriptions(args), opts);
};

/** Read a mirrored Shopify product by GID or handle. Answers from the mirror, so it costs no Admin API call and no cost points. Tokens never appear in the reply. */
export interface ShopifyFetchProductArgs {
  storeId?: string;
  id?: string;
  handle?: string;
}

export function buildShopifyFetchProduct(args: ShopifyFetchProductArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  if (args.id !== undefined) parts.push("id: " + renderMemQLValue(args.id));
  if (args.handle !== undefined) parts.push("handle: " + renderMemQLValue(args.handle));
  return "builtin shopifyFetchProduct(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    shopifyFetchProduct(args: ShopifyFetchProductArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.shopifyFetchProduct = function (this: QueryClient, args: ShopifyFetchProductArgs = {} as ShopifyFetchProductArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("shopifyFetchProduct", buildShopifyFetchProduct(args), opts);
};

/** Run the queued privacy jobs whose hold has elapsed: export a customer's data to the Library, scrub a redacted customer's PII across every version, purge a redacted shop's whole mirror. Every action is audited; shop/redact re-checks reachability first so a reverted uninstall does not cost the mirror. */
export interface ShopifyRunComplianceJobsArgs {
}

export function buildShopifyRunComplianceJobs(args: ShopifyRunComplianceJobsArgs): string {
  void args;
  return "builtin shopifyRunComplianceJobs()";
}

declare module "./query.js" {
  interface QueryClient {
    shopifyRunComplianceJobs(args?: ShopifyRunComplianceJobsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.shopifyRunComplianceJobs = function (this: QueryClient, args: ShopifyRunComplianceJobsArgs = {} as ShopifyRunComplianceJobsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("shopifyRunComplianceJobs", buildShopifyRunComplianceJobs(args), opts);
};

/** Report every configured store's status, granted-versus-needed scopes, subscription reconcile time, cost-bucket state and per-domain sync state with drift counters. The read behind the portal's Stores page. */
export interface ShopifyStoreHealthArgs {
  storeId?: string;
}

export function buildShopifyStoreHealth(args: ShopifyStoreHealthArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  return "builtin shopifyStoreHealth(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    shopifyStoreHealth(args: ShopifyStoreHealthArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.shopifyStoreHealth = function (this: QueryClient, args: ShopifyStoreHealthArgs = {} as ShopifyStoreHealthArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("shopifyStoreHealth", buildShopifyStoreHealth(args), opts);
};

/** Run an ad-hoc ShopifyQL analytics query for questions the mirror cannot answer. Requires read_reports and protected-customer-data Level 2 approval; refused below that with a reason naming the level, which Shopify's own 403 does not. */
export interface ShopifyqlArgs {
  storeId?: string;
  query?: string;
}

export function buildShopifyql(args: ShopifyqlArgs): string {
  const parts: string[] = [];
  if (args.storeId !== undefined) parts.push("storeId: " + renderMemQLValue(args.storeId));
  if (args.query !== undefined) parts.push("query: " + renderMemQLValue(args.query));
  return "builtin shopifyql(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    shopifyql(args: ShopifyqlArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.shopifyql = function (this: QueryClient, args: ShopifyqlArgs = {} as ShopifyqlArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("shopifyql", buildShopifyql(args), opts);
};

/** Archive one of the caller's sites (epic memql#4794, D10). Refuses unless the site is already DISABLED -- archiving is the end of a lifecycle, not a shortcut past pausing -- and unless confirmHostname matches the site's stored hostname exactly, which is the typed confirmation the OS renders and this server verifies. A systemOwned site (the cluster's own portal and OS) is refused outright: those rows are exempt from the lifecycle entirely. An archived site stops serving (404) but stays listed behind the Archived filter, because an archive is a place and not a void. Returns {siteId, hostname, status}. Refusals carry stable codes. */
export interface SiteArchiveArgs {
  /** The v1:platform:site row to archive. */
  siteId: string;
  /** The site's own hostname, typed by the person as confirmation. Compared against the stored value; a mismatch refuses and writes nothing. */
  confirmHostname: string;
}

export function buildSiteArchive(args: SiteArchiveArgs): string {
  const parts: string[] = [];
  parts.push("siteId: " + renderMemQLValue(args.siteId));
  parts.push("confirmHostname: " + renderMemQLValue(args.confirmHostname));
  return "builtin siteArchive(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    siteArchive(args: SiteArchiveArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.siteArchive = function (this: QueryClient, args: SiteArchiveArgs = {} as SiteArchiveArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("siteArchive", buildSiteArchive(args), opts);
};

/** Deploy a Library zip artifact to one of the caller's hosted sites (memql#4345). The caller must own the site (or be a cluster owner) AND own the artifact, which must be a Library file whose MIME type is a zip. The bundle is read from object storage and validated -- index.html at the ROOT for spa and shopify_storefront, plus the same per-file (25 MB), whole-bundle (500 MB) and file-count (20000) limits POST /sites/{id}/bundles enforces -- then written under a new content-addressed version prefix before bundleRef is flipped, so a failed publish leaves the site serving exactly what it was serving. artifactId is stamped on the site row as provenance and the attempt is recorded on the security audit log. Returns {siteId, artifactId, fileId, version, bundleRef, fileCount, totalBytes}. Rollback is unchanged: updateSiteBundle pointed back at an earlier version's bundleRef. */
export interface SitePublishFromArtifactArgs {
  /** The v1:platform:site row to publish to. */
  siteId: string;
  /** The v1:library:artifact index row of the zip to deploy. */
  artifactId: string;
}

export function buildSitePublishFromArtifact(args: SitePublishFromArtifactArgs): string {
  const parts: string[] = [];
  parts.push("siteId: " + renderMemQLValue(args.siteId));
  parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  return "builtin sitePublishFromArtifact(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    sitePublishFromArtifact(args: SitePublishFromArtifactArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.sitePublishFromArtifact = function (this: QueryClient, args: SitePublishFromArtifactArgs = {} as SitePublishFromArtifactArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("sitePublishFromArtifact", buildSitePublishFromArtifact(args), opts);
};

/** Bring one of the caller's archived sites back to DISABLED (epic memql#4794, D10). Deliberately not back to live: restoring returns a site to the state it was archived from, and publishing it again is a separate, visible decision. No typed confirmation, because leaving the archive destroys nothing. Returns {siteId, hostname, status}. */
export interface SiteRestoreArgs {
  /** The archived v1:platform:site row to restore. */
  siteId: string;
}

export function buildSiteRestore(args: SiteRestoreArgs): string {
  const parts: string[] = [];
  parts.push("siteId: " + renderMemQLValue(args.siteId));
  return "builtin siteRestore(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    siteRestore(args: SiteRestoreArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.siteRestore = function (this: QueryClient, args: SiteRestoreArgs = {} as SiteRestoreArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("siteRestore", buildSiteRestore(args), opts);
};

