// Code generated by scripts/sdk-gen. DO NOT EDIT.
// Source of truth: dsl/**/*.memql.

import { QueryClient, type QueryCallOptions } from "./query.js";
import type { Result } from "./types.js";
import { renderMemQLValue } from "./memqlValue.js";

/** Pause a running campaign send. The delivery ledger is untouched, so resuming continues exactly where it stopped -- 'where it stopped' is the set of recipients with no delivery row, not a cursor that could go stale. */
export interface CampaignPauseSendArgs {
  /** The campaign to pause. The caller must own it. */
  campaignId: string;
}

export function buildCampaignPauseSend(args: CampaignPauseSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignPauseSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignPauseSend(args: CampaignPauseSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignPauseSend = function (this: QueryClient, args: CampaignPauseSendArgs = {} as CampaignPauseSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignPauseSend", buildCampaignPauseSend(args), opts);
};

/** Resume a paused campaign send. Does not re-stamp startedAt: the gap between startedAt and completedAt is how long the run took, and resetting it on resume would erase the pause it exists to reveal. */
export interface CampaignResumeSendArgs {
  /** The campaign to resume. The caller must own it. */
  campaignId: string;
}

export function buildCampaignResumeSend(args: CampaignResumeSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignResumeSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignResumeSend(args: CampaignResumeSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignResumeSend = function (this: QueryClient, args: CampaignResumeSendArgs = {} as CampaignResumeSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignResumeSend", buildCampaignResumeSend(args), opts);
};

/** Commit a campaign to a time and enqueue the send job that will fire at it (memql#3459). Runs the SAME preflight as campaignStartSend -- sender registered, one-click unsubscribe configured, template marked ready, audience non-empty and inside the ceiling -- because the whole value of scheduling is finding out now rather than at 3am. The job it writes is inert: it sits in the 'scheduled' status until the drain worker sees that the campaign's scheduledAt has passed, and the campaign row is the authority on that time, so moving the date with updateCampaign moves the send. A time in the past is refused; use campaignStartSend to send now. Authorization is the owned-tier read of the campaign, exactly as for starting one by hand. */
export interface CampaignScheduleSendArgs {
  /** The campaign to schedule. The caller must own it. */
  campaignId: string;
  /** When the send should begin, RFC 3339 (e.g. 2026-08-14T09:00:00Z). Interpreted as an instant, not a local wall clock -- a value with no offset is read as UTC. */
  scheduledAt: string;
}

export function buildCampaignScheduleSend(args: CampaignScheduleSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  parts.push("scheduledAt: " + renderMemQLValue(args.scheduledAt));
  return "builtin campaignScheduleSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignScheduleSend(args: CampaignScheduleSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignScheduleSend = function (this: QueryClient, args: CampaignScheduleSendArgs = {} as CampaignScheduleSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignScheduleSend", buildCampaignScheduleSend(args), opts);
};

/** Preflight and start a campaign send. Refuses -- rather than partially sending -- when no email sender is registered on the node, when one-click unsubscribe is not configured (MEMQL_CAMPAIGNS_UNSUBSCRIBE_SECRET / _BASE_URL), when the template is not marked ready, or when the audience is empty or at the MEMQL_CAMPAIGNS_MAX_AUDIENCE ceiling. Authorization is the owned-tier read of the campaign: a caller who cannot read it cannot start it. Returns the recipient count the send will work through. */
export interface CampaignStartSendArgs {
  /** The campaign to send. The caller must own it. */
  campaignId: string;
}

export function buildCampaignStartSend(args: CampaignStartSendArgs): string {
  const parts: string[] = [];
  parts.push("campaignId: " + renderMemQLValue(args.campaignId));
  return "builtin campaignStartSend(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    campaignStartSend(args: CampaignStartSendArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.campaignStartSend = function (this: QueryClient, args: CampaignStartSendArgs = {} as CampaignStartSendArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("campaignStartSend", buildCampaignStartSend(args), opts);
};

/** Append a new version of a Library document with new content. Reads the current latest version, computes the next versionNumber + parentVersionId, appends an immutable v1:library:documentVersion snapshot (authorKind=user|assistant) and re-inserts the backing generatedOutput so the Library viewer reflects the edit. Optimistic concurrency via expectedVersion. ownerUserId is threaded from the document row, never the caller. Backs both the user edit (memql#1229) and the assistant editDocument tool (memql#1231). */
export interface EditDocumentArgs {
  documentId: string;
  content?: string;
  attachmentId?: string;
  note?: string;
  // Enum: user | assistant | system
  authorKind?: string;
  authorId?: string;
  expectedVersion?: number;
  producedByPlanId?: string;
  partitionId?: string;
}

export function buildEditDocument(args: EditDocumentArgs): string {
  const parts: string[] = [];
  parts.push("documentId: " + renderMemQLValue(args.documentId));
  if (args.content !== undefined) parts.push("content: " + renderMemQLValue(args.content));
  if (args.attachmentId !== undefined) parts.push("attachmentId: " + renderMemQLValue(args.attachmentId));
  if (args.note !== undefined) parts.push("note: " + renderMemQLValue(args.note));
  if (args.authorKind !== undefined) parts.push("authorKind: " + renderMemQLValue(args.authorKind));
  if (args.authorId !== undefined) parts.push("authorId: " + renderMemQLValue(args.authorId));
  if (args.expectedVersion !== undefined) parts.push("expectedVersion: " + renderMemQLValue(args.expectedVersion));
  if (args.producedByPlanId !== undefined) parts.push("producedByPlanId: " + renderMemQLValue(args.producedByPlanId));
  if (args.partitionId !== undefined) parts.push("partitionId: " + renderMemQLValue(args.partitionId));
  return "builtin editDocument(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    editDocument(args: EditDocumentArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.editDocument = function (this: QueryClient, args: EditDocumentArgs = {} as EditDocumentArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("editDocument", buildEditDocument(args), opts);
};

/** Fetch a harness plan's full execution timeline (every plan/step version transition + all observations, ordered by createdAt) reconstructed from the append-only graph event stream. Returns one synthetic node carrying the rendered timeline string, a completion flag, and the step count. Owner-scoped to the caller's own plan. The history-over-gRPC contract for the cockpit `harness trace` CLI (memql-cockpit#142). */
export interface HarnessTraceArgs {
  planId: string;
}

export function buildHarnessTrace(args: HarnessTraceArgs): string {
  const parts: string[] = [];
  parts.push("planId: " + renderMemQLValue(args.planId));
  return "builtin harnessTrace(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    harnessTrace(args: HarnessTraceArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.harnessTrace = function (this: QueryClient, args: HarnessTraceArgs = {} as HarnessTraceArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("harnessTrace", buildHarnessTrace(args), opts);
};

/** Report this node's integration registry: every plug-in the running binary registered, and for the email integration the resolved sender mode plus a slot-by-slot account of which settings and credentials are configured and where each came from. Credential VALUES are never included -- only presence, source and (for stored secrets) a fingerprint. Pass probe=true to additionally run a live, non-sending reachability check (Microsoft Graph: acquire a client-credentials token; SMTP: connect, EHLO, STARTTLS, AUTH, QUIT) and report its verdict; probe=false (the default) answers the configuration question only. */
export interface IntegrationStatusArgs {
  probe?: boolean;
}

export function buildIntegrationStatus(args: IntegrationStatusArgs): string {
  const parts: string[] = [];
  if (args.probe !== undefined) parts.push("probe: " + renderMemQLValue(args.probe));
  return "builtin integrationStatus(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    integrationStatus(args: IntegrationStatusArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.integrationStatus = function (this: QueryClient, args: IntegrationStatusArgs = {} as IntegrationStatusArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("integrationStatus", buildIntegrationStatus(args), opts);
};

/** Decide whether a chat exchange's topic warrants augmenting one of an agent's knowledge domains. Returns {outcome, domainId, topic, reasoning, confidence}. Drives the chat 'Analyze for training' button preflight. */
export interface KnowledgeAugmentDomainAnalyzeArgs {
  userQuestion: string;
  agentResponse: string;
  domains: Record<string, unknown>[];
  retrieved?: Record<string, unknown>[];
}

export function buildKnowledgeAugmentDomainAnalyze(args: KnowledgeAugmentDomainAnalyzeArgs): string {
  const parts: string[] = [];
  parts.push("userQuestion: " + renderMemQLValue(args.userQuestion));
  parts.push("agentResponse: " + renderMemQLValue(args.agentResponse));
  parts.push("domains: " + renderMemQLValue(args.domains));
  if (args.retrieved !== undefined) parts.push("retrieved: " + renderMemQLValue(args.retrieved));
  return "builtin knowledgeAugmentDomainAnalyze(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    knowledgeAugmentDomainAnalyze(args: KnowledgeAugmentDomainAnalyzeArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.knowledgeAugmentDomainAnalyze = function (this: QueryClient, args: KnowledgeAugmentDomainAnalyzeArgs = {} as KnowledgeAugmentDomainAnalyzeArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("knowledgeAugmentDomainAnalyze", buildKnowledgeAugmentDomainAnalyze(args), opts);
};

/** Generate + embed + persist topic-focused chunks for a knowledge domain. Inserts a Plan row for audit. Returns {planId, chunksAdded, domainId, domainName, topic}. */
export interface KnowledgeAugmentDomainGenerateArgs {
  domainId: string;
  topic: string;
  sourceUtteranceId?: string;
  sourceAgentId?: string;
  partitionId: string;
  requestedBy: string;
}

export function buildKnowledgeAugmentDomainGenerate(args: KnowledgeAugmentDomainGenerateArgs): string {
  const parts: string[] = [];
  parts.push("domainId: " + renderMemQLValue(args.domainId));
  parts.push("topic: " + renderMemQLValue(args.topic));
  if (args.sourceUtteranceId !== undefined) parts.push("sourceUtteranceId: " + renderMemQLValue(args.sourceUtteranceId));
  if (args.sourceAgentId !== undefined) parts.push("sourceAgentId: " + renderMemQLValue(args.sourceAgentId));
  parts.push("partitionId: " + renderMemQLValue(args.partitionId));
  parts.push("requestedBy: " + renderMemQLValue(args.requestedBy));
  return "builtin knowledgeAugmentDomainGenerate(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    knowledgeAugmentDomainGenerate(args: KnowledgeAugmentDomainGenerateArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.knowledgeAugmentDomainGenerate = function (this: QueryClient, args: KnowledgeAugmentDomainGenerateArgs = {} as KnowledgeAugmentDomainGenerateArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("knowledgeAugmentDomainGenerate", buildKnowledgeAugmentDomainGenerate(args), opts);
};

/** Add a label to a Library artifact index row. Idempotent -- a label already present is left alone and nothing is written. artifactId is the v1:library:artifact row id; the load + write-back run under a synthetic actor derived from the row's own ownerUserId, so a caller can only ever label an artifact they own. */
export interface LibraryAddArtifactLabelArgs {
  artifactId: string;
  label: string;
}

export function buildLibraryAddArtifactLabel(args: LibraryAddArtifactLabelArgs): string {
  const parts: string[] = [];
  parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  parts.push("label: " + renderMemQLValue(args.label));
  return "builtin libraryAddArtifactLabel(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    libraryAddArtifactLabel(args: LibraryAddArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.libraryAddArtifactLabel = function (this: QueryClient, args: LibraryAddArtifactLabelArgs = {} as LibraryAddArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("libraryAddArtifactLabel", buildLibraryAddArtifactLabel(args), opts);
};

/** Remove a label from a Library artifact index row. Idempotent -- a label already absent is left alone and nothing is written. Same owner-threaded load/write shape as libraryAddArtifactLabel. */
export interface LibraryRemoveArtifactLabelArgs {
  artifactId: string;
  label: string;
}

export function buildLibraryRemoveArtifactLabel(args: LibraryRemoveArtifactLabelArgs): string {
  const parts: string[] = [];
  parts.push("artifactId: " + renderMemQLValue(args.artifactId));
  parts.push("label: " + renderMemQLValue(args.label));
  return "builtin libraryRemoveArtifactLabel(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    libraryRemoveArtifactLabel(args: LibraryRemoveArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.libraryRemoveArtifactLabel = function (this: QueryClient, args: LibraryRemoveArtifactLabelArgs = {} as LibraryRemoveArtifactLabelArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("libraryRemoveArtifactLabel", buildLibraryRemoveArtifactLabel(args), opts);
};

/** Recall top-k memories of a concept (default v1:harness:observation) by a SINGLE hybrid recency x relevance score: pgvector cosine similarity + exponential time-decay over createdAt, scored and ordered server-side in one SQL statement against the MemoryNodes hypertable (no app-side merge). Owner-scoped (partition isolation); window prunes hypertable chunks; halfLife + wSem/wRec are tunable. Numeric tuning args ride additionalProperties. */
export interface RecallArgs {
  text: string;
  concept?: string;
  k?: number;
  provider?: string;
}

export function buildRecall(args: RecallArgs): string {
  const parts: string[] = [];
  parts.push("text: " + renderMemQLValue(args.text));
  if (args.concept !== undefined) parts.push("concept: " + renderMemQLValue(args.concept));
  if (args.k !== undefined) parts.push("k: " + renderMemQLValue(args.k));
  if (args.provider !== undefined) parts.push("provider: " + renderMemQLValue(args.provider));
  return "builtin recall(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    recall(args: RecallArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.recall = function (this: QueryClient, args: RecallArgs = {} as RecallArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("recall", buildRecall(args), opts);
};

/** Restore a Library document to an earlier version by APPENDING a new latest version equal to the chosen one (memql#1230). Forward-only and non-destructive: history is never deleted; the restore lands as a new version (authorKind=system) with note 'restored from vN'. ownerUserId is threaded from the document row. */
export interface RestoreDocumentVersionArgs {
  documentId: string;
  versionId: string;
  authorId?: string;
}

export function buildRestoreDocumentVersion(args: RestoreDocumentVersionArgs): string {
  const parts: string[] = [];
  parts.push("documentId: " + renderMemQLValue(args.documentId));
  parts.push("versionId: " + renderMemQLValue(args.versionId));
  if (args.authorId !== undefined) parts.push("authorId: " + renderMemQLValue(args.authorId));
  return "builtin restoreDocumentVersion(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    restoreDocumentVersion(args: RestoreDocumentVersionArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.restoreDocumentVersion = function (this: QueryClient, args: RestoreDocumentVersionArgs = {} as RestoreDocumentVersionArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("restoreDocumentVersion", buildRestoreDocumentVersion(args), opts);
};

/** searchActions wraps the builtin named "searchActions". */
export interface SearchActionsArgs {
  text: string;
  k?: number;
  provider?: string;
}

export function buildSearchActions(args: SearchActionsArgs): string {
  const parts: string[] = [];
  parts.push("text: " + renderMemQLValue(args.text));
  if (args.k !== undefined) parts.push("k: " + renderMemQLValue(args.k));
  if (args.provider !== undefined) parts.push("provider: " + renderMemQLValue(args.provider));
  return "builtin searchActions(" + parts.join(", ") + ")";
}

declare module "./query.js" {
  interface QueryClient {
    searchActions(args: SearchActionsArgs, opts?: QueryCallOptions): Promise<Result>;
  }
}

QueryClient.prototype.searchActions = function (this: QueryClient, args: SearchActionsArgs = {} as SearchActionsArgs, opts?: QueryCallOptions): Promise<Result> {
  return this.executeNamed("searchActions", buildSearchActions(args), opts);
};

