import { escapeHTML } from "./markdown.js";

const icon = (path: string) => `<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
const source = icon('<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-14-2 16"/>');
const reading = icon('<path d="M4 3h11l5 5v13H4zM14 3v6h6M8 13h8M8 17h6"/>');
const split = icon('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16"/>');
const feedback = icon('<path d="M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-6 4V6a2 2 0 0 1 2-2zM7 9h10M7 13h7"/>');
const review = icon('<path d="M9 5h11M9 12h11M9 19h11m-17-14 1 1 2-2m-3 8 1 1 2-2m-3 8 1 1 2-2"/>');
const plus = icon('<path d="M12 5v14M5 12h14"/>');
const close = icon('<path d="m6 6 12 12M6 18 18 6"/>');
const arrow = icon('<path d="M5 12h14m-6-6 6 6-6 6"/>');

/** The host supplies the same theme tokens on desktop and in the browser. */
export function markdownPage(title: string, script: string, nonce: string): string {
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; img-src 'none'; form-action 'none'; base-uri 'none'"><title>${escapeHTML(title)}</title><style>
 *{box-sizing:border-box}body{margin:0;color:var(--vscode-editor-foreground);background:var(--vscode-editor-background);font:var(--vscode-font-size,13px)/1.6 var(--vscode-font-family,system-ui)}[hidden]{display:none!important}button,textarea{font:inherit}button{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:34px;padding:6px 12px;border:1px solid transparent;border-radius:6px;color:inherit;background:transparent;cursor:pointer}button:hover{background:var(--vscode-toolbar-hoverBackground)}button:disabled{opacity:.45;cursor:default}button:focus-visible,textarea:focus-visible,summary:focus-visible,input:focus-visible{outline:2px solid var(--vscode-focusBorder);outline-offset:2px}button svg{flex-shrink:0}.icon-button{padding:8px;width:34px;height:34px}.primary{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border-color:var(--vscode-button-border,transparent)}.primary:hover{background:var(--vscode-button-hoverBackground)}.secondary{border-color:var(--vscode-panel-border)}.muted,small{color:var(--vscode-descriptionForeground)}button[aria-pressed="true"]{background:var(--vscode-toolbar-activeBackground,var(--vscode-list-inactiveSelectionBackground))}
 .toolbar{position:sticky;top:0;z-index:2;display:flex;justify-content:center;padding:10px 20px;background:var(--vscode-editor-background);border-bottom:1px solid var(--vscode-panel-border)}.views{display:inline-flex;gap:2px;padding:3px;border:1px solid var(--vscode-panel-border);border-radius:9px}.views button{min-width:75px}
 main{max-width:860px;margin:0 auto;padding:40px 72px 72px}#content{font-size:15px;line-height:1.85;overflow-wrap:anywhere}#content:focus{outline:none}#content h1{font-size:2em;line-height:1.25;letter-spacing:-.03em;margin:0 0 1em}#content h2{font-size:1.5em;line-height:1.4;margin-top:1.8em;letter-spacing:-.015em}#content h3{font-size:1.2em;margin-top:1.5em}#content p{margin:0 0 1.25em}#content a{color:var(--vscode-textLink-foreground)}#content pre{overflow:auto;padding:16px;border-radius:8px;background:var(--vscode-textCodeBlock-background)}code,pre{font-family:var(--vscode-editor-font-family,monospace)}#content table{border-collapse:collapse;max-width:100%;display:block;overflow:auto}#content td,#content th{padding:8px 12px;border:1px solid var(--vscode-panel-border)}blockquote{margin:0;padding:8px 12px;border-left:2px solid var(--vscode-focusBorder);color:var(--vscode-descriptionForeground)}#content blockquote{margin:20px 0}#content hr{border:0;border-top:1px solid var(--vscode-panel-border);margin:32px 0}
 .document-end{margin-top:40px;padding-top:20px;border-top:1px solid var(--vscode-panel-border);display:flex;align-items:center;gap:12px}.document-end button{border:1px solid var(--vscode-panel-border)}.document-end small{font-size:12px}
 .floating{background:var(--vscode-editorWidget-background,var(--vscode-editor-background));border:1px solid var(--vscode-widget-border,var(--vscode-panel-border));box-shadow:0 8px 30px var(--vscode-widget-shadow,rgba(0,0,0,.16));border-radius:10px}.review-tools{position:fixed;right:16px;top:100px;z-index:3;display:flex;flex-direction:column;gap:4px;padding:5px}.review-tools button{position:relative}.badge{position:absolute;right:-3px;top:-3px;min-width:16px;height:16px;padding:0 3px;line-height:16px;font-size:10px;border-radius:8px;background:var(--vscode-badge-background);color:var(--vscode-badge-foreground)}#selection-tools{position:fixed;z-index:5;padding:3px}#selection-tools button{font-size:12px;min-height:30px}
 #composer{position:fixed;z-index:6;width:360px;max-width:calc(100vw - 32px);padding:16px}h2{font-size:14px;line-height:1.4;margin:0;font-weight:600}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.panel-head .icon-button{margin:-6px -6px -6px 0}#selected{font-size:12px;line-height:1.6;max-height:90px;overflow:auto;white-space:pre-wrap;margin-bottom:12px}textarea{display:block;width:100%;resize:vertical;min-height:98px;max-height:220px;padding:10px 12px;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border,var(--vscode-panel-border));border-radius:6px;line-height:1.6}textarea::placeholder{color:var(--vscode-input-placeholderForeground)}.composer-actions{display:flex;align-items:center;justify-content:space-between;margin-top:12px}.composer-actions small{font-size:11px}#composer-status{font-size:12px;color:var(--vscode-errorForeground);margin-top:8px}#composer-status:empty{display:none}
 #content h1,#content h2,#content h3,#content h4,#content h5,#content h6,.document-end{scroll-margin-top:88px}.section-extend{vertical-align:middle;margin-left:8px;opacity:.45}.section-extend:hover,.section-extend:focus-visible{opacity:1}
 body.review-open main{width:calc(100% - 432px);margin-right:432px;padding-left:36px;padding-right:36px}
 #review-panel{position:fixed;right:16px;top:76px;bottom:16px;z-index:4;width:400px;max-width:calc(100vw - 32px);display:flex;flex-direction:column;overflow:hidden}#review-panel>.panel-head{padding:18px 20px 12px;margin:0;border-bottom:1px solid var(--vscode-panel-border)}.review-scroll{display:flex;flex-direction:column;overflow:auto;flex:1;min-height:0;padding:0 20px 20px;overscroll-behavior:contain}.review-scroll>section{flex-shrink:0}#revision{order:0}#comments{order:1}.review-draft #comments{order:0}.review-draft #revision{order:1}.review-footer{padding:16px 20px;border-top:1px solid var(--vscode-panel-border)}.review-footer .primary{width:100%}#status{order:-1;font-size:12px;margin:12px 0;color:var(--vscode-descriptionForeground)}#status:empty{display:none}
 #review-panel h3{font-size:14px;line-height:1.5;margin:20px 0 8px}.request-help{font-size:12px;margin:0 0 4px}.note{padding:16px 0}.note+.note{border-top:1px solid var(--vscode-panel-border)}.note-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;font-size:12px;color:var(--vscode-descriptionForeground)}.note-location{display:flex;flex-direction:column;align-items:flex-start;min-width:0;gap:2px}.request-kind{font-weight:600;color:var(--vscode-editor-foreground)}.passage{padding:0;min-height:24px;font-size:12px;text-align:left;justify-content:flex-start;color:var(--vscode-textLink-foreground)}.passage:hover{text-decoration:underline;background:transparent}.include-toggle{flex-shrink:0;font-size:11px;color:var(--vscode-descriptionForeground);padding:2px 0 2px 8px;min-height:28px;gap:8px}.include-toggle:after{content:"";width:28px;height:16px;border:1px solid var(--vscode-panel-border);border-radius:10px;background:radial-gradient(circle at 7px 7px,var(--vscode-descriptionForeground) 4px,transparent 4.5px) var(--vscode-input-background)}.include-toggle[aria-checked="true"]:after{background:radial-gradient(circle at 19px 7px,var(--vscode-button-foreground) 4px,transparent 4.5px) var(--vscode-button-background)}.note p{margin:8px 0 0;white-space:pre-wrap;overflow-wrap:anywhere}.note.excluded>p{color:var(--vscode-descriptionForeground)}.request-quote{margin-top:8px;font-size:12px;color:var(--vscode-descriptionForeground)}summary{cursor:pointer}.request-quote blockquote{margin:8px 0 0;max-height:96px;overflow:auto}.empty{padding:24px 0;color:var(--vscode-descriptionForeground);font-size:13px}.optional-direction{margin-bottom:12px}.optional-direction summary{font-size:12px;color:var(--vscode-descriptionForeground)}.optional-direction textarea{margin-top:8px;min-height:66px}
 .phase{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--vscode-descriptionForeground)}.phase.busy:before{content:"";width:10px;height:10px;border:1.5px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spin 1s linear infinite}.review-error{color:var(--vscode-errorForeground);font-size:12px;overflow-wrap:anywhere}.proposal-summary{line-height:1.7;white-space:pre-wrap;font-size:12px;margin:16px 0;color:var(--vscode-descriptionForeground)}.change{margin:12px 0;border:1px solid var(--vscode-panel-border);border-radius:7px;overflow:hidden}.change>summary{padding:12px;font-size:13px;font-weight:600}.request-context{padding:0 12px 12px;font-size:13px}.request-context p{margin:0 0 4px;white-space:pre-wrap;overflow-wrap:anywhere}.change-reason{padding:10px 12px;font-size:12px;color:var(--vscode-descriptionForeground)}.change-reason p{margin:8px 0 0}.change .diff-label{padding:8px 12px 0;font-size:11px;font-weight:600}.change pre{margin:0;padding:6px 12px 12px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.65}.before{background:var(--vscode-diffEditor-removedTextBackground,rgba(200,60,60,.1))}.after{background:var(--vscode-diffEditor-insertedTextBackground,rgba(40,170,90,.1))}.revision-actions{display:flex;gap:8px;flex-wrap:wrap}.revision-actions .primary{flex:1}.review-footer .revision-actions .primary{width:auto}.compare{width:100%;font-size:12px;margin-top:4px}.earlier{margin-top:16px;font-size:12px;color:var(--vscode-descriptionForeground)}::highlight(memql-active){background:var(--vscode-editor-selectionBackground);color:var(--vscode-editor-selectionForeground)}::highlight(memql-notes){background:var(--vscode-editor-findMatchHighlightBackground);text-decoration:underline var(--vscode-focusBorder)}
 @media(max-width:999px){body.review-open main{width:auto;margin:0 auto;padding:28px 56px calc(48vh + 48px) 24px}body.review-open #review-panel{top:auto;height:48vh;right:8px;left:8px;bottom:8px;width:auto;max-width:none}#review-panel>.panel-head{padding:12px 16px 8px}.review-scroll{padding:0 16px 16px}.review-footer{padding:12px 16px}}
 @keyframes spin{to{transform:rotate(360deg)}}@media(max-width:600px){main{padding:28px 56px 40px 24px}.toolbar{padding:8px 16px}.views button{min-width:68px;padding:5px 8px}.review-tools{right:8px;top:88px}#review-panel{right:8px;top:68px;bottom:8px;max-width:calc(100vw - 16px)}#content{font-size:14px}.document-end{align-items:flex-start;flex-direction:column;gap:8px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important}}
 </style></head><body><header class="toolbar"><div class="views" role="group" aria-label="Markdown view"><button type="button" id="source" aria-label="Source view" title="Source view" aria-pressed="false">${source}<span>Source</span></button><button type="button" id="reading" aria-label="Reading view" title="Reading view" aria-pressed="true">${reading}<span>Read</span></button><button type="button" id="split" aria-label="Split view" title="Source and reading view side by side" aria-pressed="false">${split}<span>Split</span></button></div></header>
 <main><section id="content" aria-label="Rendered Markdown" tabindex="-1"></section><footer class="document-end"><button id="extend" disabled>${plus}Extend document</button></footer></main>
 <nav class="review-tools floating" aria-label="Document tools"><button id="annotate" class="icon-button" aria-label="Add feedback on selected text" title="Select text to add feedback" disabled>${feedback}</button><button id="review-toggle" class="icon-button" aria-label="Review feedback and proposed changes" title="Review feedback and proposed changes" aria-expanded="false" aria-controls="review-panel">${review}<span id="note-count" class="badge" hidden>0</span></button></nav>
 <div id="selection-tools" class="floating" role="toolbar" aria-label="Selection tools" hidden><button id="selection-feedback">${feedback}Feedback</button><button id="selection-extend">${plus}Extend</button></div>
 <section id="composer" class="floating" role="dialog" aria-labelledby="composer-title" hidden><div class="panel-head"><h2 id="composer-title">Add feedback</h2><button id="composer-close" class="icon-button" aria-label="Close feedback composer" title="Close">${close}</button></div><blockquote id="selected"></blockquote><textarea id="feedback" aria-label="Feedback" placeholder="Describe the change you’d like…" maxlength="16000"></textarea><div id="composer-status" role="alert"></div><div class="composer-actions"><small>⌘ / Ctrl + Enter to add</small><button id="add" class="primary" disabled>Add to review</button></div></section>
 <aside id="review-panel" class="floating" aria-label="Document review" hidden><div class="panel-head"><h2>Review</h2><button id="review-close" class="icon-button" aria-label="Close review" title="Close">${close}</button></div><div class="review-scroll"><div id="status" role="status" aria-live="polite"></div><section id="revision" aria-label="Proposed document changes"></section><section id="comments" aria-label="Saved feedback"></section></div><footer class="review-footer" id="review-footer"><div id="review-actions" class="revision-actions"></div><div id="review-submit"><details class="optional-direction"><summary>Additional direction</summary><textarea id="revision-instruction" aria-label="Additional direction" placeholder="Optional guidance for the whole review" maxlength="8000"></textarea></details><button id="prepare-revision" class="primary" disabled>Propose changes ${arrow}</button></div></footer></aside>
 <script nonce="${nonce}" src="${escapeHTML(script)}"></script></body></html>`;
}
