// scripts/restructure-by-construct/main.go reorganises dsl/<domain>/*.memql
// so that each construct kind lives in its own file:
//
//	dsl/<domain>/concepts.memql
//	dsl/<domain>/queries.memql
//	dsl/<domain>/mutations.memql
//	dsl/<domain>/shapes.memql
//	dsl/<domain>/specs.memql
//	dsl/<domain>/traits.memql
//	dsl/<domain>/automations.memql
//	dsl/<domain>/logic.memql
//	dsl/<domain>/builtins.memql
//	dsl/<domain>/tools.memql
//	dsl/<domain>/prompts.memql
//	dsl/<domain>/providers.memql
//	dsl/<domain>/policies.memql
//
// Each existing .memql file in a domain may carry multiple construct
// kinds today (a per-entity bundle holds concept + queries + mutations
// + shape + specs for the entity). The script extracts every top-level
// construct, preserves the @-attribute + comment preamble above it, and
// routes the slice to the target per-kind file.
//
// Files starting with `_` (e.g. _unsorted.memql) and .tmpl files are
// skipped. The `policies/` and `providers/` domains roll up to a single
// `policies.memql` / `providers.memql` file each.
//
// Run from the repo root:
//
//	go run ./scripts/restructure-by-construct
//
// The script is idempotent: re-running on an already-restructured tree
// is a no-op.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const dslRoot = "dsl"

// constructHeader matches every top-level construct declaration at
// column 0 (with optional leading whitespace). Captures the kind
// keyword (group 1) and the declaration name (group 2). Handles both
// struct-form (`<kind> NAME {`) and procedural forms
// (`func (Query|Mutation|Policy) NAME(`).
var constructHeader = regexp.MustCompile(
	`(?m)^[ \t]*(?:` +
		`(concept|query|mutation|shape|spec|trait|automation|logic|builtin|tool|prompt|provider|policy)[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]*\{` +
		`|` +
		`func[ \t]*\([ \t]*(Query|Mutation|Policy)[ \t]*\)[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]*\(` +
		`)`,
)

// kindToFile maps each construct keyword (lower-cased) to its target
// filename in the new per-kind layout.
var kindToFile = map[string]string{
	"concept":    "concepts.memql",
	"query":      "queries.memql",
	"mutation":   "mutations.memql",
	"shape":      "shapes.memql",
	"spec":       "specs.memql",
	"trait":      "traits.memql",
	"automation": "automations.memql",
	"logic":      "logic.memql",
	"builtin":    "builtins.memql",
	"tool":       "tools.memql",
	"prompt":     "prompts.memql",
	"provider":   "providers.memql",
	"policy":     "policies.memql",
}

// kindHeaderComment is the leading comment block written into each
// generated file so readers know how it was produced.
const kindHeaderComment = `// Generated by scripts/restructure-by-construct.
// Per-construct DSL layout: every <kind>s.memql file in a domain
// holds every construct of that kind in the domain. The companion
// files cover the other construct kinds.
`

// extractedSlice carries one extracted construct ready to be routed
// to its target per-kind file.
type extractedSlice struct {
	Kind   string
	Name   string
	Source string
	Origin string // source file path (for diagnostics)
}

func main() {
	domains, err := listDomains()
	if err != nil {
		die("list domains: %v", err)
	}
	for _, domain := range domains {
		if err := restructureDomain(domain); err != nil {
			die("domain %s: %v", domain, err)
		}
		if err := consolidatePromptSubdir(domain); err != nil {
			die("domain %s prompts: %v", domain, err)
		}
	}
	fmt.Println("restructure-by-construct: done")
}

// consolidatePromptSubdir collapses dsl/<domain>/prompts/<name>.memql
// files into dsl/<domain>/prompts.memql. The .tmpl companion files
// stay in dsl/<domain>/prompts/ -- they're referenced from each
// prompt's @templateFile annotation, which is rewritten from
// "name.tmpl" to "prompts/name.tmpl" so the unified-prompt loader's
// path-resolution still finds them.
func consolidatePromptSubdir(domain string) error {
	promptsDir := filepath.Join(dslRoot, domain, "prompts")
	info, err := os.Stat(promptsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return nil
	}
	entries, err := os.ReadDir(promptsDir)
	if err != nil {
		return err
	}
	var promptFiles []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if strings.HasSuffix(e.Name(), ".memql") {
			promptFiles = append(promptFiles, filepath.Join(promptsDir, e.Name()))
		}
	}
	if len(promptFiles) == 0 {
		return nil
	}

	// Read existing dsl/<domain>/prompts.memql if present so we merge
	// rather than overwrite. (None of the current tree has both forms
	// at once, but the script must remain idempotent.)
	rootPromptsPath := filepath.Join(dslRoot, domain, "prompts.memql")
	var slices []extractedSlice
	if existing, err := os.ReadFile(rootPromptsPath); err == nil {
		source := stripGeneratedHeader(string(existing))
		slices = append(slices, extractConstructSlices(source, rootPromptsPath)...)
	}

	templateFileRewriter := regexp.MustCompile(`@templateFile\("([^"]+)"\)`)
	for _, path := range promptFiles {
		raw, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		source := stripGeneratedHeader(string(raw))
		for _, slice := range extractConstructSlices(source, path) {
			if slice.Kind != "prompt" {
				continue
			}
			rewritten := templateFileRewriter.ReplaceAllStringFunc(slice.Source, func(match string) string {
				m := templateFileRewriter.FindStringSubmatch(match)
				if len(m) < 2 {
					return match
				}
				tmpl := m[1]
				if strings.HasPrefix(tmpl, "prompts/") || strings.HasPrefix(tmpl, "/") {
					return match
				}
				return fmt.Sprintf("@templateFile(\"prompts/%s\")", tmpl)
			})
			slice.Source = rewritten
			slices = append(slices, slice)
		}
	}

	if len(slices) == 0 {
		return nil
	}

	// Deduplicate by name (later wins) and write the consolidated file.
	dedup := map[string]extractedSlice{}
	for _, s := range slices {
		dedup[s.Name] = s
	}
	merged := make([]extractedSlice, 0, len(dedup))
	for _, s := range dedup {
		merged = append(merged, s)
	}
	sort.Slice(merged, func(i, j int) bool { return merged[i].Name < merged[j].Name })

	var buf strings.Builder
	buf.WriteString(kindHeaderComment)
	buf.WriteString("\n")
	for i, s := range merged {
		if i > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString(strings.TrimRight(s.Source, "\n\r\t "))
		buf.WriteString("\n")
	}
	if err := os.WriteFile(rootPromptsPath, []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", rootPromptsPath, err)
	}

	// Remove the individual .memql files; keep the .tmpl sidecars.
	for _, path := range promptFiles {
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove %s: %w", path, err)
		}
	}
	return nil
}

func listDomains() ([]string, error) {
	entries, err := os.ReadDir(dslRoot)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		out = append(out, e.Name())
	}
	sort.Strings(out)
	return out, nil
}

func restructureDomain(domain string) error {
	dir := filepath.Join(dslRoot, domain)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	// Step 1: collect every .memql file in the domain root (not
	// recursive; subdirs like prompts/ hold templates that the loader
	// resolves via @templateFile).
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".memql") {
			continue
		}
		if strings.HasPrefix(name, "_") {
			continue
		}
		files = append(files, filepath.Join(dir, name))
	}

	if len(files) == 0 {
		return nil
	}

	// Step 2: extract every top-level construct slice from every file.
	slicesByKind := map[string][]extractedSlice{}
	for _, path := range files {
		raw, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		source := stripGeneratedHeader(string(raw))
		for _, slice := range extractConstructSlices(source, path) {
			slicesByKind[slice.Kind] = append(slicesByKind[slice.Kind], slice)
		}
	}

	// Step 3: emit per-kind files. Order constructs by name within
	// each file for deterministic output.
	emitted := map[string]bool{}
	for kind, slices := range slicesByKind {
		targetName, ok := kindToFile[kind]
		if !ok {
			return fmt.Errorf("unknown construct kind %q (slices=%d)", kind, len(slices))
		}
		sort.Slice(slices, func(i, j int) bool {
			return slices[i].Name < slices[j].Name
		})
		var buf strings.Builder
		buf.WriteString(kindHeaderComment)
		buf.WriteString("\n")
		for i, s := range slices {
			if i > 0 {
				buf.WriteString("\n")
			}
			body := strings.TrimRight(s.Source, "\n\r\t ")
			buf.WriteString(body)
			buf.WriteString("\n")
		}
		target := filepath.Join(dir, targetName)
		if err := os.WriteFile(target, []byte(buf.String()), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", target, err)
		}
		emitted[targetName] = true
	}

	// Step 4: delete originals that didn't survive as a per-kind target.
	// (e.g. `dsl/cognition/participant.memql` had concept + queries +
	// mutations + shape + specs -- now redistributed.)
	for _, path := range files {
		base := filepath.Base(path)
		if emitted[base] {
			// File was overwritten with consolidated content; keep.
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove %s: %w", path, err)
		}
	}

	return nil
}

// stripGeneratedHeader removes the `// Generated by ...` comment
// block at the top of a file (from a prior restructure pass). The
// block is identified by leading lines beginning with `//` followed
// by a blank line. Stops at the first non-comment / non-blank line.
func stripGeneratedHeader(source string) string {
	lines := strings.Split(source, "\n")
	i := 0
	if i >= len(lines) || !strings.HasPrefix(strings.TrimSpace(lines[i]), "// Generated by") {
		return source
	}
	// Skip the comment block + any immediately-following blank lines.
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			i++
			continue
		}
		break
	}
	return strings.Join(lines[i:], "\n")
}

// extractConstructSlices scans source for every top-level construct
// header, walks back through @-attributes + line comments to capture
// the preamble, then forward through balanced braces (or matched
// parens for procedural forms) to find the body's closer.
func extractConstructSlices(source, origin string) []extractedSlice {
	matches := constructHeader.FindAllStringSubmatchIndex(source, -1)
	if len(matches) == 0 {
		return nil
	}
	var out []extractedSlice
	for _, m := range matches {
		var kind, name string
		var openBraceFrom int // index from which to search for body's `{`
		headerEnd := m[1]

		if m[2] >= 0 {
			// Struct form: `<kind> NAME {`
			kind = strings.ToLower(source[m[2]:m[3]])
			name = source[m[4]:m[5]]
			openBraceFrom = headerEnd - 1 // already at `{`
		} else if m[6] >= 0 {
			// Procedural form: `func (Kind) NAME(`
			kind = strings.ToLower(source[m[6]:m[7]])
			name = source[m[8]:m[9]]
			// Scan forward for the body's `{`. Skip the param list
			// `(...)` and any return-type signature.
			openBraceFrom = headerEnd
		} else {
			continue
		}

		openIdx := findFirstBrace(source, openBraceFrom)
		if openIdx < 0 {
			continue
		}
		closeIdx := findMatchingBrace(source, openIdx)
		if closeIdx < 0 {
			continue
		}

		// Walk backwards from the header for @-attribute + comment
		// preamble. Stop at the first blank line or non-decoration
		// line.
		headerStart := m[0]
		preambleStart := headerStart
		for k := headerStart - 1; k >= 0; k-- {
			lineStart := strings.LastIndexByte(source[:k], '\n') + 1
			line := strings.TrimRight(source[lineStart:k+1], "\r\n")
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "@") || strings.HasPrefix(trimmed, "//") {
				preambleStart = lineStart
				k = lineStart - 1
				continue
			}
			if trimmed == "" {
				break
			}
			break
		}

		out = append(out, extractedSlice{
			Kind:   kind,
			Name:   name,
			Source: source[preambleStart : closeIdx+1],
			Origin: origin,
		})
	}
	return out
}

// findFirstBrace returns the index of the next `{` at or after start.
// Skips characters inside string literals and line comments.
func findFirstBrace(source string, start int) int {
	if source[start] == '{' {
		return start
	}
	inString := false
	for i := start; i < len(source); i++ {
		c := source[i]
		if inString {
			if c == '\\' && i+1 < len(source) {
				i++
				continue
			}
			if c == '"' {
				inString = false
			}
			continue
		}
		switch c {
		case '"':
			inString = true
		case '/':
			if i+1 < len(source) && source[i+1] == '/' {
				nl := strings.IndexByte(source[i:], '\n')
				if nl < 0 {
					return -1
				}
				i += nl
			}
		case '{':
			return i
		}
	}
	return -1
}

// findMatchingBrace returns the index of the `}` matching the `{` at
// openIdx. Aware of string literals and line comments.
func findMatchingBrace(source string, openIdx int) int {
	if openIdx < 0 || openIdx >= len(source) || source[openIdx] != '{' {
		return -1
	}
	depth := 0
	inString := false
	for i := openIdx; i < len(source); i++ {
		c := source[i]
		if inString {
			if c == '\\' && i+1 < len(source) {
				i++
				continue
			}
			if c == '"' {
				inString = false
			}
			continue
		}
		switch c {
		case '"':
			inString = true
		case '/':
			if i+1 < len(source) && source[i+1] == '/' {
				nl := strings.IndexByte(source[i:], '\n')
				if nl < 0 {
					return -1
				}
				i += nl
			}
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return i
			}
		}
	}
	return -1
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "restructure-by-construct: "+format+"\n", args...)
	os.Exit(1)
}
