package main

import (
	"fmt"
	"strings"

	"github.com/znasllc-io/memql/component/frontdoor"
)

// tlsSecret is the one front-door certificate per namespace. Named identically
// in every environment: a Kubernetes Secret is namespaced, so two environments
// naming it the same is not a collision, and naming it differently would be a
// per-environment value with nothing to decide.
const tlsSecret = "memql-front-door-tls"

// clusterIssuer is the cert-manager ClusterIssuer that signs it. Managed
// outside this repository (deploy/argocd/apps/project.yaml permits the
// public-entry overlay to own it) and referenced by name, exactly as
// deploy/k8s/base/livekit.yaml already references it.
//
// IT MUST RESOLVE DNS-01. A wildcard SAN cannot be issued over HTTP-01 -- ACME
// has no way to serve a challenge for a name that does not exist yet -- and
// every environment here requests at least one. An issuer configured for
// HTTP-01 alone does not fail at apply time; the Certificate sits Pending, the
// Secret is never created, and the Ingresses serve the controller's default
// certificate, which presents as a name-mismatch warning in a browser rather
// than as anything naming cert-manager.
const clusterIssuer = "letsencrypt-prod"

// ingressClass is the cloud front door's L7 proxy.
//
// nginx and not traefik, matching the only other cloud Ingress in this
// repository (deploy/k8s/base/livekit.yaml, which the local overlay deletes for
// exactly this reason). The choice is a VALUE under CLAUDE.md's parity standard
// -- "ingress controller (traefik vs nginx annotations)" is on its ALLOWED list
// -- and it is the one thing in this file that a cluster could disagree with
// this repository about. If the cloud cluster is ever traefik, this constant and
// the annotations below change together and nothing else here does.
const ingressClass = "nginx"

// manifest renders one environment's whole front door.
//
// The order is: certificate first (nothing else works without it), then the
// roles in the order component/frontdoor declares them, then the sites
// wildcard. Stable, because a reordering would show up as a diff in a generated
// file and cost a review round for nothing.
func manifest(env environment, domain, pathBlock string) string {
	var b strings.Builder
	b.WriteString(header(env, domain))
	b.WriteString(certificate(env, domain))
	b.WriteString(apiIngress(env, domain, pathBlock))
	b.WriteString(apiGRPCIngress(env, domain))
	b.WriteString(identityIngress(env, domain))
	b.WriteString(mcpIngress(env, domain))
	b.WriteString(edgeIngress(env, domain))
	return b.String()
}

func header(env environment, domain string) string {
	hosts := frontdoor.Hosts(env.label, domain)
	var rows strings.Builder
	for _, h := range hosts {
		fmt.Fprintf(&rows, "#   %-12s %s\n", h.Role, h.Name)
	}

	labelNote := "# This environment carries NO host label, so its hosts are the unprefixed ones\n" +
		"# and it owns the apex. Exactly one environment may be in that position: the bare\n" +
		"# domain has no label for a second claimant to occupy.\n"
	if env.label != "" {
		labelNote = fmt.Sprintf(
			"# This environment's label is %q. Its ROLE hosts hyphenate (api-%s.<domain>) so the\n"+
				"# cluster's existing *.<domain> wildcard certificate still covers them -- a TLS\n"+
				"# wildcard matches exactly ONE label, and api.%s.<domain> would need a certificate\n"+
				"# of its own. Its SITES cannot do that, because a site's own name already occupies\n"+
				"# that label, so they nest and this environment requests ONE additional wildcard,\n"+
				"# *.%s.<domain> -- one certificate for all of its sites, not one per site.\n"+
				"#\n"+
				"# A site here lives under the CLUSTER's domain: the host for shop.acme.com is\n"+
				"# shop.%s.<clusterdomain>, never shop.%s.acme.com. This environment is the\n"+
				"# operator's own surface and must not require DNS the operator may not control.\n",
			env.label, env.label, env.label, env.label, env.label, env.label)
	}

	return "" +
		"# GENERATED by cmd/frontdoorhosts -- DO NOT EDIT.\n" +
		"# Run `make frontdoor` (hosts, then paths). Hand edits are reverted by the generator\n" +
		"# and TestFrontDoorHostsAreNotStale fails the build until they are.\n" +
		"#\n" +
		"# The front door for the `" + env.dir + "` overlay (" + env.name + "), as the product of\n" +
		"# ROLE x ENVIRONMENT (epic memql#3748 / memql#3767). The host COUNT is allowed to grow\n" +
		"# with environments -- a closed set the operator chooses -- and never with customers,\n" +
		"# apps or sites, which is what the sites wildcard is for (memql#3700).\n" +
		"#\n" +
		rows.String() +
		"#\n" +
		labelNote +
		"#\n" +
		"# THE DOMAIN IS A COMMITTED DEFAULT, NOT A CONSTANT (memql#3593). No file under deploy/\n" +
		"# names a real domain: the domain is a value on the memql-domain ConfigMap, which every\n" +
		"# node derives its issuer, CORS origins and redirect URIs from at boot\n" +
		"# (component/genesis/domain.go, threaded through component/frontdoor so the hosts below\n" +
		"# and the hosts the nodes believe in cannot disagree). An Ingress host is a Kubernetes\n" +
		"# API object, so it has to be in the render; an install overrides these through the\n" +
		"# ArgoCD Application's spec.source.kustomize.patches. `.localhost` is unroutable, so an\n" +
		"# environment reconciled before its domain is set fails visibly rather than half-working.\n" +
		"#\n" +
		"# NO ROUTER-PRIORITY ANNOTATIONS, unlike the local overlay's traefik front door. nginx\n" +
		"# resolves server_name by specificity in its own core -- an exact name beats a leading\n" +
		"# wildcard -- so the role hosts outrank *.<domain> without anything being declared. That\n" +
		"# is a guarantee traefik does not give, which is why the local overlay declares the\n" +
		"# ranking by hand and why doing it there went wrong once (memql#3810). Do not copy that\n" +
		"# annotation here: it would be an unnecessary declaration of something nginx already\n" +
		"# does, and Ingress-level priority is what flattened the api host's path ordering.\n"
}

func certificate(env environment, domain string) string {
	var sans strings.Builder
	for _, s := range frontdoor.CertificateSANs(env.label, domain) {
		fmt.Fprintf(&sans, "    - %q\n", s)
	}

	return "---\n" +
		"# The front-door certificate for this namespace.\n" +
		"#\n" +
		"# ONE PER NAMESPACE, and the SAN sets overlap deliberately. A Kubernetes Secret cannot\n" +
		"# be referenced across namespaces, so a certificate shared between the environments is\n" +
		"# not expressible -- two orders for the same wildcard is the price of the namespace\n" +
		"# isolation the whole epic rests on, and it is paid once per renewal, not per site.\n" +
		"#\n" +
		"# *.<domain> is present in EVERY environment, and that is what the hyphenated role hosts\n" +
		"# buy: a labelled environment adds exactly one SAN for its sites and needs none for its\n" +
		"# api / identity / mcp hosts. The apex is a separate SAN because no wildcard covers it --\n" +
		"# *.<domain> matches one label and the bare domain has none.\n" +
		"apiVersion: cert-manager.io/v1\n" +
		"kind: Certificate\n" +
		"metadata:\n" +
		"  name: " + tlsSecret + "\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  secretName: " + tlsSecret + "\n" +
		"  issuerRef:\n" +
		"    name: " + clusterIssuer + "\n" +
		"    kind: ClusterIssuer\n" +
		"  dnsNames:\n" +
		sans.String()
}

// apiIngress carries the bff's HTTP surface. It does NOT carry the h2c
// catch-all -- apiGRPCIngress does, and the split is forced.
func apiIngress(env environment, domain, pathBlock string) string {
	host := frontdoor.RoleHost(frontdoor.RoleAPI, env.label, domain)

	return "---\n" +
		"# The API edge's HTTP half.\n" +
		"#\n" +
		"# TWO INGRESS OBJECTS FOR ONE HOST, AND THIS IS THE CONSTRAINT THAT FORCES IT: an\n" +
		"# ingress controller's backend protocol is not a per-path setting. On nginx\n" +
		"# `backend-protocol` is an annotation on the INGRESS, so an object cannot route some of\n" +
		"# its paths to an h2c backend and the rest to an HTTP one; the bff's gRPC edge\n" +
		"# (bff:50051) and its HTTP edge (bff-http:8085) are already two Services over one\n" +
		"# Deployment for the same reason. So the HTTP paths live here and the gRPC catch-all\n" +
		"# lives in the object below. nginx merges rules for one host into one server block and\n" +
		"# orders locations by prefix length, so every path below outranks the `/` catch-all.\n" +
		"#\n" +
		"# MERGING THEM WOULD NOT 404 -- it would hand an HTTP/1.1 request to an h2c backend,\n" +
		"# which fails with a protocol error naming nothing. That is memql#3703, and it is the\n" +
		"# same failure the generated block below exists to prevent from the other direction.\n" +
		"#\n" +
		"# THE PATH LIST IS GENERATED BY A DIFFERENT TOOL. cmd/frontdoorpaths emits it from\n" +
		"# component/server's own path declarations; this tool preserves the block across a\n" +
		"# regeneration and `make frontdoor-paths` fills it. Hand-editing it is reverted by the\n" +
		"# generator, and some paths the bff serves are DELIBERATELY withheld from it --\n" +
		"# /metrics and /api/concepts* are unauthenticated because they are in-cluster only, so\n" +
		"# adding a rule for one is not a fix, it is an exposure.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: api-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		beginMarker + "\n" +
		pathBlock +
		endMarker + "\n"
}

func apiGRPCIngress(env environment, domain string) string {
	host := frontdoor.RoleHost(frontdoor.RoleAPI, env.label, domain)

	return "---\n" +
		"# The API edge's gRPC half: the h2c catch-all, on the same host.\n" +
		"#\n" +
		"# Everything the bff serves over gRPC arrives here -- MemqlService.Stream is the primary\n" +
		"# surface, so this is the rule the Cockpit, the SDKs, the VS Code extension and the\n" +
		"# browser bridge all land on. It is `/` and it is a whole Ingress of its own because\n" +
		"# backend-protocol is Ingress-scoped; see the object above.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: api-front-door-grpc\n" +
		"  namespace: memql\n" +
		"  annotations:\n" +
		"    nginx.ingress.kubernetes.io/backend-protocol: \"GRPC\"\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "bff", 50051)
}

func identityIngress(env environment, domain string) string {
	host := frontdoor.RoleHost(frontdoor.RoleIdentity, env.label, domain)

	return "---\n" +
		"# The identity service: /login, the WebAuthn ceremonies, the OAuth endpoints,\n" +
		"# /.well-known/jwks.json, /me/*, /enroll and /device.\n" +
		"#\n" +
		"# HTTPS ON THE INTERNAL HOP, VERIFICATION OFF. identity serves TLS in-cluster under the\n" +
		"# internal CA, which the ingress controller's trust store does not carry -- so the proxy\n" +
		"# speaks https to it and skips verification. The hop stays inside the cluster network.\n" +
		"# The local overlay expresses the same thing with a traefik ServersTransport.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: identity-front-door\n" +
		"  namespace: memql\n" +
		"  annotations:\n" +
		"    nginx.ingress.kubernetes.io/backend-protocol: \"HTTPS\"\n" +
		"    nginx.ingress.kubernetes.io/proxy-ssl-verify: \"off\"\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "identity", 8085)
}

func mcpIngress(env environment, domain string) string {
	host := frontdoor.RoleHost(frontdoor.RoleMCP, env.label, domain)

	return "---\n" +
		"# The MCP Streamable HTTP protocol head.\n" +
		"#\n" +
		"# Its own host rather than a path under the api host, for the constraint that shapes\n" +
		"# this whole file: the mcp node is a different Service on a different port (8090)\n" +
		"# speaking plain HTTP, and backend protocol is not a per-path setting. Not proxied\n" +
		"# through the edge either -- MCP clients configure a URL, they are not browsers, and an\n" +
		"# extra hop on a tool-calling path buys nothing.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: mcp-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "mcp", 8090)
}

func edgeIngress(env environment, domain string) string {
	wildcard := frontdoor.SitesWildcard(env.label, domain)
	apex := frontdoor.Apex(env.label, domain)

	hosts := []string{wildcard}
	rules := "" +
		"    # Every hosted site in this environment: the portal, and every SPA or website the\n" +
		"    # operator creates a v1:platform:site row for. ONE rule, forever -- the edge node\n" +
		"    # resolves the request Host against the graph, so a new site is an upload plus a row\n" +
		"    # write and the number of Kubernetes objects does not grow with it.\n" +
		"    - host: " + fmt.Sprintf("%q", wildcard) + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "edge", 8085)
	if apex != "" {
		hosts = append(hosts, apex)
		rules += "" +
			"    # The apex, and it is NOT a special case: for a customer cluster the bare domain IS\n" +
			"    # their main website, so it is a site row like any other -- it just happens to be the\n" +
			"    # one whose hostname has no label in front of it. Same Service; the edge cannot tell\n" +
			"    # the two rules apart. Only the unprefixed environment has one, because the bare\n" +
			"    # domain has no label for a second environment to occupy.\n" +
			"    - host: " + apex + "\n" +
			"      http:\n" +
			"        paths:\n" +
			pathRule("/", "edge", 8085)
	}

	return "---\n" +
		"# The site edge -- the last front-door rules that will ever be added.\n" +
		"#\n" +
		"# Everything after this is a graph row. That is the whole of memql#3700's \"a site is\n" +
		"# data, not infrastructure\": the host count grows with ENVIRONMENTS, which are a closed\n" +
		"# set, and never with sites, which are not.\n" +
		"#\n" +
		"# The edge serves plain HTTP on :8085, so no backend-protocol annotation is needed here\n" +
		"# -- unlike the api host, which carries h2c for gRPC, and unlike identity, which is https\n" +
		"# behind a verification skip.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: edge-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(hosts...) +
		"  rules:\n" +
		rules
}

// tlsBlock names the certificate an Ingress terminates with. Every front-door
// Ingress in a namespace names the SAME Secret, which the Certificate above
// creates -- one certificate per namespace covering every host in it.
func tlsBlock(hosts ...string) string {
	var b strings.Builder
	b.WriteString("  tls:\n    - hosts:\n")
	for _, h := range hosts {
		fmt.Fprintf(&b, "        - %q\n", h)
	}
	fmt.Fprintf(&b, "      secretName: %s\n", tlsSecret)
	return b.String()
}

// pathRule renders one Ingress path entry, indented to sit under
// spec.rules[].http.paths.
func pathRule(path, service string, port int) string {
	return fmt.Sprintf(""+
		"          - path: %s\n"+
		"            pathType: Prefix\n"+
		"            backend:\n"+
		"              service:\n"+
		"                name: %s\n"+
		"                port:\n"+
		"                  number: %d\n", path, service, port)
}
