package main

import (
	"fmt"
	"strings"

	"github.com/znasllc-io/memql/component/frontdoor"
)

// tlsSecret is the cluster's one front-door certificate.
const tlsSecret = "memql-front-door-tls"

// clusterIssuer is the cert-manager ClusterIssuer that signs it. Managed
// outside this repository (deploy/argocd/apps/project.yaml permits the
// public-entry overlay to own it) and referenced by name, exactly as
// deploy/k8s/base/livekit.yaml already references it.
//
// IT SOLVES HTTP-01, AND THE CERTIFICATE IS SHAPED FOR THAT (memql#4224). An
// earlier version of this comment demanded a DNS-01 solver because the
// Certificate requested `*.<domain>`; the cluster's issuer never had one, and
// the consequence was not a failure at apply time. ACME cannot serve an HTTP-01
// challenge for a wildcard, ONE wildcard dnsName fails the WHOLE order, the
// Certificate sat Pending, and every Ingress served the controller's
// self-signed default -- a browser name-mismatch warning naming nothing. So the
// Certificate names exact hosts only, which HTTP-01 issues without ceremony: a
// GET to /.well-known/acme-challenge/ on each name, answered through the same
// ingress controller that routes everything else here.
const clusterIssuer = "letsencrypt-prod"

// ingressClass is the cloud front door's L7 proxy.
//
// nginx and not traefik, matching the only other cloud Ingress in this
// repository (deploy/k8s/base/livekit.yaml, which the local overlay deletes for
// exactly this reason). The choice is a VALUE under CLAUDE.md's parity standard
// -- "ingress controller (traefik vs nginx annotations)" is on its ALLOWED list
// -- and it is the one thing in this file that a cluster could disagree with
// this repository about. If the cloud cluster is ever traefik, this constant and
// the annotations below change together and nothing else here does.
const ingressClass = "nginx"

// manifest renders one instance overlay's whole front door.
//
// The order is: certificate first (nothing else works without it), then the
// roles in the order component/frontdoor declares them, then the portal, then
// the sites wildcard and the apex. Stable, because a reordering would show up
// as a diff in a generated file and cost a review round for nothing.
func manifest(overlay, domain, pathBlock string) string {
	var b strings.Builder
	b.WriteString(header(overlay, domain))
	b.WriteString(certificate(domain))
	b.WriteString(apiIngress(domain, pathBlock))
	b.WriteString(apiGRPCIngress(domain))
	b.WriteString(identityIngress(domain))
	b.WriteString(mcpIngress(domain))
	b.WriteString(portalIngress(domain))
	b.WriteString(edgeIngress(domain))
	return b.String()
}

func header(overlay, domain string) string {
	var rows strings.Builder
	for _, h := range frontdoor.Hosts(domain) {
		fmt.Fprintf(&rows, "#   %-12s %s\n", h.Role, h.Name)
	}

	return "" +
		"# GENERATED by cmd/frontdoorhosts -- DO NOT EDIT.\n" +
		"# Run `make frontdoor` (hosts, then paths). Hand edits are reverted by the generator\n" +
		"# and TestFrontDoorHostsAreNotStale fails the build until they are.\n" +
		"#\n" +
		"# The front door for the `" + overlay + "` overlay, derived from the closed ROLE set plus\n" +
		"# the platform's own site (memql#3767, memql#4224). The host COUNT never grows with\n" +
		"# customers, apps or sites, which is what the sites wildcard is for (memql#3700).\n" +
		"#\n" +
		rows.String() +
		"#\n" +
		"# THE CERTIFICATE NAMES EXACT HOSTS, NOT A WILDCARD (memql#4224). The ClusterIssuer\n" +
		"# solves HTTP-01 only. ACME cannot serve an HTTP-01 challenge for *.<domain>, and ONE\n" +
		"# wildcard dnsName fails the WHOLE order -- so the Certificate that used to request it sat\n" +
		"# Pending, was hand-edited to exact names on the first entry-shape cluster, and the edge\n" +
		"# Ingress whose tls.hosts still said *.<domain> served ingress-nginx's self-signed default\n" +
		"# for portal.<domain> (Safari: \"This Connection Is Not Private\"). DECISION: the wildcard\n" +
		"# is NOT requested. dnsNames is every exact host above; every Ingress below lists exactly\n" +
		"# its own exact rule hosts under tls; and the union of those tls lists is the dnsNames\n" +
		"# set -- deploy/k8s/overlays/frontdoor_hosts_test.go fails the build when they differ.\n" +
		"# The *.<domain> RULE stays, because it is how every site reaches the edge, and THIS\n" +
		"# certificate is not what covers it. Where the overlay declares a DNS-01 ClusterIssuer it\n" +
		"# also declares a SECOND, wildcard Certificate, and the wildcard rule carries that one\n" +
		"# under tls (memql#4347). Where it does not -- the default -- the wildcard rule still has\n" +
		"# no certificate behind it and a customer site hostname needs its own Certificate and\n" +
		"# exact-host Ingress (docs/public/operate/site-hosting.md). Either way this generated\n" +
		"# certificate names exact hosts only, because HTTP-01 cannot issue a wildcard. The portal\n" +
		"# is the one site the generator can name in advance, so it is the one site with an exact\n" +
		"# rule and a SAN here.\n" +
		"#\n" +
		"# THE DOMAIN IS A COMMITTED DEFAULT, NOT A CONSTANT (memql#3593). No file under deploy/\n" +
		"# names a real domain: the domain is a value on the memql-domain ConfigMap, which every\n" +
		"# node derives its issuer, CORS origins, redirect URIs and portal site hostname from at\n" +
		"# boot (component/envregistry/domain.go and component/memql's SeedMaterializer, threaded\n" +
		"# through component/frontdoor so the hosts below and the hosts the nodes believe in\n" +
		"# cannot disagree). An Ingress host is a Kubernetes API object, so it has to be in the\n" +
		"# render; an install overrides these through the ArgoCD Application's\n" +
		"# spec.source.kustomize.patches. `.localhost` is unroutable, so a cluster reconciled\n" +
		"# before its domain is set fails visibly rather than half-working.\n" +
		"#\n" +
		"# NO ROUTER-PRIORITY ANNOTATIONS, unlike the local overlay's traefik front door. nginx\n" +
		"# resolves server_name by specificity in its own core -- an exact name beats a leading\n" +
		"# wildcard -- so the role hosts and the portal outrank *.<domain> without anything being\n" +
		"# declared. That is a guarantee traefik does not give, which is why the local overlay\n" +
		"# declares the ranking by hand and why doing it there went wrong once (memql#3810). Do\n" +
		"# not copy that annotation here: it would be an unnecessary declaration of something\n" +
		"# nginx already does, and Ingress-level priority is what flattened the api host's path\n" +
		"# ordering.\n"
}

func certificate(domain string) string {
	var sans strings.Builder
	for _, s := range frontdoor.CertificateSANs(domain) {
		fmt.Fprintf(&sans, "    - %q\n", s)
	}

	return "---\n" +
		"# The front-door certificate for this namespace: every EXACT host the front door serves,\n" +
		"# and nothing else (memql#4224).\n" +
		"#\n" +
		"# NO WILDCARD SAN. The issuer is HTTP-01 and a wildcard dnsName fails the whole order,\n" +
		"# not the one name -- the Certificate would sit Pending and every host here would serve\n" +
		"# the controller's default certificate. The apex is a dnsName like any other now; it\n" +
		"# used to be the one exception to a wildcard that matched exactly one label. One order,\n" +
		"# one renewal, and a new customer site does NOT join this list: it is covered by the\n" +
		"# overlay's wildcard Certificate where a DNS-01 issuer is declared, and otherwise needs a\n" +
		"# Certificate of its own (docs/public/operate/site-hosting.md).\n" +
		"#\n" +
		"# This list and the tls.hosts of the Ingresses below are the SAME set, derived from\n" +
		"# component/frontdoor.CertificateSANs; the overlay render gate asserts the equality.\n" +
		"apiVersion: cert-manager.io/v1\n" +
		"kind: Certificate\n" +
		"metadata:\n" +
		"  name: " + tlsSecret + "\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  secretName: " + tlsSecret + "\n" +
		"  issuerRef:\n" +
		"    name: " + clusterIssuer + "\n" +
		"    kind: ClusterIssuer\n" +
		"  dnsNames:\n" +
		sans.String()
}

// apiIngress carries the bff's HTTP surface. It does NOT carry the h2c
// catch-all -- apiGRPCIngress does, and the split is forced.
func apiIngress(domain, pathBlock string) string {
	host := frontdoor.RoleHost(frontdoor.RoleAPI, domain)

	return "---\n" +
		"# The API edge's HTTP half.\n" +
		"#\n" +
		"# TWO INGRESS OBJECTS FOR ONE HOST, AND THIS IS THE CONSTRAINT THAT FORCES IT: an\n" +
		"# ingress controller's backend protocol is not a per-path setting. On nginx\n" +
		"# `backend-protocol` is an annotation on the INGRESS, so an object cannot route some of\n" +
		"# its paths to an h2c backend and the rest to an HTTP one; the bff's gRPC edge\n" +
		"# (bff:50051) and its HTTP edge (bff-http:8085) are already two Services over one\n" +
		"# Deployment for the same reason. So the HTTP paths live here and the gRPC catch-all\n" +
		"# lives in the object below. nginx merges rules for one host into one server block and\n" +
		"# orders locations by prefix length, so every path below outranks the `/` catch-all.\n" +
		"#\n" +
		"# MERGING THEM WOULD NOT 404 -- it would hand an HTTP/1.1 request to an h2c backend,\n" +
		"# which fails with a protocol error naming nothing. That is memql#3703, and it is the\n" +
		"# same failure the generated block below exists to prevent from the other direction.\n" +
		"#\n" +
		"# THE PATH LIST IS GENERATED BY A DIFFERENT TOOL. cmd/frontdoorpaths emits it from\n" +
		"# component/server's own path declarations; this tool preserves the block across a\n" +
		"# regeneration and `make frontdoor-paths` fills it. Hand-editing it is reverted by the\n" +
		"# generator, and some paths the bff serves are DELIBERATELY withheld from it --\n" +
		"# /metrics and /api/concepts* are unauthenticated because they are in-cluster only, so\n" +
		"# adding a rule for one is not a fix, it is an exposure.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: api-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		beginMarker + "\n" +
		pathBlock +
		endMarker + "\n"
}

func apiGRPCIngress(domain string) string {
	host := frontdoor.RoleHost(frontdoor.RoleAPI, domain)

	return "---\n" +
		"# The API edge's gRPC half: the h2c catch-all, on the same host.\n" +
		"#\n" +
		"# Everything the bff serves over gRPC arrives here -- MemqlService.Stream is the primary\n" +
		"# surface, so this is the rule the Cockpit, the SDKs, the VS Code extension and the\n" +
		"# browser bridge all land on. It is `/` and it is a whole Ingress of its own because\n" +
		"# backend-protocol is Ingress-scoped; see the object above.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: api-front-door-grpc\n" +
		"  namespace: memql\n" +
		"  annotations:\n" +
		"    nginx.ingress.kubernetes.io/backend-protocol: \"GRPC\"\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "bff", 50051)
}

func identityIngress(domain string) string {
	host := frontdoor.RoleHost(frontdoor.RoleIdentity, domain)

	return "---\n" +
		"# The identity service: /login, the WebAuthn ceremonies, the OAuth endpoints,\n" +
		"# /.well-known/jwks.json, /me/*, /enroll and /device.\n" +
		"#\n" +
		"# HTTPS ON THE INTERNAL HOP, VERIFICATION OFF. identity serves TLS in-cluster under the\n" +
		"# internal CA, which the ingress controller's trust store does not carry -- so the proxy\n" +
		"# speaks https to it and skips verification. The hop stays inside the cluster network.\n" +
		"# The local overlay expresses the same thing with a traefik ServersTransport.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: identity-front-door\n" +
		"  namespace: memql\n" +
		"  annotations:\n" +
		"    nginx.ingress.kubernetes.io/backend-protocol: \"HTTPS\"\n" +
		"    nginx.ingress.kubernetes.io/proxy-ssl-verify: \"off\"\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "identity", 8085)
}

func mcpIngress(domain string) string {
	host := frontdoor.RoleHost(frontdoor.RoleMCP, domain)

	return "---\n" +
		"# The MCP Streamable HTTP protocol head.\n" +
		"#\n" +
		"# Its own host rather than a path under the api host, for the constraint that shapes\n" +
		"# this whole file: the mcp node is a different Service on a different port (8090)\n" +
		"# speaking plain HTTP, and backend protocol is not a per-path setting. Not proxied\n" +
		"# through the edge either -- MCP clients configure a URL, they are not browsers, and an\n" +
		"# extra hop on a tool-calling path buys nothing.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: mcp-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "mcp", 8090)
}

// portalIngress is the portal's own exact-host rule (memql#4224).
func portalIngress(domain string) string {
	host := frontdoor.PortalHost(domain)

	return "---\n" +
		"# The portal -- site #1, and the ONE site with an exact rule of its own (memql#4224).\n" +
		"#\n" +
		"# To the edge the portal is a site like any other: the same Service the wildcard below\n" +
		"# points at, resolved against the same v1:platform:site rows, no special path\n" +
		"# (component/edge's dogfood gate forbids one). It gets its own Ingress for a TLS reason\n" +
		"# and only that: ingress-nginx creates a certificate-bearing server block per RULE host,\n" +
		"# never per tls host. With only the *.<domain> rule, portal.<domain> is answered by the\n" +
		"# wildcard's server block, whose certificate is the controller's self-signed default\n" +
		"# because no wildcard SAN can be issued over HTTP-01 -- exactly what the first entry-shape\n" +
		"# cluster served to Safari. An exact rule gives the portal a server block the\n" +
		"# certificate verifies for.\n" +
		"#\n" +
		"# It is the only site the generator can do this for, because it is the only site whose\n" +
		"# name exists before an operator creates a row. The engine seeds that row's hostname\n" +
		"# from MEMQL_DOMAIN through the same derivation that wrote this host\n" +
		"# (component/frontdoor.PortalHost), so the certificate cannot name a host the row does\n" +
		"# not carry. The same Service and port as the edge Ingress below, deliberately: this is\n" +
		"# not a second way to serve the portal, it is the first way with a certificate.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: portal-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(host) +
		"  rules:\n" +
		"    - host: " + host + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "edge", 8085)
}

func edgeIngress(domain string) string {
	wildcard := frontdoor.SitesWildcard(domain)
	apex := frontdoor.Apex(domain)

	rules := "" +
		"    # Every hosted site: every SPA or website the operator creates a v1:platform:site\n" +
		"    # row for (the portal has its own rule above, for TLS; it is served exactly like\n" +
		"    # these). ONE rule, forever -- the edge node resolves the request Host against the\n" +
		"    # graph, so a new site is an upload plus a row write and the number of Kubernetes\n" +
		"    # objects does not grow with it. What a new site does NOT get from this rule is a\n" +
		"    # certificate: see the tls block above.\n" +
		"    - host: " + fmt.Sprintf("%q", wildcard) + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "edge", 8085) +
		"    # The apex, and it is NOT a special case: for a customer cluster the bare domain IS\n" +
		"    # their main website, so it is a site row like any other -- it just happens to be the\n" +
		"    # one whose hostname is the domain itself. Same Service; the edge cannot tell the two\n" +
		"    # rules apart.\n" +
		"    - host: " + apex + "\n" +
		"      http:\n" +
		"        paths:\n" +
		pathRule("/", "edge", 8085)

	return "---\n" +
		"# The site edge -- the wildcard and the apex, the last front-door rules that will ever\n" +
		"# be added.\n" +
		"#\n" +
		"# Everything after this is a graph row. That is the whole of memql#3700's \"a site is\n" +
		"# data, not infrastructure\": the host count is fixed by the closed ROLE set plus the\n" +
		"# platform's own portal, and never grows with sites.\n" +
		"#\n" +
		"# TLS NAMES THE APEX ONLY, IN THIS GENERATED BLOCK (memql#4224). The issuer here is\n" +
		"# HTTP-01, which cannot issue *.<domain>, and listing the wildcard under tls against an\n" +
		"# HTTP-01 certificate is what made ingress-nginx fall back to its self-signed default for\n" +
		"# every name this rule answers. An overlay that declares a DNS-01 ClusterIssuer adds the\n" +
		"# wildcard tls entry by patch, against its own wildcard Certificate (memql#4347); without\n" +
		"# one, a site routed by the wildcard terminates TLS with that default until it has a\n" +
		"# Certificate and an exact-host Ingress of its own (docs/public/operate/site-hosting.md).\n" +
		"#\n" +
		"# The edge serves plain HTTP on :8085, so no backend-protocol annotation is needed here\n" +
		"# -- unlike the api host, which carries h2c for gRPC, and unlike identity, which is https\n" +
		"# behind a verification skip.\n" +
		"apiVersion: networking.k8s.io/v1\n" +
		"kind: Ingress\n" +
		"metadata:\n" +
		"  name: edge-front-door\n" +
		"  namespace: memql\n" +
		"spec:\n" +
		"  ingressClassName: " + ingressClass + "\n" +
		tlsBlock(apex) +
		"  rules:\n" +
		rules
}

// tlsBlock names the certificate an Ingress terminates with, and the EXACT
// hosts it terminates for. Every front-door Ingress in a namespace names the
// SAME Secret, which the Certificate above creates -- one certificate per
// namespace covering every exact host in it -- and lists under tls exactly the
// exact rule hosts it carries, never the wildcard (memql#4224): ingress-nginx
// verifies the certificate against each tls host and falls back to its
// self-signed default for a host the certificate does not name.
func tlsBlock(hosts ...string) string {
	var b strings.Builder
	b.WriteString("  tls:\n    - hosts:\n")
	for _, h := range hosts {
		fmt.Fprintf(&b, "        - %q\n", h)
	}
	fmt.Fprintf(&b, "      secretName: %s\n", tlsSecret)
	return b.String()
}

// pathRule renders one Ingress path entry, indented to sit under
// spec.rules[].http.paths.
func pathRule(path, service string, port int) string {
	return fmt.Sprintf(""+
		"          - path: %s\n"+
		"            pathType: Prefix\n"+
		"            backend:\n"+
		"              service:\n"+
		"                name: %s\n"+
		"                port:\n"+
		"                  number: %d\n", path, service, port)
}
