// Code generated by scripts/sdk-gen. DO NOT EDIT.
// Source of truth: dsl/**/*.memql.

package client

import (
	"context"
	"fmt"
	"strings"
)

var (
	_ = fmt.Sprintf
	_ = strings.Builder{}
)

// LogicAccessRequestExpirySweep -- Daily 04:00 UTC sweep that ages out pending access requests older than IDENTITY_ACCESS_REQUEST_EXPIRY_DAYS (default 30) by stamping status='expired'. Per-row windowing via addDuration(createdAt, P{N}D) since MemQL filters can't push the duration math down. Pending queue is small (admin), so daily walk is cheap.
type LogicAccessRequestExpirySweepArgs struct {
	Event map[string]any
}

// LogicAccessRequestExpirySweep calls the engine logic logicAccessRequestExpirySweep.
func (qc *QueryClient) LogicAccessRequestExpirySweep(ctx context.Context, args LogicAccessRequestExpirySweepArgs) (*Result, error) {
	call := LogicAccessRequestExpirySweepBuild(args)
	return qc.executeNamed(ctx, "logicAccessRequestExpirySweep", call)
}

func LogicAccessRequestExpirySweepBuild(args LogicAccessRequestExpirySweepArgs) string {
	var b strings.Builder
	b.WriteString("logicAccessRequestExpirySweep({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicAccountDeletionReminder25Days -- Daily 09:05 UTC sweep that emits an 'identity.deletion.reminder' event for each user 25-26 days into their deletion cooldown -- final notice before accountDeletionSweep performs the hard delete at 30 days. Bracket [P25D, P26D) on deletionScheduledAt fired daily means each user gets exactly one reminder at this milestone.
type LogicAccountDeletionReminder25DaysArgs struct {
	Event map[string]any
}

// LogicAccountDeletionReminder25Days calls the engine logic logicAccountDeletionReminder25Days.
func (qc *QueryClient) LogicAccountDeletionReminder25Days(ctx context.Context, args LogicAccountDeletionReminder25DaysArgs) (*Result, error) {
	call := LogicAccountDeletionReminder25DaysBuild(args)
	return qc.executeNamed(ctx, "logicAccountDeletionReminder25Days", call)
}

func LogicAccountDeletionReminder25DaysBuild(args LogicAccountDeletionReminder25DaysArgs) string {
	var b strings.Builder
	b.WriteString("logicAccountDeletionReminder25Days({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicAccountDeletionReminder7Days -- Daily 09:00 UTC sweep that emits an 'identity.deletion.reminder' event for each user 7-8 days into their deletion cooldown so they can cancel before the cooldown elapses. Bracket [P7D, P8D) on deletionScheduledAt fired daily means exactly one reminder per user at this milestone. Email delivery is consumed by the component/server subscriber.
type LogicAccountDeletionReminder7DaysArgs struct {
	Event map[string]any
}

// LogicAccountDeletionReminder7Days calls the engine logic logicAccountDeletionReminder7Days.
func (qc *QueryClient) LogicAccountDeletionReminder7Days(ctx context.Context, args LogicAccountDeletionReminder7DaysArgs) (*Result, error) {
	call := LogicAccountDeletionReminder7DaysBuild(args)
	return qc.executeNamed(ctx, "logicAccountDeletionReminder7Days", call)
}

func LogicAccountDeletionReminder7DaysBuild(args LogicAccountDeletionReminder7DaysArgs) string {
	var b strings.Builder
	b.WriteString("logicAccountDeletionReminder7Days({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicAccountDeletionSweep -- Daily 03:00 UTC sweep that hard-deletes users whose deletionScheduledAt + IDENTITY_DELETION_COOLDOWN_DAYS (default 30) has elapsed, via mutationDeleteUserHard. Audit-event rows, invitations the user issued, and access-request rows are intentionally retained for the trail.
type LogicAccountDeletionSweepArgs struct {
	Event map[string]any
}

// LogicAccountDeletionSweep calls the engine logic logicAccountDeletionSweep.
func (qc *QueryClient) LogicAccountDeletionSweep(ctx context.Context, args LogicAccountDeletionSweepArgs) (*Result, error) {
	call := LogicAccountDeletionSweepBuild(args)
	return qc.executeNamed(ctx, "logicAccountDeletionSweep", call)
}

func LogicAccountDeletionSweepBuild(args LogicAccountDeletionSweepArgs) string {
	var b strings.Builder
	b.WriteString("logicAccountDeletionSweep({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicAuditEventRetentionSweep -- Daily 02:00 UTC sweep over v1:identity:auditEvent rows older than IDENTITY_AUDIT_LOG_RETENTION_DAYS. Observation-only today: emits an 'identity.audit.retention.observed' event with the candidate count -- MemQL has no delete() mutation and AuditEvent's append-only semantics forbid soft-delete via active=false. Per-row delete lands when one of those gaps closes.
type LogicAuditEventRetentionSweepArgs struct {
	Event map[string]any
}

// LogicAuditEventRetentionSweep calls the engine logic logicAuditEventRetentionSweep.
func (qc *QueryClient) LogicAuditEventRetentionSweep(ctx context.Context, args LogicAuditEventRetentionSweepArgs) (*Result, error) {
	call := LogicAuditEventRetentionSweepBuild(args)
	return qc.executeNamed(ctx, "logicAuditEventRetentionSweep", call)
}

func LogicAuditEventRetentionSweepBuild(args LogicAuditEventRetentionSweepArgs) string {
	var b strings.Builder
	b.WriteString("logicAuditEventRetentionSweep({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicAutoJoinSI -- Triggered when a v1:cognition:space is created with status='active'. Auto-joins the creator's currently-active assistant as a v1:cognition:participant on the new space, with forUserId=creator and isGroupGA=true (so the participant guard prevents non-elevated callers from removing it via the Roster tab). This is the ONLY AI participant a space carries (maxAgents=1, one-assistant model copresent #124). Idempotent. Emits 'si.auto-joined' for observability.
type LogicAutoJoinSIArgs struct {
	Event map[string]any
}

// LogicAutoJoinSI calls the engine logic logicAutoJoinSI.
func (qc *QueryClient) LogicAutoJoinSI(ctx context.Context, args LogicAutoJoinSIArgs) (*Result, error) {
	call := LogicAutoJoinSIBuild(args)
	return qc.executeNamed(ctx, "logicAutoJoinSI", call)
}

func LogicAutoJoinSIBuild(args LogicAutoJoinSIArgs) string {
	var b strings.Builder
	b.WriteString("logicAutoJoinSI({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicBootstrapCluster -- Bootstraps the cluster's self-representation on first startup. Creates v1:cluster:cluster + v1:cluster:database + v1:cluster:identityProvider rows when no cluster row exists. Only BFF nodes run the create path. Idempotent: skips entirely if a cluster row already exists.
type LogicBootstrapClusterArgs struct {
	Event map[string]any
}

// LogicBootstrapCluster calls the engine logic logicBootstrapCluster.
func (qc *QueryClient) LogicBootstrapCluster(ctx context.Context, args LogicBootstrapClusterArgs) (*Result, error) {
	call := LogicBootstrapClusterBuild(args)
	return qc.executeNamed(ctx, "logicBootstrapCluster", call)
}

func LogicBootstrapClusterBuild(args LogicBootstrapClusterArgs) string {
	var b strings.Builder
	b.WriteString("logicBootstrapCluster({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicBootstrapSession -- Auto-creates a v1:cognition:session record when a v1:cognition:participant is created, with default device + stream state. Ensures every participant has a session tracking their real-time interaction state. Idempotent via queryParticipantSession existence check. Emits 'session.created' for downstream consumers.
type LogicBootstrapSessionArgs struct {
	Event map[string]any
}

// LogicBootstrapSession calls the engine logic logicBootstrapSession.
func (qc *QueryClient) LogicBootstrapSession(ctx context.Context, args LogicBootstrapSessionArgs) (*Result, error) {
	call := LogicBootstrapSessionBuild(args)
	return qc.executeNamed(ctx, "logicBootstrapSession", call)
}

func LogicBootstrapSessionBuild(args LogicBootstrapSessionArgs) string {
	var b strings.Builder
	b.WriteString("logicBootstrapSession({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicConflictDetection -- Triggered on new v1:data:record creation with a non-empty naturalKeyValue. Queries confirmed records for matching natural key + record type; if any exist, emits 'data.conflicts.detected' event for the UI's ConflictResolutionPanel. Never auto-resolves -- always requires human approval.
type LogicConflictDetectionArgs struct {
	Event map[string]any
}

// LogicConflictDetection calls the engine logic logicConflictDetection.
func (qc *QueryClient) LogicConflictDetection(ctx context.Context, args LogicConflictDetectionArgs) (*Result, error) {
	call := LogicConflictDetectionBuild(args)
	return qc.executeNamed(ctx, "logicConflictDetection", call)
}

func LogicConflictDetectionBuild(args LogicConflictDetectionArgs) string {
	var b strings.Builder
	b.WriteString("logicConflictDetection({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicConsolidateMemory -- Entry point for the daily memory-consolidation automation (#586). Per #586 the precise per-owner loop -- similarity clustering of the since-watermark episode batch, the blocking LLM distill per cluster, similarTo dedup, the confidence bump / decay arithmetic, and the max(createdAt) watermark advance -- runs in the Go harness consolidation handler (the same DSL-entry / Go-loop split the knowledge refresh-cron made), because the MemQL parser has neither arithmetic on number/datetime fields nor an in-DSL clustering primitive. This body is the scheduled trigger surface; the file header documents the full Go-handler contract it drives. Returns a sentinel until the handler is wired (mirrors logicRefreshDueKnowledgeDomains).
type LogicConsolidateMemoryArgs struct {
	Event map[string]any
}

// LogicConsolidateMemory calls the engine logic logicConsolidateMemory.
func (qc *QueryClient) LogicConsolidateMemory(ctx context.Context, args LogicConsolidateMemoryArgs) (*Result, error) {
	call := LogicConsolidateMemoryBuild(args)
	return qc.executeNamed(ctx, "logicConsolidateMemory", call)
}

func LogicConsolidateMemoryBuild(args LogicConsolidateMemoryArgs) string {
	var b strings.Builder
	b.WriteString("logicConsolidateMemory({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicDeregisterNode -- Records node shutdown by creating a v1:cluster:spawnEvent with action='stopped' and reason='system.shutdown'. Fires when the node is going down.
type LogicDeregisterNodeArgs struct {
	Event map[string]any
}

// LogicDeregisterNode calls the engine logic logicDeregisterNode.
func (qc *QueryClient) LogicDeregisterNode(ctx context.Context, args LogicDeregisterNodeArgs) (*Result, error) {
	call := LogicDeregisterNodeBuild(args)
	return qc.executeNamed(ctx, "logicDeregisterNode", call)
}

func LogicDeregisterNodeBuild(args LogicDeregisterNodeArgs) string {
	var b strings.Builder
	b.WriteString("logicDeregisterNode({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicEnsureDailySpaceForCaller -- Ensure today's daily space exists for the authenticated caller. Top-level Execute entry point for interactive clients; resolves userId from the request's auth context inside the dailyspace integration.
type LogicEnsureDailySpaceForCallerArgs struct {
}

// LogicEnsureDailySpaceForCaller calls the engine logic logicEnsureDailySpaceForCaller.
func (qc *QueryClient) LogicEnsureDailySpaceForCaller(ctx context.Context, args LogicEnsureDailySpaceForCallerArgs) (*Result, error) {
	call := LogicEnsureDailySpaceForCallerBuild(args)
	return qc.executeNamed(ctx, "logicEnsureDailySpaceForCaller", call)
}

func LogicEnsureDailySpaceForCallerBuild(args LogicEnsureDailySpaceForCallerArgs) string {
	_ = args
	return "logicEnsureDailySpaceForCaller({})"
}

// LogicEnsureDailySpaceOnAuthSession -- Fires on every v1:identity:authSession create (one per login). Calls dailyspace.ensureForUser for the authenticating user; the idempotent insert collapses to a no-op when today's daily already exists. This is the path that makes the cron-frequency concern moot -- every login guarantees today's daily exists before the SPA reads.
type LogicEnsureDailySpaceOnAuthSessionArgs struct {
	Event map[string]any
}

// LogicEnsureDailySpaceOnAuthSession calls the engine logic logicEnsureDailySpaceOnAuthSession.
func (qc *QueryClient) LogicEnsureDailySpaceOnAuthSession(ctx context.Context, args LogicEnsureDailySpaceOnAuthSessionArgs) (*Result, error) {
	call := LogicEnsureDailySpaceOnAuthSessionBuild(args)
	return qc.executeNamed(ctx, "logicEnsureDailySpaceOnAuthSession", call)
}

func LogicEnsureDailySpaceOnAuthSessionBuild(args LogicEnsureDailySpaceOnAuthSessionArgs) string {
	var b strings.Builder
	b.WriteString("logicEnsureDailySpaceOnAuthSession({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicGenerateResponse -- Generates and inserts an SI response when the Go cognition handler decides a non-streaming response is needed and emits this event with pre-loaded prompt data. Calls the prompt template, inserts a v1:cognition:utterance via mutationSendTextUtterance, and bumps participant presence to idle. Idempotent via queryHasSIResponseForReply.
type LogicGenerateResponseArgs struct {
	Event map[string]any
}

// LogicGenerateResponse calls the engine logic logicGenerateResponse.
func (qc *QueryClient) LogicGenerateResponse(ctx context.Context, args LogicGenerateResponseArgs) (*Result, error) {
	call := LogicGenerateResponseBuild(args)
	return qc.executeNamed(ctx, "logicGenerateResponse", call)
}

func LogicGenerateResponseBuild(args LogicGenerateResponseArgs) string {
	var b strings.Builder
	b.WriteString("logicGenerateResponse({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicKillSwitchSuspendsRunningPlans -- Triggered on v1:identity:user update. When preferences.computerUseEnabled flips true->false, transitions every running plan owned by that user (with computerUseScope set) to awaitingFeedback with feedbackReason='kill_switch_engaged'. Re-enable flips the flag back; resume is per-plan-explicit (no auto-resume on flag flip).
type LogicKillSwitchSuspendsRunningPlansArgs struct {
	Event map[string]any
}

// LogicKillSwitchSuspendsRunningPlans calls the engine logic logicKillSwitchSuspendsRunningPlans.
func (qc *QueryClient) LogicKillSwitchSuspendsRunningPlans(ctx context.Context, args LogicKillSwitchSuspendsRunningPlansArgs) (*Result, error) {
	call := LogicKillSwitchSuspendsRunningPlansBuild(args)
	return qc.executeNamed(ctx, "logicKillSwitchSuspendsRunningPlans", call)
}

func LogicKillSwitchSuspendsRunningPlansBuild(args LogicKillSwitchSuspendsRunningPlansArgs) string {
	var b strings.Builder
	b.WriteString("logicKillSwitchSuspendsRunningPlans({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicMagicLinkExpirySweep -- Hourly sweep that stamps consumedAt + consumedFromIP='system:expiry' on v1:identity:magiclink rows whose expiresAt is in the past, so the row reads as 'spent' in audit queries and any subsequent click is idempotently rejected by the consume handler's own expiresAt guard.
type LogicMagicLinkExpirySweepArgs struct {
	Event map[string]any
}

// LogicMagicLinkExpirySweep calls the engine logic logicMagicLinkExpirySweep.
func (qc *QueryClient) LogicMagicLinkExpirySweep(ctx context.Context, args LogicMagicLinkExpirySweepArgs) (*Result, error) {
	call := LogicMagicLinkExpirySweepBuild(args)
	return qc.executeNamed(ctx, "logicMagicLinkExpirySweep", call)
}

func LogicMagicLinkExpirySweepBuild(args LogicMagicLinkExpirySweepArgs) string {
	var b strings.Builder
	b.WriteString("logicMagicLinkExpirySweep({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicOnDelegationCreated -- Emits a 'delegation.created' event when a new v1:identity:delegation row lands. Carries the delegation id + identity / agent / role / scope fields for audit logging and downstream event processing.
type LogicOnDelegationCreatedArgs struct {
	Event map[string]any
}

// LogicOnDelegationCreated calls the engine logic logicOnDelegationCreated.
func (qc *QueryClient) LogicOnDelegationCreated(ctx context.Context, args LogicOnDelegationCreatedArgs) (*Result, error) {
	call := LogicOnDelegationCreatedBuild(args)
	return qc.executeNamed(ctx, "logicOnDelegationCreated", call)
}

func LogicOnDelegationCreatedBuild(args LogicOnDelegationCreatedArgs) string {
	var b strings.Builder
	b.WriteString("logicOnDelegationCreated({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicProvisionDailySpaceOnUserCreate -- Fires when a new v1:identity:user row lands. Delegates to the dailyspace.ensureForUser capability which owns the timezone math + idempotent insert of today's daily space for that user. dailySpaceEnabled gating lives inside the Go capability since the value sits under preferences and filter syntax doesn't navigate nested payload paths reliably.
type LogicProvisionDailySpaceOnUserCreateArgs struct {
	Event map[string]any
}

// LogicProvisionDailySpaceOnUserCreate calls the engine logic logicProvisionDailySpaceOnUserCreate.
func (qc *QueryClient) LogicProvisionDailySpaceOnUserCreate(ctx context.Context, args LogicProvisionDailySpaceOnUserCreateArgs) (*Result, error) {
	call := LogicProvisionDailySpaceOnUserCreateBuild(args)
	return qc.executeNamed(ctx, "logicProvisionDailySpaceOnUserCreate", call)
}

func LogicProvisionDailySpaceOnUserCreateBuild(args LogicProvisionDailySpaceOnUserCreateArgs) string {
	var b strings.Builder
	b.WriteString("logicProvisionDailySpaceOnUserCreate({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicPurgeExpiredArchivedSpaces -- Daily 02:00 UTC sweep that hard-deletes archived v1:cognition:space rows whose payload.expiresAt has passed (deadline pre-computed at archive time as archivedAt + retentionDays). Defensive: only acts on rows where status='archived' AND active=true AND expiresAt<now. Saved/scheduled/active spaces are untouched.
type LogicPurgeExpiredArchivedSpacesArgs struct {
	Event map[string]any
}

// LogicPurgeExpiredArchivedSpaces calls the engine logic logicPurgeExpiredArchivedSpaces.
func (qc *QueryClient) LogicPurgeExpiredArchivedSpaces(ctx context.Context, args LogicPurgeExpiredArchivedSpacesArgs) (*Result, error) {
	call := LogicPurgeExpiredArchivedSpacesBuild(args)
	return qc.executeNamed(ctx, "logicPurgeExpiredArchivedSpaces", call)
}

func LogicPurgeExpiredArchivedSpacesBuild(args LogicPurgeExpiredArchivedSpacesArgs) string {
	var b strings.Builder
	b.WriteString("logicPurgeExpiredArchivedSpaces({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicPurgeExpiredOutputScreenings -- Daily sweep over v1:safety:outputScreening rows past MEMQL_SAFETY_OUTPUT_SCREENING_RETENTION_DAYS (default 90). Currently observation-only: emits a 'safety.outputScreening.retention.observed' event with the candidate count. Per-row delete lands when the engine grows a delete() mutation -- mirrors logicPurgeExpiredSafetyClassifications.
type LogicPurgeExpiredOutputScreeningsArgs struct {
	Event map[string]any
}

// LogicPurgeExpiredOutputScreenings calls the engine logic logicPurgeExpiredOutputScreenings.
func (qc *QueryClient) LogicPurgeExpiredOutputScreenings(ctx context.Context, args LogicPurgeExpiredOutputScreeningsArgs) (*Result, error) {
	call := LogicPurgeExpiredOutputScreeningsBuild(args)
	return qc.executeNamed(ctx, "logicPurgeExpiredOutputScreenings", call)
}

func LogicPurgeExpiredOutputScreeningsBuild(args LogicPurgeExpiredOutputScreeningsArgs) string {
	var b strings.Builder
	b.WriteString("logicPurgeExpiredOutputScreenings({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicPurgeExpiredPolicyTraces -- Daily 02:30 UTC sweep over v1:platform:policyTrace rows older than MEMQL_POLICYTRACE_RETENTION_DAYS (default 90). Currently observation-only: emits a 'platform.policyTrace.retention.observed' event with the candidate count. Per-row delete lands when the engine grows a delete() mutation.
type LogicPurgeExpiredPolicyTracesArgs struct {
	Event map[string]any
}

// LogicPurgeExpiredPolicyTraces calls the engine logic logicPurgeExpiredPolicyTraces.
func (qc *QueryClient) LogicPurgeExpiredPolicyTraces(ctx context.Context, args LogicPurgeExpiredPolicyTracesArgs) (*Result, error) {
	call := LogicPurgeExpiredPolicyTracesBuild(args)
	return qc.executeNamed(ctx, "logicPurgeExpiredPolicyTraces", call)
}

func LogicPurgeExpiredPolicyTracesBuild(args LogicPurgeExpiredPolicyTracesArgs) string {
	var b strings.Builder
	b.WriteString("logicPurgeExpiredPolicyTraces({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicPurgeExpiredSafetyClassifications -- Daily sweep over v1:safety:classification rows past MEMQL_SAFETY_CLASSIFICATION_RETENTION_DAYS (default 90). Currently observation-only: emits a 'safety.classification.retention.observed' event with the candidate count. Per-row delete lands when the engine grows a delete() mutation -- mirrors the same gap purgeExpiredPolicyTraces + auditEventRetentionSweep document.
type LogicPurgeExpiredSafetyClassificationsArgs struct {
	Event map[string]any
}

// LogicPurgeExpiredSafetyClassifications calls the engine logic logicPurgeExpiredSafetyClassifications.
func (qc *QueryClient) LogicPurgeExpiredSafetyClassifications(ctx context.Context, args LogicPurgeExpiredSafetyClassificationsArgs) (*Result, error) {
	call := LogicPurgeExpiredSafetyClassificationsBuild(args)
	return qc.executeNamed(ctx, "logicPurgeExpiredSafetyClassifications", call)
}

func LogicPurgeExpiredSafetyClassificationsBuild(args LogicPurgeExpiredSafetyClassificationsArgs) string {
	var b strings.Builder
	b.WriteString("logicPurgeExpiredSafetyClassifications({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicRefreshDueKnowledgeDomains -- Reads candidate knowledge-domain rows via queryDueRefreshDomains; for each, the Go-side cron handler (registered by the planner-service init path) evaluates the elapsed-since-lastSeededAt check and spawns a trainSpecialist Plan per matching row. Per Q9 the schema-side cadence + runtime-side spawn are deliberately split -- the DSL filter is broad (active + non-null refreshCadenceDays), the precise elapsed-time math runs in Go where arithmetic on datetime fields is cheap.
type LogicRefreshDueKnowledgeDomainsArgs struct {
	Event map[string]any
}

// LogicRefreshDueKnowledgeDomains calls the engine logic logicRefreshDueKnowledgeDomains.
func (qc *QueryClient) LogicRefreshDueKnowledgeDomains(ctx context.Context, args LogicRefreshDueKnowledgeDomainsArgs) (*Result, error) {
	call := LogicRefreshDueKnowledgeDomainsBuild(args)
	return qc.executeNamed(ctx, "logicRefreshDueKnowledgeDomains", call)
}

func LogicRefreshDueKnowledgeDomainsBuild(args LogicRefreshDueKnowledgeDomainsArgs) string {
	var b strings.Builder
	b.WriteString("logicRefreshDueKnowledgeDomains({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicRegisterNode -- Registers this node on startup. Creates a v1:cluster:node record (using the peer's NodeId as the explicit concept id so later NodeStatusWriter rows share the same time-series timeline) and a v1:cluster:spawnEvent with action='spawned' and reason='system.startup'. Runs on every node type; safe to re-run on every restart.
type LogicRegisterNodeArgs struct {
	Event map[string]any
}

// LogicRegisterNode calls the engine logic logicRegisterNode.
func (qc *QueryClient) LogicRegisterNode(ctx context.Context, args LogicRegisterNodeArgs) (*Result, error) {
	call := LogicRegisterNodeBuild(args)
	return qc.executeNamed(ctx, "logicRegisterNode", call)
}

func LogicRegisterNodeBuild(args LogicRegisterNodeArgs) string {
	var b strings.Builder
	b.WriteString("logicRegisterNode({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicReleaseWorkspaceOnPlanTerminal -- On every v1:planner:plan update, checks the new status; if terminal (succeeded/failed/cancelled) AND a v1:workbench:workspace exists for the planId AND it is still provisioned, flips the concept row to released AND calls the workbench integration to remove the on-disk directory tree. Also fires the teardown unconditionally on terminal status even when no concept row exists -- the MVP Go integration provisions workspaces in-memory + on-disk without writing the concept row, so the teardown call cleans those up too. Idempotent on both paths.
type LogicReleaseWorkspaceOnPlanTerminalArgs struct {
	Event map[string]any
}

// LogicReleaseWorkspaceOnPlanTerminal calls the engine logic logicReleaseWorkspaceOnPlanTerminal.
func (qc *QueryClient) LogicReleaseWorkspaceOnPlanTerminal(ctx context.Context, args LogicReleaseWorkspaceOnPlanTerminalArgs) (*Result, error) {
	call := LogicReleaseWorkspaceOnPlanTerminalBuild(args)
	return qc.executeNamed(ctx, "logicReleaseWorkspaceOnPlanTerminal", call)
}

func LogicReleaseWorkspaceOnPlanTerminalBuild(args LogicReleaseWorkspaceOnPlanTerminalArgs) string {
	var b strings.Builder
	b.WriteString("logicReleaseWorkspaceOnPlanTerminal({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicRevokeExpiredDelegations -- Find every expired active delegation and soft-revoke it with `system:expiry` as the revoker. Returns the count processed.
type LogicRevokeExpiredDelegationsArgs struct {
	Now string
}

// LogicRevokeExpiredDelegations calls the engine logic logicRevokeExpiredDelegations.
func (qc *QueryClient) LogicRevokeExpiredDelegations(ctx context.Context, args LogicRevokeExpiredDelegationsArgs) (*Result, error) {
	call := LogicRevokeExpiredDelegationsBuild(args)
	return qc.executeNamed(ctx, "logicRevokeExpiredDelegations", call)
}

func LogicRevokeExpiredDelegationsBuild(args LogicRevokeExpiredDelegationsArgs) string {
	var b strings.Builder
	b.WriteString("logicRevokeExpiredDelegations({")
	b.WriteString("now: ")
	b.WriteString(fmt.Sprintf("%q", args.Now))
	b.WriteString("})")
	return b.String()
}

// LogicRolloverDailySpace -- Hourly cron tick. Delegates the entire per-user sweep to the dailyspace.rolloverAllUsers capability, which walks queryActiveUsers and calls ensureForUser per row. Returns a one-row summary the automation logs.
type LogicRolloverDailySpaceArgs struct {
	Event map[string]any
}

// LogicRolloverDailySpace calls the engine logic logicRolloverDailySpace.
func (qc *QueryClient) LogicRolloverDailySpace(ctx context.Context, args LogicRolloverDailySpaceArgs) (*Result, error) {
	call := LogicRolloverDailySpaceBuild(args)
	return qc.executeNamed(ctx, "logicRolloverDailySpace", call)
}

func LogicRolloverDailySpaceBuild(args LogicRolloverDailySpaceArgs) string {
	var b strings.Builder
	b.WriteString("logicRolloverDailySpace({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicVoiceMigrationOnSecondHuman -- Phase 7 of chat-architecture. Triggered when a user's activeSpaceId pointer changes. When exactly two humans become active in the same space, emits a public 'voice.migrated.group' canvas card plus per-user 'voice.migrated.private' cards announcing voice transport migration from Team to Group thread. Idempotent via content-addressed stateIds.
type LogicVoiceMigrationOnSecondHumanArgs struct {
	Event map[string]any
}

// LogicVoiceMigrationOnSecondHuman calls the engine logic logicVoiceMigrationOnSecondHuman.
func (qc *QueryClient) LogicVoiceMigrationOnSecondHuman(ctx context.Context, args LogicVoiceMigrationOnSecondHumanArgs) (*Result, error) {
	call := LogicVoiceMigrationOnSecondHumanBuild(args)
	return qc.executeNamed(ctx, "logicVoiceMigrationOnSecondHuman", call)
}

func LogicVoiceMigrationOnSecondHumanBuild(args LogicVoiceMigrationOnSecondHumanArgs) string {
	var b strings.Builder
	b.WriteString("logicVoiceMigrationOnSecondHuman({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}

// LogicWorkerInvocationRetentionSweep -- Daily 02:30 UTC sweep that soft-deletes v1:worker:invocation rows older than WORKER_INVOCATION_RETENTION_DAYS (default 90). Per-row windowing via addDuration since MemQL filters can't push duration math down. Per-user invocation queries filter on @skipDeleted so rows disappear from UIs the moment the soft-delete lands.
type LogicWorkerInvocationRetentionSweepArgs struct {
	Event map[string]any
}

// LogicWorkerInvocationRetentionSweep calls the engine logic logicWorkerInvocationRetentionSweep.
func (qc *QueryClient) LogicWorkerInvocationRetentionSweep(ctx context.Context, args LogicWorkerInvocationRetentionSweepArgs) (*Result, error) {
	call := LogicWorkerInvocationRetentionSweepBuild(args)
	return qc.executeNamed(ctx, "logicWorkerInvocationRetentionSweep", call)
}

func LogicWorkerInvocationRetentionSweepBuild(args LogicWorkerInvocationRetentionSweepArgs) string {
	var b strings.Builder
	b.WriteString("logicWorkerInvocationRetentionSweep({")
	b.WriteString("event: ")
	b.WriteString(renderMemQLValue(args.Event))
	b.WriteString("})")
	return b.String()
}
