#!/usr/bin/env bash
#
# scripts/dev/mint-node-tokens.sh
# ===============================
#
# Mints a class="node" JWT for every cluster-node binary the dev
# docker-compose stack runs (bff, voice, cognition, agent, planner)
# and writes a key=value snippet to .env.local.node-tokens that the
# compose env_file consumes via ${MEMQL_<TYPE>_NODE_TOKEN}
# indirection.
#
# Without this, every node boots with MEMQL_NODE_TOKEN unset, the
# inter-node NodeService.Stream interceptor rejects with
# `authorization header missing`, and every cross-node call (chat
# dispatch, greet-on-join, planner tasks, voice transcription
# routing) fails silently. memql#338.
#
# Called by `make dev-node-tokens-bootstrap` + scripts/dev/refresh.sh's
# step4b. Operators can also call it directly:
#
#   bash scripts/dev/mint-node-tokens.sh
#   docker compose -f docker/docker-compose.cluster.yml \
#     up -d --force-recreate bff voice cognition agent planner
#
# Per repo convention (CLAUDE.md): function-based structure. main()
# at the bottom invokes the steps in order.
set -euo pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly REPO_ROOT="$( cd "${SCRIPT_DIR}/../.." && pwd )"
readonly OUT_FILE="${REPO_ROOT}/.env.local.node-tokens"

# The cluster-node services the dev docker-compose stack runs. Each
# entry is `node-id:node-type`; the env-var key derives from the
# node-type (uppercased) per the compose interpolation convention.
readonly NODE_TARGETS=(
    "bff-local:bff"
    "voice-local:voice"
    "cognition-local:cognition"
    "agent-local:agent"
    "planner-local:planner"
)

function check_identity_container() {
    if ! docker ps --filter "name=^memql-identity$" --filter "status=running" --format '{{.Names}}' | grep -q "memql-identity"; then
        echo "ERROR: memql-identity container is not running."
        echo "Start the stack first: make dev-cluster-up"
        exit 1
    fi
}

function mint_one() {
    local node_id="$1"
    local node_type="$2"
    # `docker exec` prints the bearer to stdout; the subcommand's
    # diagnostic line goes to stderr and is shown to the operator.
    local bearer
    bearer=$(docker exec memql-identity /app/memql node-token mint \
        --node-id="${node_id}" \
        --node-type="${node_type}")
    if [ -z "${bearer}" ]; then
        echo "ERROR: node-token mint returned empty bearer for ${node_type}/${node_id}"
        exit 1
    fi
    printf '%s' "${bearer}"
}

function write_snippet() {
    local snippet="$1"
    # Mode 0600 -- the tokens are bearer credentials for the local
    # cluster; world-readable would let any process on the dev box
    # impersonate a cluster node against the running stack.
    umask 077
    printf '# Auto-generated by scripts/dev/mint-node-tokens.sh -- DO NOT EDIT BY HAND.\n# Tokens here are class="node" JWTs for the dev cluster.\n# Re-run `make dev-node-tokens-bootstrap` to refresh.\n%s' "${snippet}" > "${OUT_FILE}"
    chmod 0600 "${OUT_FILE}"
    echo "Wrote ${#NODE_TARGETS[@]} node tokens to ${OUT_FILE} (mode 0600)."
}

function main() {
    check_identity_container

    local snippet=""
    for target in "${NODE_TARGETS[@]}"; do
        local node_id="${target%%:*}"
        local node_type="${target##*:}"
        local key_name
        # MEMQL_BFF_NODE_TOKEN, MEMQL_VOICE_NODE_TOKEN, etc.
        key_name="MEMQL_$(echo "${node_type}" | tr '[:lower:]' '[:upper:]')_NODE_TOKEN"
        echo "[mint] ${node_type} (${node_id})"
        local bearer
        bearer="$(mint_one "${node_id}" "${node_type}")"
        snippet+="${key_name}=${bearer}"$'\n'
    done

    write_snippet "${snippet}"
    cat <<EOF

  Next: recreate the cluster nodes so they pick up the new tokens:

      docker compose -f docker/docker-compose.cluster.yml \\
          up -d --force-recreate bff voice cognition agent planner

  (scripts/dev/refresh.sh does this automatically as step 4b.)
EOF
}

main "$@"
