#!/usr/bin/env bash
# bootstrap.sh -- CI Tier 4 (#859) Bazel build-graph SPIKE bootstrap.
#
# EXPERIMENTAL. This is a throwaway-branch spike, NOT part of the build.
# It is intentionally not referenced by any .github/workflows/** or
# Makefile target. It writes root-level Bazel files INTO THE WORKING TREE
# (so Gazelle can see the Go module), installs bazelisk if needed, runs
# Gazelle to generate BUILD.bazel files, and attempts a build of the core
# engine package. See docs/ci/tier4-build-graph.md for the full plan.
#
# Run it on a scratch branch only:
#   git switch -c spike/bazel && bash scripts/bazel-spike/bootstrap.sh
# and DO NOT commit the generated root Bazel files to main until the spike
# is proven (per the decision record in the plan doc).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RULES_GO_VERSION="0.50.1"
GAZELLE_VERSION="0.39.1"

log() { printf '\n=== %s ===\n' "$*"; }

guard_scratch_branch() {
  local branch
  branch="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
  if [[ "$branch" == "main" ]]; then
    echo "REFUSING to run on main. This spike writes root Bazel files; run it on a scratch branch." >&2
    exit 1
  fi
  echo "Running spike on branch: $branch"
}

ensure_bazelisk() {
  if command -v bazel >/dev/null 2>&1 || command -v bazelisk >/dev/null 2>&1; then
    echo "bazel/bazelisk found: $(command -v bazel bazelisk | head -1)"
    return
  fi
  echo "bazel/bazelisk not found." >&2
  echo "Install it first, e.g.:  go install github.com/bazelbuild/bazelisk@latest" >&2
  echo "(or 'npm i -g @bazel/bazelisk', or your package manager), then re-run." >&2
  exit 1
}

write_module_bazel() {
  log "writing MODULE.bazel"
  cat >"$REPO_ROOT/MODULE.bazel" <<EOF
# SPIKE (CI Tier 4 / #859) -- generated by scripts/bazel-spike/bootstrap.sh.
# Scoped to the 'memql' module first (see docs/ci/tier4-build-graph.md).
module(name = "memql", version = "0.0.0")

bazel_dep(name = "rules_go", version = "$RULES_GO_VERSION")
bazel_dep(name = "gazelle", version = "$GAZELLE_VERSION")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.26.4")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
# use_repo(go_deps, ...)  # populated by: bazel mod tidy
EOF
}

write_bazelrc() {
  log "writing .bazelrc (remote-cache config is a placeholder)"
  cat >"$REPO_ROOT/.bazelrc" <<'EOF'
# SPIKE (CI Tier 4 / #859).
common --enable_bzlmod
build --@rules_go//go/config:pure          # CGO-free default graph
test --test_output=errors

# Remote cache -- fill in a BuildBuddy/bazel-remote endpoint to prove the
# cross-machine cache hit, then run with: bazel test //... --config=remote
build:remote --remote_cache=grpcs://YOUR-REMOTE-CACHE-ENDPOINT
build:remote --remote_timeout=60
EOF
  echo "1.26.4" >/dev/null  # (Go SDK pinned in MODULE.bazel; bazelisk picks its own version)
}

run_gazelle_and_build() {
  local bz; bz="$(command -v bazelisk || command -v bazel)"
  log "bazel mod tidy (resolve go_deps)"
  ( cd "$REPO_ROOT" && "$bz" mod tidy ) || echo "WARN: 'bazel mod tidy' needs network + may need use_repo wiring; see plan doc."
  log "gazelle: generate BUILD.bazel from the Go module"
  ( cd "$REPO_ROOT" && "$bz" run //:gazelle ) || echo "WARN: gazelle target not bootstrapped yet; add the gazelle rule per rules_go docs."
  log "build the core engine package (first real target)"
  ( cd "$REPO_ROOT" && "$bz" build //component/memql/... ) \
    || echo "WARN: expected on first run -- iterate on embedsrcs (DSL tree) + go_deps per the plan doc's hard-parts list."
  log "spike attempt complete -- see docs/ci/tier4-build-graph.md for next steps"
}

main() {
  guard_scratch_branch
  ensure_bazelisk
  write_module_bazel
  write_bazelrc
  run_gazelle_and_build
}

main "$@"
